//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Mapping of jurisdiction regions. */
export type Jurisdiction =
  | "None"
  | "NoJurisdiction"
  | "AU"
  | "BR"
  | "CA"
  | "US"
  | "AS"
  | "EU"
  | "USGov";
