//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { StatusData } from "../Engine/StatusData";

/** Represents the low and high values of fuel level for a fill-up. */
export interface FillUpExtrema {
  /** Gets or sets the maxima value. */
  maxima: StatusData;
  /** Gets or sets the maxima {@link FillUpExtremum} for the fill-up. */
  maximaPoint: unknown;
  /** Gets or sets the minima value. */
  minima: StatusData;
  /** Gets or sets the minima {@link FillUpExtremum} for the fill-up. */
  minimaPoint: unknown;
}
