//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FillUpExtrema } from "./FillUpExtrema";
import { FuelTankCapacity } from "./FuelTankCapacity";
import { FuelTransaction } from "./FuelTransaction";

/** An event representing adding fuel to a vehicle. */
export interface FuelUpEvent {
  /** Gets or sets the volume derived from fuel tank capacity. */
  derivedVolume: number;
  /** Gets or sets the difference in fuel out vs fuel in. */
  deviationFactor: number;
  /** Gets or sets the raw fuel transaction. */
  fuelTransactions: FuelTransaction[];
  /** Gets or sets the fuel tank capacity. */
  tankCapacity: FuelTankCapacity;
  /** Gets or sets the fuel tank level change. */
  tankLevelExtrema: FillUpExtrema;
  /** Gets or sets the total fuel used up to this point in time. */
  totalFuelUsed: number;
}
