//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FuelUsed } from "./FuelUsed";

/** An event representing fuel and energy used for a vehicle. */
export interface FuelAndEnergyUsed extends FuelUsed {
  /** Gets or sets the amount of energy used in Kwh. Default [null]. */
  totalEnergyUsedKwh: number;
  /** Gets or sets the volume of fuel used in Liters. Default [null]. */
  totalFuelUsed: number;
  /** Gets or sets the amount of idling energy used in Kwh. Default [null]. */
  totalIdlingEnergyUsedKwh: number;
}
