//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FuelTankCapacitySource } from "./FuelTankCapacitySource";

/** Represent a vehicle's fuel tank capacity and how it was derived. */
export interface FuelTankCapacity {
  /** Gets or sets the tank capacity source. */
  source: FuelTankCapacitySource;
  /** Gets or sets the volume (L). */
  volume: number;
}
