//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { DeviceSearch } from "../DeviceSearch";

/** The object used to specify the arguments when searching for a {@link FuelSnapshotRecord}. */
export interface FuelSnapshotRecordSearch extends Search {
  /**
   * Gets or sets the device search criteria for the {@link FuelSnapshotRecord} records with this {@link DeviceSearch} Id. Available DeviceSearch options are:.
   *  <list><item><description>Id</description><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets the from date, which is used to search for {@link FuelSnapshotRecord} records recorded on or after this date. */
  fromDate: Date;
  /** Gets or sets the IncludeAdjacent flag which, when true, includes the {@link FuelSnapshotRecord} records immediately before and after the date range specified */
  includeAdjacent: boolean;
  /** Gets or sets the isWaitingForData flag which is used to search for {@link FuelSnapshotRecord} records recorded with a isWaitingForData flag set to true */
  isWaitingForData: boolean;
  /** Gets or sets the to date, which is used to search for {@link FuelSnapshotRecord} records recorded on or before this date. */
  toDate: Date;
}
