//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { FuelTransactionProvider } from "./FuelTransactionProvider";
import { DeviceSearch } from "../DeviceSearch";
import { UserSearch } from "../UserSearch";

/** The object used to specify the arguments when searching for a {@link FuelTransaction}. */
export interface FuelTransactionSearch extends Search {
  /**
   * Gets or sets search for FuelTransactions for this {@link DeviceSearch} Id.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets the DriverName. */
  driverName: string;
  /** Gets or sets search for Fuel Transactions with this External Reference. Wildcard can be used by prepending/appending "%" to string. Example "%reference%". */
  externalReference: string;
  /** Gets or sets the from date, which is used to search for FuelTransactions that occur on or after this date. */
  fromDate: Date;
  /** Gets or sets a value indicating whether to include source data with transaction. Source data can be a large string, therefore, optionally exclude it from results. */
  includeSourceData: boolean;
  /** Gets or sets the maximum version for which FuelTransactions should be searched. */
  maxVersion: number;
  /** Gets or sets search by the {@link FuelTransactionProvider}. */
  provider: FuelTransactionProvider;
  /** Gets or sets the to date, which is used to search for FuelTransactions that occur on or before this date. */
  toDate: Date;
  /**
   * Gets or sets search for FuelTransactions for this {@link UserSearch} Id.
   *  Available UserSearch options are:
   *  <list><item><description>Id</description></item></list>
   */
  userSearch: UserSearch;
  /** Gets or sets the VehicleIdentificationNumber. */
  vehicleIdentificationNumber: string;
}
