//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 * Confidence of the fuel event data, derived from how many data points successfully matched to calculate a
 *  {@link FuelUpEvent}.
 */
export enum FuelUpEventConfidences {
  /** None */
  None = "None",
  /** Fuel level based {@link FuelUpEvent} */
  FuelLevel = "FuelLevel",
  /** The {@link FuelUpEvent} that matched on trip stop date. */
  TripStop = "TripStop",
  /** The {@link FuelUpEventConfidences.FuelTransaction} based {@link FuelUpEvent} */
  FuelTransaction = "FuelTransaction",
  /** {@link FuelUpEventConfidences.FuelTransaction} based {@link FuelUpEvent} that has a matched device */
  DeviceMatchedFuelTransaction = "DeviceMatchedFuelTransaction",
  /** {@link FuelUpEventConfidences.FuelTransaction} based {@link FuelUpEvent} that has matched trip stop by location */
  LocationMatchedFuelTransaction = "LocationMatchedFuelTransaction",
  /** {@link FuelUpEventConfidences.FuelTransaction} based {@link FuelUpEvent} that has matched trip stop by date */
  TripStopFuelTransaction = "TripStopFuelTransaction",
  /**
   * Fuel level based {@link FuelUpEvent} matched to {@link FuelUpEventConfidences.FuelTransaction} based
   *  {@link FuelUpEvent} by datetime and device
   */
  DeviceFuelLevelMatchedFuelTransaction = "DeviceFuelLevelMatchedFuelTransaction",
  /**
   * Fuel level based {@link FuelUpEvent} matched to {@link FuelUpEventConfidences.FuelTransaction} based
   *  {@link FuelUpEvent} where locations match
   */
  LocationFuelLevelMatchedFuelTransaction = "LocationFuelLevelMatchedFuelTransaction",
  /** The {@link Device} was not communicating at the time of transaction */
  NotCommunicating = "NotCommunicating",
  /** Fuel level based {@link FuelUpEvent} could not be determined as there is not enough data */
  FuelLevelIndeterminate = "FuelLevelIndeterminate",
  /** {@link FuelUpEventConfidences.FuelTransaction} based {@link FuelUpEvent} that has a matched driver */
  DriverMatchedFuelTransaction = "DriverMatchedFuelTransaction",
  /** Fuel used inconsistent */
  FuelUsedInconsistent = "FuelUsedInconsistent",
  /** The {@link Device} is reporting electric energy usage. */
  EngineElectricEnergy = "EngineElectricEnergy",
}
