//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 * A Third Party Fault State Type
 *  Reference: https://developers.geotab.com/myGeotab/apiReference/objects/FaultState
 */
export type FaultState = "None" | "Active" | "Pending";
