//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Represents the result of a response. */
export type ResponseResult = "Unknown" | "Failed" | "Completed";
