//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** A specific type of StoreForward exception. */
export enum StoreForwardExceptionType {
  /** No diagnostic */
  None = "None",
  /** A general exception occurred. */
  Exception = "Exception",
  /** The server is not configured as a sync source. */
  SyncNotAllowed = "SyncNotAllowed",
}
