//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 *  The {@link ThirdPartyDataRecord} type.
 *
 * @deprecated
 */
export type ThirdPartyDataRecordType =
  | "None"
  | "ThirdPartyGpsRecord"
  | "ThirdPartyStatusRecord"
  | "ThirdPartyGenericStatusRecord"
  | "ThirdPartyAccelerationRecord"
  | "ThirdPartyVinRecord"
  | "ThirdPartyJ1939FaultRecord"
  | "ThirdPartyObdiiFaultRecord"
  | "ThirdPartyJ1708FaultRecord"
  | "ThirdPartyGenericFaultRecord"
  | "InsightsStatusRecord"
  | "ThirdPartyDriverChangeRecord"
  | "ThirdPartyBinaryRecord"
  | "ThirdPartyBluetoothRecord";
