//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Different types of responses that can come from {@link EldPingResponse}, {@link EldSubmitResponse} and {@link EldError.ErrorType} in the response. */
export type EldResponseStatus =
  | "Success"
  | "Error"
  | "Warning"
  | "Information"
  | "NotValidated"
  | "InvalidRegistrationData"
  | "EldDecertified"
  | "Timeout";
