//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** ELD output validation message types. */
export enum EldValidationEntityType {
  /** The error entity type cannot be determined or was not provided. */
  None = "None",
  /** The error entity type is a {@link Device}. */
  Vehicle = "Vehicle",
  /** The error entity type is a {@link Driver}. */
  Driver = "Driver",
}
