//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { UserSearch } from "../UserSearch";
import { ExceptionEventSearch } from "./ExceptionEventSearch";

/**
 *  The object used to specify the arguments when searching for {@link ExceptionEventComment}s.
 *  See comments on each nested {@link Search} for what parameters are supported.
 */
export interface ExceptionEventCommentSearch extends Search {
  /**
   * Gets or sets the {@link ExceptionEventCommentSearch.ExceptionEventSearch} used to find comments related to particular {@link ExceptionEvent}s.
   *
   * @remarks All search properties are supported. When specified, ExceptionEvents will be populated.
   */
  exceptionEventSearch: ExceptionEventSearch;
  /** Gets or sets the ToDate to filter only {@link ExceptionEventComment}s that have been created since the date. */
  fromDate: Date;
  /** Gets or sets the {@link Boolean} indicating whether to populate ExceptionEvents on the result. */
  populateExceptionEvent: boolean;
  /** Gets or sets the ToDate to filter only {@link ExceptionEventComment}s that have been created up to the date. */
  toDate: Date;
  /** Gets or sets the {@link ExceptionEventCommentSearch.UserSearch} used to filter for {@link ExceptionEventComment}s created by a specific user. */
  userSearch: UserSearch;
}
