//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The mode of the {@link Rule}. */
export type ExceptionRuleMode =
  | "Inside"
  | "Outside"
  | "StopInside"
  | "StopOutside"
  | "EnteringZone"
  | "ExitingZone";
