//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Defines options for a map server request. */
export type SpeedLimitRequestOptions =
  | "None"
  | "NoEstimates"
  | "NoCommunity"
  | "NoCommercial"
  | "NoSnapping"
  | "Truck";
