//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { Device } from "../Device";

/** The entity that contains the data for the {@link TachographDriverActivity} tachograph driver activity extractor. */
export interface TachographDriverActivity extends Entity {
  /** Gets or sets the activity in this telemetry. */
  activity: string;
  /** Gets or sets the time of this telemetry. */
  dateTime: Date;
  /** Gets or sets the {@link TachographDriverActivity.Device} id. */
  device: Device;
  /** Gets or sets a value indicating if is part of the crew. */
  isCrew: boolean;
  /** Gets or sets the nation (specific country code from tachograph driver card). */
  nation: string;
  /** Gets or sets the slot. */
  slot: string;
}
