//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { User } from "../User";
import { WeekRest } from "./WeekRest";

/** The entity that contains the data for the {@link TachographDrivingTimeStatus} tachograph driving time status extractor. */
export interface TachographDrivingTimeStatus extends Entity {
  /** Gets or sets the Active daily driving start in seconds. */
  activeDailyDrivingStart: number;
  /** Gets or sets the Active daily working start in seconds. */
  activeDailyWorkingStart: number;
  /** Gets or sets the Activity last vehicle. */
  activityLastVehicle: string;
  /** Gets or sets the Activity status. */
  activityStatus: string;
  /** Gets or sets the Biweekly driving available time in seconds. */
  biweeklyDrivingAvailableTime: number;
  /** Gets or sets the Continuous driving start in seconds. */
  continuousDrivingStart: number;
  /** Gets or sets the Continuous driving time in seconds. */
  continuousDrivingTime: number;
  /** Gets or sets the Continuous working start in seconds. */
  continuousWorkingStart: number;
  /** Gets or sets the Continuous working time in seconds. */
  continuousWorkingTime: number;
  /** Gets or sets the Cumulated biweekly driving time in seconds. */
  cumulatedBiweeklyDrivingTime: number;
  /** Gets or sets the Cumulated weekly driving time in seconds. */
  cumulatedWeeklyDrivingTime: number;
  /** Gets or sets the Current week working time in seconds. */
  currentWeekWorkingTime: number;
  /** Gets or sets the Daily current fixed week rest. */
  dailyCurrentFixedWeekRest: WeekRest;
  /** Gets or sets the Daily driving available time in seconds. */
  dailyDrivingAvailableTime: number;
  /** Gets or sets the Daily driving long day count in seconds. */
  dailyDrivingLongDayCount: number;
  /** Gets or sets the Daily driving rest minimal type. */
  dailyDrivingRestMinType: string;
  /** Gets or sets the Daily driving time in seconds. */
  dailyDrivingTime: number;
  /** Gets or sets the Daily driving time limit in seconds. */
  dailyDrivingTimeLimit: number;
  /** Gets or sets the Daily fixed Week Date. */
  dailyFixedWeekDate: Date;
  /** Gets or sets the Daily rest type. */
  dailyRestType: string;
  /** Gets or sets the Daily working time in seconds. */
  dailyWorkingTime: number;
  /** Gets or sets the Last daily rest. */
  lastDailyRest: Date;
  /** Gets or sets the Last Known Vehicle. */
  lastKnownVehicle: string;
  /** Gets or sets the Next compensation duration in seconds. */
  nextCompensationDuration: number;
  /** Gets or sets the Next compensation limit in seconds. */
  nextCompensationLimit: number;
  /** Gets or sets the Next rest maximum start time in seconds. */
  nextRestMaxStartTime: number;
  /** Gets or sets the Pending break time in seconds. */
  pendingBreakTime: number;
  /** Gets or sets the Pending compensations in seconds. */
  pendingCompensations: number;
  /** Gets or sets the Potential split daily rest. */
  potentialSplitDailyRest: boolean;
  /** Gets or sets the Previous fixed week rest. */
  previousFixedWeekRest: WeekRest;
  /** Gets or sets the Previous week weekly driving time in seconds. */
  previousWeekWeeklyDrivingTime: number;
  /** Gets or sets the Previous week working time in seconds. */
  previousWeekWorkingTime: number;
  /** Gets or sets the Rest activity start. */
  restActivityStart: Date;
  /** Gets or sets the Rest duration in seconds. */
  restDuration: number;
  /** Gets or sets the {@link TachographDrivingTimeStatus.User} in this telemetry. */
  user: User;
  /** Gets or sets the Weekly driving available time in seconds. */
  weeklyDrivingAvailableTime: number;
  /** Gets or sets the Weekly period daily driving count in seconds. */
  weeklyPeriodDailyDrivingCount: number;
  /** Gets or sets the Weekly period reduced rest count in seconds. */
  weeklyPeriodReducedRestCount: number;
  /** Gets or sets the Weekly period regular rest count in seconds. */
  weeklyPeriodRegularRestCount: number;
  /** Gets or sets the Weekly period start. */
  weeklyPeriodStart: Date;
  /** Gets or sets the Weekly rest maximum start time. */
  weeklyRestMaxStartTime: Date;
  /** Gets or sets the Weekly rest minimal type. */
  weeklyRestMinType: string;
  /** Gets or sets the Work activity status. */
  workActivityStatus: string;
}
