//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../../Search";

/** The object used to specify the arguments when searching for {@link TachographCompanyCard}. */
export interface TachographCompanyCardSearch extends Search {
  /** Gets or sets search for tachograph company cards that match the card number. */
  cardNumber: string;
  /** Gets or sets search for tachograph company cards with this icc. */
  icc: number;
  /**
   * Gets or sets search for tachograph company cards
   *  where the company card is valid at this time, and it is not expired.
   */
  isValidAt: Date;
  /**
   * Gets or sets search for tachograph company cards that match this status.
   *  The available values are:
   *  <list><item><description>"Available": Company card available.</description></item><item><description>"Busy": Company card authenticating.</description></item><item><description>"Offline": Company card disconnected.</description></item></list>
   */
  status: string;
}
