//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../../Entity";
import { TachographCompanyCardStatus } from "./TachographCompanyCardStatus";

/** Represents a tachograph company card used to identify transport companies in EU countries. */
export interface TachographCompanyCard extends Entity {
  /** Gets or sets the company's address. */
  address: string;
  /** Gets or sets the card authority. */
  cardAuthority: string;
  /** Gets or sets the card number. */
  cardNumber: string;
  /** Gets or sets the company name of the card. */
  companyName: string;
  /** Gets or sets the expiry of the card. */
  expiry: Date;
  /** Gets or sets the ICC number of the card. */
  icc: number;
  /** Gets or sets the last time this card was updated. */
  lastUpdate: Date;
  /** Gets or sets the time this card was registered on the system. */
  registrationTime: Date;
  /** Gets or sets the source of the card. */
  source: string;
  /** Gets or sets the {@link TachographCompanyCardStatus} of the card. */
  status: TachographCompanyCardStatus;
  /** Gets or sets the validity of the card. */
  validity: Date;
}
