//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { EntityType } from "./EntityType";
import { AddInData } from "../AddInData";

/** Represents a entity-linked setting in JSON format. Every setting has an specific key. */
export interface EntitySetting extends Entity {
  /** Gets or sets the {@link AddInData} for this setting. */
  data: AddInData;
  /** Gets or sets the entity identifier of this setting. */
  entityId: string;
  /** Gets or sets the entity type of this setting. */
  entityType: EntityType;
  /** Gets or sets the key for this setting. */
  key: string;
  /** Gets or sets the setting value of this setting. */
  settingValue: string;
}
