//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Extension of legal files: 0 refers to 'tgd', 1 refers to 'ddd', and 2 refers to 'V1b'. */
export type TachographFileFormat = "Tgd" | "Ddd" | "V1B";
