//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { GroupSearch } from "./GroupSearch";

/** The object used to specify the arguments when searching for {@link AddInData}. */
export interface AddInDataSearch extends Search {
  /** Gets or sets the add-in identifier. */
  addInId: string;
  /**
   * Gets or sets search for Devices that are a member of these {@link GroupSearch}(s).
   *  Available
   *  GroupSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  groups: GroupSearch[];
  /** Gets or sets the select clause which decides which properties of the stored objects are returned. */
  selectClause: string;
  /** Gets or sets the where clause which filters the data that is returned. */
  whereClause: string;
}
