//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { DutyStatusLog } from "./DutyStatusLog";
import { User } from "./User";

/** An AnnotationLog is a comment that can be associated with a {@link DutyStatusLog}. The {@link Driver} is the author of the AnnotationLog. */
export interface AnnotationLog extends EntityWithVersion {
  /** Gets or sets the annotation text associated with the log. */
  comment: string;
  /** Gets or sets the date and time the log was created. */
  dateTime: Date;
  /** Gets or sets the {@link User} who created the log. */
  driver: User;
  /** Gets or sets the {@link AnnotationLog.DutyStatusLog} which this log belongs to. */
  dutyStatusLog: DutyStatusLog;
}
