//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/** The object used to specify the arguments when searching for {@link AssetLinkDetailsSearch} record(s). */
export interface AssetLinkDetailsSearch extends Search {
  /**
   * Gets or sets search for AssetLink that was active at this date or after.
   *  Set to UTC now to search for only currently active AssetLink.
   */
  activeFrom: Date;
  /** Gets or sets search for AssetLink that was active at this date or before. */
  activeTo: Date;
  /** Gets or sets the AssetLink identifier. */
  assetLinkId: string;
  /**
   * Gets or sets source device search for AssetLinkSearch attached to this {@link DeviceSearch} Id.
   *  Available DeviceSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  deviceSearch: DeviceSearch;
}
