//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { User } from "./User";
import { DeviceSearch } from "./DeviceSearch";

/** The object used to specify the arguments when searching for {@link AssetSeparationSubscriptionSearch} record(s). */
export interface AssetSeparationSubscriptionSearch extends Search {
  /** Gets or sets search for subscriptions created at this date or after. */
  createdFrom: Date;
  /** Gets or sets search for subscriptions created at this date or before. */
  createdTo: Date;
  /** Gets or sets the current active link id. */
  currentActiveLinkId: string;
  /** Gets or sets the device to search in either Vehicle1 or Vehicle2. */
  deviceSearch: DeviceSearch;
  /**
   * Gets or sets the second vehicle id to search for subscriptions between two specific vehicles.
   *  Used in combination with Vehicle to find subscriptions between two vehicles regardless of order.
   */
  deviceSearch2: DeviceSearch;
  /** Gets or sets search for subscriptions with last alert at this date or after. */
  lastAlertFrom: Date;
  /** Gets or sets search for subscriptions with last alert at this date or before. */
  lastAlertTo: Date;
  /** Gets or sets the user. */
  user: User;
}
