//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { DeviceLinkType } from "./DeviceLinkType";
import { AssetLinkDetails } from "./AssetLinkDetails";

/** A particular instance of an {@link AssetLink}. */
export interface AssetLink extends Entity {
  /** Gets or sets the {@link AssetLink.AssetLinkDetails}(s) that are currently active. */
  assetLinkDetails: AssetLinkDetails[];
  /** Gets or sets the description. */
  description: string;
  /** Gets or sets if the link is Active. */
  isActive: boolean;
  /** Gets or sets the link type */
  linkType: DeviceLinkType;
}
