//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Device } from "./Device";

/** This entity allows you to track high voltage battery degradation over the lifetime of your BEVs and PHEVs. We use historical driving and charging data to estimate usable battery capacity. */
export interface BatteryStateOfHealth {
  /**
   * Gets or sets the lower bound of the vehicle's usable battery capacity on the detection date, measured in kWh.
   *  <para />
   *  This means that there is a 90% probability that the true usable battery capacity is between CurrentBatteryCapacityLowerBoundKwh and CurrentBatteryCapacityUpperBoundKwh.
   */
  currentBatteryCapacityLowerBoundKwh: number;
  /**
   * Gets or sets the usable battery capacity on the detection date, measured in kWh.
   *  <para />
   *  The mean value is our best guess at the vehicle's true usable battery capacity.
   */
  currentBatteryCapacityMeanKwh: number;
  /**
   * Gets or sets the upper bound of the vehicle's usable battery capacity on the detection date, measured in kWh.
   *  <para />
   *  This means that there is a 90% probability that the true usable battery capacity is between CurrentBatteryCapacityLowerBoundKwh and CurrentBatteryCapacityUpperBoundKwh.
   */
  currentBatteryCapacityUpperBoundKwh: number;
  /** Gets or sets the date and time (UTC, ISO 8601 format) when the {@link BatteryStateOfHealth} was calculated. */
  detectionDate: Date;
  /** Gets or sets the {@link Device} associated with the {@link BatteryStateOfHealth}. */
  device: Device;
  /**
   * Gets or sets the lower bound of the vehicle's usable battery capacity when the vehicle was new, measured in kWh.
   *  <para />
   *  This means that there is a 90% probability that the true usable battery capacity is between OriginalBatteryCapacityLowerBoundKwh and OriginalBatteryCapacityUpperBoundKwh.
   *  The original capacity is calculated based on data collected from other vehicles of the same make, model, year and trim. This value may be updated as we gather more information on this particular trim.
   */
  originalBatteryCapacityLowerBoundKwh: number;
  /**
   * Gets or sets the mean original battery capacity value, measured in kWh.
   *  <para />
   *  The mean value is our best guess at the true original battery capacity when the vehicle was new.
   *  The original capacity is calculated based on data collected from other vehicles of the same make, model, year and trim. This value may be updated as we gather more information on this particular trim.
   */
  originalBatteryCapacityMeanKwh: number;
  /**
   * Gets or sets the upper bound of the vehicle's usable battery capacity when the vehicle was new, measured in kWh.
   *  <para />
   *  This means that there is a 90% probability that the true usable battery capacity is between OriginalBatteryCapacityLowerBoundKwh and OriginalBatteryCapacityUpperBoundKwh.
   *  The original capacity is calculated based on data collected from other vehicles of the same make, model, year and trim. This value may be updated as we gather more information on this particular trim.
   */
  originalBatteryCapacityUpperBoundKwh: number;
  /**
   * Gets or sets the state of health's lower bound value.
   *  <para />
   *  state of health = current battery capacity / original battery capacity
   *  There is a 90% probability that the true usable battery capacity is between StateOfHealthLowerBound and StateOfHealthUpperBound.
   */
  stateOfHealthLowerBound: number;
  /**
   * Gets or sets the mean state of health value.
   *  <para />
   *  The mean value is our best guess at the true battery State of Health. It is calculated via the following formula:
   *  state of health = current battery capacity / original battery capacity
   */
  stateOfHealthMean: number;
  /**
   * Gets or sets the state of health's upper bound value.
   *  <para />
   *  state of health = current battery capacity / original battery capacity
   *  There is a 90% probability that the true usable battery capacity is between StateOfHealthLowerBound and StateOfHealthUpperBound.
   */
  stateOfHealthUpperBound: number;
  /** Gets or sets the vehicle identification number (VIN). Must be 17 characters. */
  vin: string;
}
