//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/** The object used to specify the arguments when searching for a {@link BatteryStateOfHealth}. */
export interface BatteryStateOfHealthSearch extends Search {
  /**
   * Gets or sets filter by the {@link DeviceSearch} options.
   *  Providing a device ID will search for any BatteryStateOfHealth(s) that are assigned to that Device.
   *  Providing deviceIds will search for any BatteryStateOfHealth(s) that are assigned to these Devices.
   *  Providing the Groups will search for BatteryStateOfHealth(s) for that have Devices in that group.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>DeviceIds</description></item><item><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets the from date, which is used to search for BatteryStateOfHealth(s) calculated on or after this date. */
  fromDate: Date;
  /** Gets or sets the to date, which is used to search for BatteryStateOfHealth(s) calculated on or before this date. */
  toDate: Date;
}
