//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The enum for the type of CalculationMethod */
export type CalculationMethod =
  | "Unknown"
  | "BatteryEstimation"
  | "SoCEstimation";
