//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { CameraDeviceStatus } from "./CameraDeviceStatus";

/** The object used to specify the arguments when searching for {@link CameraStatus}. */
export interface CameraStatusSearch extends Search {
  /** Gets or sets the camera id(s) to search by. */
  cameraIds: string[];
  /** Gets or sets the maximum version to search. */
  maxVersion: number;
  /** Gets or sets the camera status(es) to search by. */
  statuses: CameraDeviceStatus[];
  /** Gets or sets the version to search from (for feed operations). */
  version: number;
}
