//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 * The camera health status. Values align with the Video device health diagnostic
 *  (0 = healthy / 1 = unstable / 2 = unhealthy / 3 = not working).
 */
export type CameraHealthStatus =
  | "Healthy"
  | "Unstable"
  | "Unhealthy"
  | "NotWorking"
  | "Pending";
