//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { CameraHealthStatus } from "./CameraHealthStatus";

/**
 *  The object used to specify the arguments when searching for {@link CameraHealth}.
 */
export interface CameraHealthSearch extends Search {
  /** Gets or sets the camera id(s) to search by. */
  cameraIds: string[];
  /** Gets or sets the maximum row version of the {@link CameraHealth} search criteria. */
  maxVersion: number;
  /** Gets or sets the health status(es) to search by. */
  statuses: CameraHealthStatus[];
  /** Gets or sets the row version of the {@link CameraHealth} search criteria. */
  version: number;
}
