//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { RuleSearch } from "./Exceptions/RuleSearch";
import { UserSearch } from "./UserSearch";

/**
 *  The object used to specify the arguments when searching for {@link CoachingSession}(s).
 *
 * @deprecated
 */
export interface CoachingSessionSearch extends Search {
  /** Gets or sets the start date for the coaching session search. */
  fromDate: Date;
  /**
   * Gets or sets filter by the {@link RuleSearch} options. Providing a Rule ID
   *  will search for any Coaching Sessions recorded for that Rule.
   *  Available RuleSearch options are:
   *  <list><item><description>Id</description></item></list>
   */
  ruleSearch: RuleSearch;
  /**
   * Gets or sets a case-insensitive filter by multiple names of the {@link CoachingSessionState}.
   *  Possible values: "New", "Active", "Completed".
   *  When multiple states are specified, the search returns sessions matching any of the specified states (OR logic).
   */
  states: string[];
  /** Gets or sets the end date for the coaching session search. */
  toDate: Date;
  /**
   * Gets or sets the filter by the {@link UserSearch} options. Providing a User ID will search
   *  for any Coaching Sessions recorded for that User.
   *  Providing Groups will search Coaching Sessions recorded for Users that are members of the provided GroupSearch(s) or
   *  their children.
   *  Available UserSearch options are:
   *  <list><item><description>Id</description></item><item><description>DriverGroups</description></item><item><description>DriverGroupFilterCondition</description></item><item><description>CompanyGroups</description></item><item><description>UserGroupFilterCondition</description></item></list>
   */
  userSearch: UserSearch;
}
