//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The Custom Data Section enumeration. Custom data can be made up of three separate messages. This enumeration is used internally to identify which part(s) of the {@link CustomData} is being used. */
export type CustomDataSections = "None" | "A" | "B" | "C" | "Header" | "All";
