//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { PropertySetSearch } from "./PropertySetSearch";
import { PropertySearch } from "./PropertySearch";

/** A new search property for entities that support custom properties. */
export interface CustomPropertySearch extends Search {
  /**
   * Gets or sets search for Entities that are a member of these {@link PropertySearch}(s). Each PropertySearch is an object within the array.
   *  Available
   *  PropertySearch options are:
   *  <list><item><description>Id</description></item></list>
   */
  propertySearches: PropertySearch[];
  /**
   * Gets or sets search for Entities that are a member of these {@link PropertySetSearch}(s). Each PropertySetSearch is an object within the array.
   *  Available
   *  PropertySetSearch options are:
   *  <list><item><description>Id</description></item><item><description>Groups</description></item></list>
   */
  propertySetSearches: PropertySetSearch[];
  /**
   * Gets or sets search for Properties with this Value. Wildcard can be used by prepending/appending "%" to string. Example
   *  "%Value%".
   */
  value: string;
}
