//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Device } from "./Device";

/** Generic Custom Data from a GO unit that was sent through from a third-party device that is attached to the serial port. */
export interface CustomData extends Entity {
  /** Gets or sets the custom data in binary format. Default [empty]. */
  data: number[];
  /** Gets or sets the date and time the log was created. */
  dateTime: Date;
  /** Gets or sets the {@link Device} for which the data was recorded. */
  device: Device;
}
