//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/** The object used to specify the arguments when searching for {@link CustomData}. */
export interface CustomDataSearch extends Search {
  /**
   * Gets or sets search for CustomData recorded for this {@link DeviceSearch} Id.
   *  Available DeviceSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for CustomData that was recorded at this date or after. */
  fromDate: Date;
  /** Gets or sets the maximum Id of the search criteria. */
  maxId: string;
  /** Gets or sets the minimum Id of the search criteria. */
  minId: string;
  /** Gets or sets search for CustomData that was recorded at this date or before. */
  toDate: Date;
}
