//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntity } from "./NameEntity";
import { ReportTypedArgument } from "./ReportTypedArgument";
import { ReportDestination } from "./ReportDestination";
import { ReportFrequency } from "./ReportFrequency";
import { Group } from "./Group";
import { User } from "./User";
import { ReportPeriod } from "./ReportPeriod";
import { GroupFilter } from "./GroupFilter";
import { ReportTemplate } from "./ReportTemplate";

/** Used to represent the schedule for emailed reports and dashboard graphic elements. */
export interface CustomReportSchedule extends NameEntity {
  /** Gets or sets the arguments of scheduled report. */
  arguments: ReportTypedArgument;
  /** Gets or sets argument of the report represented in Json formatted text. */
  argumentsJsonText: string;
  /** Gets or sets the description of the report schedule. */
  description: string;
  /** Gets or sets the {@link ReportDestination} (email or dashboard) of scheduled report. */
  destination: ReportDestination;
  /** Gets or sets the frequency of scheduled report. */
  frequency: ReportFrequency;
  /** Gets or sets the {@link Group}(s) collection. */
  groups: Group[];
  /** Gets or sets {@link Group}(s) that define the groups that dashboard/email to be sent to all users under it. */
  includeAllChildrenGroups: Group[];
  /** Gets or sets {@link Group}(s) that the groups that dashboard/email to be sent to direct users under it. */
  includeDirectChildrenOnlyGroups: Group[];
  /** Gets or sets the individually added {@link User}(s) as the dashboard/email recipients. */
  individualRecipients: User[];
  /** Gets or sets interactive dashboard settings of scheduled report. */
  interactiveSettings: string;
  /** Gets or sets a value indicating whether weather the scheduled report is active or not. */
  isActive: boolean;
  /** Gets or sets the last modified user. */
  lastModifiedUser: User;
  /** Gets or sets the date of the last run of the scheduled report. */
  lastRun: Date;
  /** Gets or sets the last updated time. */
  lastUpdated: Date;
  /** Gets or sets a value to nullify ScopeGroupFilter. */
  nullifyScopeGroupFilter: boolean;
  /** Gets or sets the {@link ReportPeriod} of scheduled report. */
  period: ReportPeriod;
  /** Gets or sets {@link GroupFilter}(s) that define data scope group filter of the report schedule. */
  scopeGroupFilter: GroupFilter;
  /** Gets or sets {@link Group}(s) that define data scope of the report schedule. */
  scopeGroups: Group[];
  /** Gets or sets the {@link ReportTemplate} of scheduled report. */
  template: ReportTemplate;
}
