//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The state that the database is currently operating in. */
export type DatabaseState = "Unknown" | "Inactive" | "Active" | "Deletion";
