//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DVIRDefectSearch } from "./DVIRDefectSearch";
import { UserSearch } from "./UserSearch";

/** The object used to specify the arguments when searching for {@link DefectRemark}(s). */
export interface DefectRemarkSearch extends Search {
  /**
   * Gets or sets search for DefectRemark with this {@link DVIRDefectSearch} Id.
   *  Available DVIRDefectSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  dvirDefectSearch: DVIRDefectSearch;
  /** Gets or sets search for DefectRemark that were recorded at this date or after. */
  fromDate: Date;
  /** Gets or sets search for DefectRemarks with this remark as part of it. */
  remarkSearch: string;
  /** Gets or sets search for DefectRemark that were recorded at this date or before. */
  toDate: Date;
  /**
   * Gets or sets search for DefectRemarks with this {@link UserSearch} Id.
   *  Available UserSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  userSearch: UserSearch;
}
