//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Group } from "./Group";
import { Color } from "../../Drawing/Color";
import { DefectSeverity } from "./DefectSeverity";
import { DefectAssetType } from "./DefectAssetType";

/**
 *  Represents a Defect entity. This defines the one
 *  to one relationship between a {@link DefectSeverity} and
 *  {@link Group}.
 */
export interface Defect extends Group {
  /** Gets or sets the {@link DefectAssetType} of the defect. */
  assetType: DefectAssetType;
  /** Gets or sets the color used to render assets belonging to this defect. */
  color: Color;
  /** Gets or sets the list of Defect groups. */
  groups: Group[];
  /** Gets a value indicating whether this is a list of defects. */
  isDefectList: boolean;
  /** Gets or sets a value indicating whether this defect is hidden in the UI. Used for parts to determine if 'other' should be shown or not. */
  isHidden: boolean;
  /** Gets or sets a value indicating whether this defect must be signed off on. Used for parts to determine if the part must be explicitly marked as having defect(s) or not. */
  isRequired: boolean;
  /** Gets or sets the {@link DefectSeverity} of the Defect. */
  severity: DefectSeverity;
}
