//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The class that contains device share options flags. */
export interface DeviceShareOptions {
  /** Gets or sets a value indicating auto approve switch. */
  autoApprove: boolean;
  /** Gets or sets a value indicating enable gps data switch. */
  enableGps: boolean;
  /** Gets or sets a value indicating enable location data switch. */
  enableLocation: boolean;
  /** Gets or sets a value indicating transfer control switch. */
  transferControl: boolean;
}
