//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The Geotab GO device type enumeration. Geotab has produced various types of tracking devices and this device type enumeration can be used to determine which type of hardware a particular device is. */
export type DeviceType =
  | "None"
  | "OldGeotab"
  | "GO2"
  | "GO3"
  | "GO4"
  | "GO4v3"
  | "GO5"
  | "GO6"
  | "GO7"
  | "GO8"
  | "GO9"
  | "GO9B"
  | "CustomDevice"
  | "GoDriveDevice"
  | "CustomVehicleDevice"
  | "A1"
  | "U1";
