//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { VehicleFeatureCategory } from "./VehicleFeatureCategory";

/** The plan a device is on. */
export interface DeviceFlags {
  /** Gets a list of features currently active on the device. */
  activeFeatures: VehicleFeatureCategory[];
  /**
   * Gets a value indicating whether the device has access to the active tracking
   *  functionality.
   */
  isActiveTrackingAllowed: boolean;
  /** Gets a value indicating whether a {@link Boolean} indicating if the device has access to engine functionality. */
  isEngineAllowed: boolean;
  /** Gets a value indicating whether the device has access to Garmin functionality. */
  isGarminAllowed: boolean;
  /** Gets a value indicating whether the device has access to HOS functionality. */
  isHOSAllowed: boolean;
  /** Gets a value indicating whether the device has access to Iridium functionality. */
  isIridiumAllowed: boolean;
  /** Gets a value indicating whether the device has access to odometer functionality. */
  isOdometerAllowed: boolean;
  /** Gets a value indicating whether the device has access to trip detail functionality. */
  isTripDetailAllowed: boolean;
  /** Gets a value indicating whether the device can be viewed in MyGeotab. */
  isUIAllowed: boolean;
  /** Gets a value indicating whether the device has access to VIN functionality. */
  isVINAllowed: boolean;
  /** Gets the rate plans. Has been replaced by ActiveFeatures. Kept around for legacy serializers. See case 143314. */
  ratePlans: string[];
}
