//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/** The object used to specify the arguments when searching for {@link DeviceLink} record(s). */
export interface DeviceLinkSearch extends Search {
  /**
   * Gets or sets search for DeviceLink that was active at this date or after.
   *  Set to UTC now to search for only currently active DeviceLink.
   */
  activeFrom: Date;
  /** Gets or sets search for DeviceLink that was active at this date or before. */
  activeTo: Date;
  /**
   * Gets or sets destination device search for DeviceLink attached to this {@link DeviceSearch} Id.
   *  Available DeviceSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  destinationDeviceSearch: DeviceSearch;
  /** Gets or sets the maximum row version of the DeviceLink search criteria. */
  maxVersion: number;
  /**
   * Gets or sets source device search for DeviceLink attached to this {@link DeviceSearch} Id.
   *  Available DeviceSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  sourceDeviceSearch: DeviceSearch;
  /** Gets or sets the row version of the DeviceLink search criteria. */
  version: number;
}
