//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/** The object used to specify the arguments when searching for {@link DeviceCommunicationHistory} record(s). */
export interface DeviceCommunicationHistorySearch extends Search {
  /**
   * Gets or sets filter by the {@link DeviceSearch} options.
   *  Providing a device ID will search for any DeviceCommunicationHistory for that Device.
   *  Providing deviceIds will search for any DeviceCommunicationHistory for that Devices.
   *  Providing the Groups will search for DeviceCommunicationHistory for that have Devices in that group.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>DeviceIds</description></item><item><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for device communication history entries that were recorded at this date or after. */
  fromDate: Date;
  /**
   * Gets or sets the maximum version of the
   *  {@link DeviceCommunicationHistory} search criteria.
   */
  maxVersion: number;
  /** Gets or sets search for device communication history entries that were at this date or before. */
  toDate: Date;
  /** Gets or sets the row version of the {@link DeviceCommunicationHistory} search criteria. */
  version: number;
}
