//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The device status level. Used to indicate the "level" of severity for a device's status. */
export type DeviceStatusLevel =
  | "Critical"
  | "Warning"
  | "Good"
  | "Disabled"
  | "Unknown";
