//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { User } from "./User";

/**
 *  Represents a snapshot of discrete HOS availability values for a driver at a specific point in time.
 *
 * @deprecated
 */
export interface DiscreteAvailabilitySnapshot extends EntityWithVersion {
  /** Gets or sets the cycle availability duration. */
  cycle: number;
  /** Gets or sets the cycle driving availability duration. */
  cycleDriving: number;
  /** Gets or sets the cycle rest availability duration. */
  cycleRest: number;
  /** Gets or sets the daily driving availability duration. */
  dailyDriving: number;
  /** Gets or sets the daily duty availability duration. */
  dailyDuty: number;
  /** Gets or sets the daily off-duty availability duration. */
  dailyOff: number;
  /** Gets or sets the daily rest availability duration. */
  dailyRest: number;
  /** Gets or sets the timestamp when this availability was calculated. */
  dateTime: Date;
  /**
   * @inheritdoc
   */
  deletedDateTime: Date;
  /** Gets or sets the driving availability duration. */
  driving: number;
  /** Gets or sets the duty availability duration. */
  duty: number;
  /** Gets or sets a value indicating whether the 16-hour exemption is available. */
  is16HourExemptionAvailable: boolean;
  /** Gets or sets a value indicating whether the adverse driving exemption has been applied. */
  isAdverseDrivingApplied: boolean;
  /** Gets or sets a value indicating whether the adverse driving exemption is available. */
  isAdverseDrivingExemptionAvailable: boolean;
  /** Gets or sets a value indicating whether the exemption reduced rest is available. */
  isExemptionReducedRestAvailable: boolean;
  /** Gets or sets a value indicating whether the off-duty deferral exemption is available. */
  isOffDutyDeferralExemptionAvailable: boolean;
  /** Gets or sets a value indicating whether the railroad exemption is available. */
  isRailroadExemptionAvailable: boolean;
  /** Gets or sets a value indicating whether the workday is being split. */
  isSplittingWorkday: boolean;
  /** Gets or sets the rest availability duration. */
  rest: number;
  /** Gets or sets the {@link User} (driver) for whom this availability was calculated. */
  user: User;
  /** Gets or sets the workday availability duration. */
  workday: number;
}
