//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The current driving state of a vehicle. */
export enum DrivingState {
  /** There is no status */
  None = "None",
  /** The vehicle is driving */
  Driving = "Driving",
  /** The vehicle is idling or driving slowly */
  IdlingOrDrivingSlowly = "IdlingOrDrivingSlowly",
  /** The vehicle is stopped */
  Stopped = "Stopped",
  /** The vehicle is idling */
  Idling = "Idling",
  /** The vehicle is parked */
  Parked = "Parked",
}
