//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { DutyStatusAvailability } from "./DutyStatusAvailability";
import { User } from "./User";
import { DutyStatusViolation } from "./DutyStatusViolation";
import { UserHosRuleSet } from "./UserHosRuleSet";
import { DutyStatusLogType } from "./DutyStatusLogType";

/** Detailed information for Hours of Service regulation for a driver. */
export interface DriverRegulation extends Entity {
  /** Gets or sets the {@link DutyStatusAvailability}. */
  availability: DutyStatusAvailability;
  /** Gets or sets the latest duty status log type {@link DutyStatusLogType} affecting availability or violations. */
  currentDutyStatus: DutyStatusLogType;
  /** Gets or sets the cycle summaries. */
  cycleSummaries: unknown[];
  /** Gets or sets the day summaries. */
  daySummaries: unknown[];
  /** Gets or sets the {@link DriverRegulation.Driver}. */
  driver: User;
  /**
   * Gets or sets the {@link DriverRegulation.EwdAvailability}.
   *
   *
   * @deprecated
   */
  ewdAvailability: unknown[];
  /** Gets or sets when off duty is needed. */
  offDutyNeeded: string;
  /** Gets or sets when rest break is needed. */
  restBreakNeeded: string;
  /** Gets or sets rulesets that cannot be changed currently. */
  rulesetsThatCannotChange: UserHosRuleSet[];
  /** Gets or sets the {@link DutyStatusViolation}. */
  violations: DutyStatusViolation[];
  /** Gets or sets the workday summaries. */
  workdaySummaries: unknown[];
}
