//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";
import { UserSearch } from "./UserSearch";
import { DriverChangeType } from "./DriverChangeType";

/**
 * The object used to specify the arguments when searching for a {@link DriverChange}.
 *  This search defaults to searching {@link DriverChange}(s) by {@link Driver} Id when no {@link DeviceSearch} is provided.
 */
export interface DriverChangeSearch extends Search {
  /**
   * Gets or sets filter by the {@link DeviceSearch} options. Providing a device ID will
   *  search for any DriverChanges that are assigned to that Device.
   *  Providing the Groups will search for DriverChanges for that have Devices in that group.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for DriverChange records at this date or after. */
  fromDate: Date;
  /** Gets or sets a value indicating whether to include the next driver change after the to date or the most recent driver change (if dates are not provided). */
  includeNextChanges: boolean;
  /** Gets or sets a value indicating whether to include the last driver change before the from date or the most recent driver change (if dates are not provided). */
  includeOverlappedChanges: boolean;
  /** Gets or sets maximum version of the search criteria. */
  maxVersion: number;
  /** Gets or sets search for DriverChange records at this date or before. */
  toDate: Date;
  /** Gets or sets a value indicating the {@link DriverChangeType} to search for exclusively. */
  type: DriverChangeType;
  /**
   * Gets or sets search for DriverChanges with this {@link DriverChangeSearch.UserSearch} Id or DriverGroups.
   *  Available UserSearch options are:.
   *  <list><item><description>Id</description></item><item><description>DriverGroups</description></item><item><description>DriverGroupFilterCondition</description></item></list>
   */
  userSearch: UserSearch;
}
