//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Supported Driver Change Types. */
export enum DriverChangeType {
  /** Unknown key type. */
  None = "None",
  /** Driver Key - based Driver. Drivers use this key type to identify themselves. This will typically be used when the driver ID relay is enabled. Makes a {@link Device} continuously associated with a particular {@link Driver} until a different driver ID is assigned to the same device. */
  DriverKey = "DriverKey",
  /** DriverVehicleChange log - based Driver. Auto-generated by the system to support the driver ID relay feature. */
  DriverVehicleChange = "DriverVehicleChange",
  /** User-based Driver that is only active for the duration of a single trip. */
  TripDriver = "TripDriver",
  /** User-based Driver. Makes a {@link Device} continuously associated with particular {@link Driver} until a different driver id is assigned to the same device. First record in a trip overrides any other record encountered during the trip it was added to, except "TripDriver". */
  Driver = "Driver",
  /** System-detected Driver reset (to UnknownDriver). Makes a {@link Device} permanently disassociate from the previous {@link Driver} due to concurrent permanent registration of the same Driver for a different device. */
  ResetDriver = "ResetDriver",
}
