//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { UserSearch } from "./UserSearch";

/**
 *  The object used to specify the arguments when searching for
 *  {@link DutyStatusViolation}(s).
 *  This search has been designed to work efficiently with these combinations of parameters:<list><item><description>UserSearch + FromDate and/or ToDate</description></item></list>
 */
export interface DutyStatusViolationSearch extends Search {
  /** Gets or sets search for duty status violations that were recorded at this date or after. */
  fromDate: Date;
  /** Gets or sets search for an entry based on the specific {@link Id}. */
  id: string;
  /** Gets or sets search for duty status violations that were recorded at this date or before. */
  toDate: Date;
  /**
   * Gets or sets search for duty status violations with this {@link UserSearch}.
   *  Available UserSearch options are:.
   *  <list><item><description>Id</description></item><item><description>CompanyGroups</description></item><item><description>DriverGroups</description></item></list>
   */
  userSearch: UserSearch;
}
