//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Malfunction or Diagnostic type of the {@link DutyStatusLog}. */
export type DutyStatusMalfunctionTypes =
  | "None"
  | "Diagnostic"
  | "Malfunction"
  | "UserClear"
  | "UserDiagnosticClear"
  | "UserMalfunctionClear"
  | "SystemClear"
  | "SystemDiagnosticClear"
  | "SystemClearDriving"
  | "SystemDiagnosticClearDriving"
  | "ManualPosition"
  | "DiagnosticManualPosition"
  | "MalfunctionManualPosition";
