//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 *  The origin of a {@link DutyStatusLog}.
 */
export type DutyStatusOrigin =
  | "Automatic"
  | "Manual"
  | "OtherUser"
  | "Unassigned";
