//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 *  The type of {@link DVIRLog}.
 */
export enum DVIRLogType {
  /** Unknown log type */
  Unknown = "Unknown",
  /** Pre-trip log type */
  PreTrip = "PreTrip",
  /** Post-trip log type */
  PostTrip = "PostTrip",
  /** In-trip log type */
  InTrip = "InTrip",
}
