//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { DefectRemark } from "./DefectRemark";
import { Defect } from "./Defect";
import { User } from "./User";
import { RepairStatusType } from "./RepairStatusType";

/**
 *  A DVIRDefect is a Defect that can be associated with a {@link DVIRLog}.
 *  It contains repair information such as repair {@link DateTime}, repair {@link User , and {@link RepairStatusType}.
 *  DVIRDefect also consists a list of {@link DefectRemark}} which can be used to store additional information for the defect.
 */
export interface DVIRDefect extends Entity {
  /** Gets or sets the {@link DVIRDefect.Defect} which this DVIRDefect belongs to. */
  defect: Defect;
  /** Gets or sets the {@link DefectRemark}s which this DVIRDefect has. */
  defectRemarks: DefectRemark[];
  /** Gets or sets the date and time the DVIRDefect was repaired. */
  repairDateTime: Date;
  /** Gets or sets the {@link RepairStatusType} of this DVIRDefect. */
  repairStatus: RepairStatusType;
  /** Gets or sets the {@link User} who repaired the DVIRDefect. */
  repairUser: User;
}
