//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Aggregated energy data for a vehicle. */
export interface ElectrificationAggregation {
  /** Gets or sets a value indicating whether the vehicle can be replaced with a BEV or not. */
  canUseBev: boolean;
  /** Gets or sets a value indicating whether the vehicle can be replaced with a PHEV or not. */
  canUsePhev: boolean;
  /** Gets or sets the number of days evaluated for the calculation of data. */
  daysEvaluated: number;
  /**
   * Gets or sets the amount of fuel saved if the vehicle was switched to PHEV for this month expressed as a
   *  percentage.
   */
  estimatedPhevGasSavingsPercent: number;
}
