//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { RouteSearch } from "./RouteSearch";

/**
 *  The object used to specify the arguments when searching for
 *  {@link EmployeeRoutePlan}(s).
 *
 * @deprecated
 */
export interface EmployeeRoutePlanSearch extends Search {
  /** Gets or sets search for Employee Route Plan(s) recorded at this date or after. */
  fromDate: Date;
  /**
   * Gets or sets search for Employee Route Plans with this {@link RouteSearch} Id.
   *  Available RouteSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  routeSearch: RouteSearch;
  /** Gets or sets search for Employee Route Plans recorded at this date or before. */
  toDate: Date;
}
