//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { EntityUploadRequestStatus } from "./EntityUploadRequestStatus";
import { EntityUploadRequestAdditionalInfo } from "./EntityUploadRequestAdditionalInfo";

/** Represents a request to upload an entity with versioning information. */
export interface EntityUploadRequest extends Entity {
  /** Gets or sets the {@link EntityUploadRequestAdditionalInfo}. */
  additionalInfo: EntityUploadRequestAdditionalInfo;
  /** Gets or sets the current version of the entity. */
  currentVersion: number;
  /** Gets or sets the name of the entity. */
  entityName: string;
  /** Gets or sets the date from which the entity is being uploaded. */
  fromDate: Date;
  /** Gets or sets the From version from which the entity is being uploaded. */
  fromVersion: number;
  /** Gets or sets the date and time of the request. */
  requestedDateTime: Date;
  /** Gets or sets the status of the entity upload request. */
  status: EntityUploadRequestStatus;
  /** Gets or sets the date to which the entity is being uploaded. */
  toDate: Date;
  /** Gets or sets the To version to which the entity is being uploaded. */
  toVersion: number;
}
