//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The enum representing all the entity upload request statuses. */
export type EntityUploadRequestStatus =
  | "Initialized"
  | "Processing"
  | "Successful"
  | "Error";
