//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntity } from "./NameEntity";
import { EventType } from "./EventType";
import { Group } from "./Group";
import { NotificationBinaryFile } from "./NotificationBinaryFile";

/** The rule describing an event. */
export interface EventRule extends NameEntity {
  /** Gets or sets free text field where any user information can be stored and referenced for this entity. */
  comment: string;
  /** Gets or sets the {@link EventRule.DateTime} of the event. */
  dateTime: Date;
  /** Gets or sets the days. */
  days: number;
  /** Gets or sets the engine hours. */
  engineHours: string;
  /** Gets or sets the event date. */
  eventDate: Date;
  /** Gets or sets the type of the event. */
  eventType: EventType;
  /** Gets or sets a list of {@link Group}(s) assigned to the event rule. */
  groups: Group[];
  /** Gets or sets gets the unique identifier for this entity. See {@link Id}. */
  id: string;
  /** Gets or sets the kilometers. */
  kilometers: number;
  /** Gets or sets the months. */
  months: number;
  /** Gets or sets the name of this entity that uniquely identifies it and is used when displaying this entity. */
  name: string;
  /** Gets or sets the notification template {@link NotificationBinaryFile} for the event. */
  notificationTemplate: NotificationBinaryFile;
}
