//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { MediaContentType } from "./MediaContentType";
import { MediaLinkStatus } from "./MediaLinkStatus";
import { ExceptionEvent } from "./Exceptions/ExceptionEvent";

/** The link between a media request and the associated exception event. */
export interface ExceptionEventMediaLink extends EntityWithVersion {
  /** Gets or sets the associated {@link ExceptionEventMediaLink.ExceptionEvent} that this {@link ExceptionEventMediaLink} is based on. */
  exceptionEvent: ExceptionEvent;
  /** Gets or sets the exception event id. */
  exceptionEventId: string;
  /** Gets or sets the media request id. */
  mediaRequestId: string;
  /** Gets or sets the status of the {@link ExceptionEventMediaLink} . */
  mediaStatus: MediaLinkStatus;
  /** Gets or sets the {@link MediaContentType}. */
  mediaType: MediaContentType;
  /** Gets or sets the start time. */
  startTime: Date;
}
