//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { MediaContentType } from "./MediaContentType";

/**
 *  The object used to specify the arguments when searching for {@link ExceptionEventMediaLink}.
 */
export interface ExceptionEventMediaLinkSearch extends Search {
  /** Gets or sets the exception event id, which is used to search for a specific matching exception event id. */
  exceptionEventId: string;
  /** Gets or sets the exception event ids, which matches based on the exception ids in the list. */
  exceptionEventIds: string[];
  /** Gets or sets the max row version of the {@link ExceptionEventMediaLink} search criteria. */
  maxVersion: number;
  /** Gets or sets the media request id, which is used to search for a specific matching media request id. */
  mediaRequestId: string;
  /** Gets or sets the media request ids, which matches based on the media request ids in the list. */
  mediaRequestIds: string[];
  /** Gets or sets the media statuses, which is used to search for specific media statuses. */
  mediaStatuses: string[];
  /** Gets or sets the media type, which is used to search for specific types of media only (i.e. only Video, only Snapshot). */
  mediaType: MediaContentType;
  /** Gets or sets the property indicating whether to populate the {@link ExceptionEvent} associated with the {@link ExceptionEventMediaLink}. */
  populateExceptionEvent: boolean;
  /** Gets or sets the row version of the {@link ExceptionEventMediaLink} search criteria. */
  version: number;
}
