//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Device } from "./Device";
import { Source } from "./Engine/Source";
import { Controller } from "./Engine/Controller";
import { Diagnostic } from "./Engine/Diagnostic";
import { FailureMode } from "./Engine/FailureMode";

/** A class that holds the cycles for a fault. */
export interface FaultCycle {
  /** Gets or sets the count of all Active cycles inside the cycle. */
  activeEventCount: number;
  /** Gets or sets the duration of break down in seconds. */
  breakdownDuration: number;
  /** Gets or sets the posibility of break down, percentage. */
  breakdownRisk: number;
  /** Gets or sets the count of all Confirmed cycles inside the cycle. */
  confirmedEventCount: number;
  /** Gets or sets the Controller. */
  controller: Controller;
  /** Gets or sets the last DateTime of the Cycle. */
  cycleEnd: Date;
  /**
   * Gets or sets the indication whether the cycle is considered as persistent.
   *  If the cycle is persistent the last seen cycle is not yet set as the cycle end and can still update.
   */
  cycleOnGoing: boolean;
  /** Gets or sets the first DateTime of the Cycle. */
  cycleStart: Date;
  /** Gets or sets the date and time when the fault cycle record was first inserted into the database. */
  dateInserted: Date;
  /** Gets or sets the {@link Device}. */
  device: Device;
  /** Gets or sets the Diagnostic. */
  diagnostic: Diagnostic;
  /** Gets or sets the FailureMode. */
  failureMode: FailureMode;
  /** Gets or sets the count of all Pending cycles inside the cycle. */
  pendingEventCount: number;
  /** Gets or sets the Source. */
  source: Source;
  /** Gets or sets the distance driven with cycle in active state. */
  summaryCycleDistanceActive: number;
  /** Gets or sets the distance driven with cycle in confirmed state. */
  summaryCycleDistanceConfirmed: number;
  /** Gets or sets the distance driven with cycle in pending state. */
  summaryCycleDistancePending: number;
  /** Gets or sets the duration where cycle is in the active state. */
  summaryCycleDurationActive: number;
  /** Gets or sets the duration where cycle is in the confirmed state. */
  summaryCycleDurationConfirmed: number;
  /** Gets or sets the duration where cycle is in the pending state. */
  summaryCycleDurationPending: number;
  /** Gets or sets the DateTime of the first Active cycle. */
  summaryCycleFirstActive: Date;
  /** Gets or sets the DateTime of the first Confirmed cycle. */
  summaryCycleFirstConfirmed: Date;
  /** Gets or sets the datetime of the first pending. */
  summaryCycleFirstPending: Date;
  /** Gets or sets the dateTime of the last Active cycle. */
  summaryCycleLastActive: Date;
  /** Gets or sets the DateTime of the last Confirmed cycle. */
  summaryCycleLastConfirmed: Date;
  /** Gets or sets the dateTime of the last pending cycle. */
  summaryCycleLastPending: Date;
  /** Gets or sets the Odometer value of the first Active cycle. */
  summaryCycleOdometerFirstActive: number;
  /** Gets or sets the Odometer value of the first Confirmed cycle. */
  summaryCycleOdometerFirstConfirmed: number;
  /** Gets or sets the odometer value of the first pending cycle. */
  summaryCycleOdometerFirstPending: number;
  /** Gets or sets the Odometer value of the last Active cycle. */
  summaryCycleOdometerLastActive: number;
  /** Gets or sets the Odometer value of the last Confirmed cycle. */
  summaryCycleOdometerLastConfirmed: number;
  /** Gets or sets the odometer value of the last Pending cycle. */
  summaryCycleOdometerLastPending: number;
  /** Gets or sets the indication wheter a cycle is valid or invalid due to more recent cycle. */
  validCycle: boolean;
}
