//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";
import { FeedbackType } from "./FeedbackType";
import { FeedbackStatus } from "./FeedbackStatus";

/**
 *  The object used to specify the
 *  arguments when searching for a {@link Feedback}.
 *
 * @deprecated
 */
export interface FeedbackSearch extends Search {
  /**
   * Gets or sets filter by the {@link DeviceSearch} options. Providing a device ID will
   *  search for any Feedback that are assigned to that Device.
   *  Providing the Groups will search for Feedback for that have Devices in that group.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for {@link Feedback}s of the given {@link FeedbackSearch.FeedbackStatus}. */
  feedbackStatus: FeedbackStatus;
  /** Gets or sets search for {@link Feedback}s for a Feedback Target Id/&gt;. */
  feedbackTargetId: string;
  /** Gets or sets search for {@link Feedback}s for a list of Feedback Target Ids. */
  feedbackTargetIds: string[];
  /** Gets or sets search for {@link Feedback}s of the given {@link FeedbackSearch.FeedbackType}. */
  feedbackType: FeedbackType;
  /** Gets or sets search for {@link Feedback}s of the given {@link FeedbackSearch.FeedbackType}. */
  feedbackTypes: FeedbackType[];
  /** Gets or sets search for {@link Feedback}s recorded at this date or after. */
  submittedOn: Date;
}
