//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The type of firmware. */
export enum FirmwareType {
  /** The firmware is used for Ethernet Radio Downloaders */
  EthernetRadioDownloader = "EthernetRadioDownloader",
  /** The firmware is used for USB Radio Downloaders */
  UsbRadioDownloader = "UsbRadioDownloader",
}
