//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Fuel tax road type. */
export enum FuelTaxRoadType {
  /** Unknown road type. */
  Unknown = "Unknown",
  /** Offroad road type. */
  OffRoad = "OffRoad",
  /** Public road type. */
  Public = "Public",
  /** Private road type. */
  Private = "Private",
  /** Toll road type. */
  Toll = "Toll",
  /** Rail road type. */
  Rail = "Rail",
}
