//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Defines the different types of {@link FuelAndEnergySetting}(s). */
export type FuelAndEnergySettingType =
  | "SustainabilityCenter"
  | "FuelTransactions";
