//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The language used by a GoTalk attached to a. {@link GoDevice} */
export type GoTalkLanguage =
  | "English"
  | "French"
  | "Spanish"
  | "German"
  | "Italian";
