//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { AddInSearch } from "./AddIns/AddInSearch";
import { GroupSearch } from "./GroupSearch";

/** The object used to specify the arguments when searching for GroupAddIn/&gt;. */
export interface GroupAddInSearch extends Search {
  /** Gets or sets the filter by the {@link GroupAddInSearch.AddInSearch} options. */
  addInSearch: AddInSearch;
  /** Gets or sets the filter by the {@link GroupAddInSearch.GroupSearch} options. */
  groupSearch: GroupSearch;
  /** Gets or sets a value indicating whether to filter by soft-deleted status. */
  isSoftDeleted: boolean;
}
