//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntity } from "./NameEntity";
import { GroupFilterCondition } from "./GroupFilterCondition";

/**
 * GroupFilter can be used to specify the type of operator (AND and OR) to use when searching for entities.
 *  The GroupsFilter option allows you to use more than one type of operator when searching for a specific group.
 */
export interface GroupFilter extends NameEntity {
  /** Gets or sets the comments */
  comments: string;
  /** Gets or sets the GroupFilter */
  groupFilterCondition: GroupFilterCondition;
}
