//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";

/** The object used to specify the arguments when searching for a {@link Group}. */
export interface GroupSearch extends Search {
  /** Gets or sets include Groups from all trees, for example "Security Groups" and "Private User Groups". The"Company Group" tree is included by default. */
  includeAllTrees: boolean;
  /** Gets or sets gets maximum Id of the search criteria. */
  maxId: string;
  /** Gets or sets search for Groups with this Name. Wildcard can be used by prepending/appending "%" to string. Example "%name%". */
  name: string;
  /** Gets or sets search for Groups with this Reference. Wildcard can be used by prepending/appending "%" to string. Example "%reference%". */
  reference: string;
}
