//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Represents a {@link Group} linked to an {@link AddIn}. This defines the many to many relationship between an {@link AddIn} and {@link Group}. */
export interface GroupAddIn {
  /** Gets or sets a value indicating whether this GroupAddIn is soft-deleted. */
  softDeleted: boolean;
}
