//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 * The configuration parameters of
 *  {@link HosRulesetConfig}.
 */
export interface HosRulesetConfigParameters {
  /** Gets or sets a value indicating whether adverse driving extend workday. */
  adverseDoesNotExtendWorkday: boolean;
  /** Gets or sets the big day bonus. */
  bigDayBonus: number;
  /** Gets or sets a value indicating whether a big day ignores a cycle reset. */
  bigDayIgnoresCycleReset: boolean;
  /** Gets or sets the maximum big day exemptions that can be applied per cycle. */
  bigDayMaxPerCycle: number;
  /** Gets or sets a value indicating whether a ruleset can have a custom start of day set. */
  customStartOfDay: boolean;
  /** Gets or sets the {@link HosRulesetCycleConfig}. */
  cycle: unknown;
  /** Gets or sets the {@link HosRulesetDailyConfig}. */
  daily: unknown;
  /** Gets or sets a value indicating whether exempt or not. */
  exempt: boolean;
  /** Gets or sets a value indicating whether labs are enabled or not. */
  labsEnabled: boolean;
  /** Gets or sets the days of log retention. */
  logRetentionDays: number;
  /** Gets or sets a value indicating whether there is an oil well exemption or not. */
  oilwell: boolean;
  /** Gets or sets a value indicating whether there is an railroad exemption or not. */
  railroadExempt: boolean;
  /** Gets or sets a value indicating whether a reset previous cycle is true. */
  resetPreviousCycle: boolean;
  /** Gets or sets the {@link HosRulesetRestConfig}. */
  rest: unknown;
  /** Gets or sets the split type. */
  splitType: string;
  /** Gets or sets the {@link HosRulesetWorkdayConfig}. */
  workday: unknown;
  /** Gets or sets the {@link EwdWorkRestConfig} for WWD rulesets. */
  workRestConfig: unknown[];
}
