//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";

/** Hos Ruleset. */
export interface HosRuleSet2 extends Entity {}
