//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntity } from "./NameEntity";
import { HosRulesetConfigParameters } from "./HosRulesetConfigParameters";

/**
 * The object used to specify the arguments when retrieving
 *  {@link HosRulesetConfig}(s).
 */
export interface HosRulesetConfig extends NameEntity {
  /** Gets the {@link HosRulesetConfigParameters}. */
  config: HosRulesetConfigParameters;
  /** Gets the description of the ruleset. */
  description: string;
}
