//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { UserSearch } from "./UserSearch";
import { DutyStatusLogSearch } from "./DutyStatusLogSearch";
import { UserHosRuleSetSearch } from "./UserHosRuleSetSearch";

/** The object used to specify the arguments when searching for {@link HosStatusInfo}(s). */
export interface HosStatusInfoSearch extends Search {
  /**
   * Gets or sets search for {@link HosStatusInfo} with the provided {@link HosStatusInfoSearch.DutyStatusLogSearch}.
   *  Available DutyStatusLogSearch options are:
   *  <list><item><description>Statuses</description></item></list>
   */
  dutyStatusLogSearch: DutyStatusLogSearch;
  /**
   * Gets or sets the {@link HosStatusInfoSearch.Id}.
   *  This is not supported on {@link HosStatusInfoSearch}.
   */
  id: string;
  /**
   * Gets or sets search for {@link HosStatusInfo} with the provided {@link HosStatusInfoSearch.UserHosRuleSetSearch}.
   *  Available UserHosRuleSetSearch options are:
   *  <list><item><description>RuleSets</description></item></list>
   */
  userHosRuleSetSearch: UserHosRuleSetSearch;
  /**
   * Gets or sets search for {@link HosStatusInfo} objects with this {@link HosStatusInfoSearch.UserSearch}.
   *  Available UserSearch options are:
   *  <list><item><description>Id</description></item><item><description>CompanyGroups</description></item><item><description>Keywords</description></item></list>
   */
  userSearch: UserSearch;
}
