//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { User } from "./User";
import { DutyStatusLog } from "./DutyStatusLog";
import { UserHosRuleSet } from "./UserHosRuleSet";

/** Represents the current HOS state of a driver by providing information such as the driver's current {@link HosStatusInfo.DutyStatusLog} and current {@link HosStatusInfo.UserHosRuleSet}. */
export interface HosStatusInfo extends EntityWithVersion {
  /** Gets or sets the {@link HosStatusInfo.Driver}. */
  driver: User;
  /** Gets or sets the current {@link HosStatusInfo.DutyStatusLog}. */
  dutyStatusLog: DutyStatusLog;
  /** Gets or sets the current {@link HosStatusInfo.UserHosRuleSet}. */
  userHosRuleSet: UserHosRuleSet;
}
