//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";

/** Metadata for a user on IAM. */
export interface IAMMetadata extends Entity {
  /** Gets or sets the name of the connection the user belongs to on IAM. */
  connectionName: string;
  /** Gets or sets a value indicating whether the user is verified on IAM, if [true] the user is verified on IAM, otherwise [false]. Default [false]. */
  isIAMVerified: boolean;
  /** Gets or sets a value indicating whether the user has received a welcome email. Default [true]. */
  isWelcomeEmailSent: boolean;
  /** Gets or sets the user's Id on IAM. */
  userId: string;
}
