//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";
import { UserSearch } from "./UserSearch";

/** The object used to specify the arguments when searching for {@link InspectionLog}(s). */
export interface InspectionLogSearch extends Search {
  /** Gets or sets search for InspectionLogs for this {@link DeviceSearch} Id. */
  assetSearch: DeviceSearch;
  /** Gets or sets search for InspectionLogs created by this {@link UserSearch} Id. */
  createdBySearch: UserSearch;
  /** Gets or sets search for InspectionLogs that were created at this date or after. */
  fromDate: Date;
  /**
   * Gets or sets search for InspectionLogs matching any of the specified {@link InspectionLogStatus} values.
   *  Valid "LogStatus" values are:
   *  <list><item><description>Unknown</description></item><item><description>Draft</description></item><item><description>Complete</description></item><item><description>Submitted</description></item><item><description>InReview</description></item><item><description>Reviewed</description></item></list>
   */
  logStatuses: string[];
  /** Gets or sets the maximum version. */
  maxVersion: number;
  /** Gets or sets the minimum version. */
  minVersion: number;
  /** Gets or sets search for InspectionLogs that were created at this date or before. */
  toDate: Date;
}
