//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { InspectionLogSearch } from "./InspectionLogSearch";
import { GroupSearch } from "./GroupSearch";
import { UserSearch } from "./UserSearch";

/** The object used to specify the arguments when searching for {@link InspectedItem}(s). */
export interface InspectedItemSearch extends Search {
  /** Gets or sets search for InspectedItems that were repaired at this date or after. */
  fromDate: Date;
  /** Gets or sets search for InspectedItems for this {@link GroupSearch} Id. */
  inspectionItemSearch: GroupSearch;
  /** Gets or sets search for InspectedItems for this {@link InspectedItemSearch.InspectionLogSearch} Id. */
  inspectionLogSearch: InspectionLogSearch;
  /** Gets or sets search for InspectedItems repaired by this {@link UserSearch} Id. */
  repairBySearch: UserSearch;
  /** Gets or sets search for InspectedItems that were repaired at this date or before. */
  toDate: Date;
}
