//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { Group } from "./Group";
import { Device } from "./Device";
import { InspectionLogType } from "./InspectionLogType";
import { InspectionLogStatus } from "./InspectionLogStatus";
import { AddressLookupData } from "./AddressLookupData";
import { User } from "./User";
import { InspectedItem } from "./InspectedItem";

/**
 *  An InspectionLog is an asset inspection report which is prepared by a user
 *  regarding the condition of an asset. The log contains inspected items
 *  with their status, severity, and optional repair information.
 *
 * @deprecated
 */
export interface InspectionLog extends EntityWithVersion {
  /** Gets or sets the asset (Device) being inspected. */
  asset: Device;
  /** Gets or sets comments added by the user that inspected the asset. */
  comments: string;
  /** Gets or sets the user that created the inspection. */
  createdBy: User;
  /** Gets or sets the created date and time of the inspection. */
  createdDateTime: Date;
  /** Gets or sets the duration it takes to complete this inspection. */
  duration: string;
  /** Gets or sets the list of {@link InspectedItem}(s) for this log. */
  inspectedItems: InspectedItem[];
  /** Gets or sets the inspection template or defect list used when inspecting this asset. */
  inspectionTemplate: Group;
  /** Gets or sets the user that last edited the inspection. */
  lastEditedBy: User;
  /** Gets or sets the last edited date and time of the inspection. */
  lastEditedDateTime: Date;
  /** Gets or sets an object with the location information of the inspection. */
  location: AddressLookupData;
  /** Gets or sets the status of inspection. */
  logStatus: InspectionLogStatus;
  /** Gets or sets the type of inspection. */
  logType: InspectionLogType;
  /** Gets or sets the user that reviewed the inspection. */
  reviewedBy: User;
  /** Gets or sets the reviewed date and time of the inspection. */
  reviewedDateTime: Date;
  /** Gets or sets the user that submitted the inspection. */
  submittedBy: User;
  /** Gets or sets the submitted date and time of the inspection. */
  submittedDateTime: Date;
}
