//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** An enum representing invalid user exception types. */
export type InvalidUserType =
  | "Default"
  | "SessionExpired"
  | "UserLockout"
  | "SessionInvalid";
