//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { MediaFile } from "./Files/MediaFile";

/** Represents an uploaded {@link MediaFile} associated with an {@link Investigation}. */
export interface InvestigationAttachment extends Entity {
  /** Gets or sets the ID of the {@link Investigation} that this attachment belongs to. */
  investigationId: string;
  /** Gets or sets the {@link MediaFile} attachment associated with the {@link Investigation}. */
  mediaFile: MediaFile;
  /** Gets or sets the ID of the {@link User} who uploaded the file to the investigation. */
  uploadedById: string;
  /** Gets or sets the timestamp when the file was uploaded. */
  uploadedDate: Date;
}
