//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 *  Supported Legacy Key Types.
 *
 * @deprecated
 */
export type KeyType =
  | "Unknown"
  | "DriverId"
  | "DriverIdAndData"
  | "AccidentData"
  | "LoggingParameters"
  | "GoFirmware"
  | "ToggleDebug"
  | "ResetPointers"
  | "ResetProductId"
  | "LatestTripData"
  | "ToggleRFPing"
  | "GSMParameters"
  | "ToggleJ1708Ignition"
  | "Go3Firmware"
  | "WifiParameters"
  | "WiFiSecurity"
  | "Go5Firmware"
  | "WifiLive"
  | "DevicePowerUpReset"
  | "IgnitionTimeout"
  | "NFCDriverId"
  | "NFCCdmaReset"
  | "NFCDebugMode"
  | "NFCPassengerId"
  | "GenericNFCDriverId"
  | "CustomNFCDriverId"
  | "TachographDriverId"
  | "TachographCoDriverId"
  | "CustomDriverId";
