//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Zone } from "./Zone";
import { Device } from "./Device";

/**
 * Couples a {@link LogRecord} and a
 *  {@link Zone} objects with a distance between them in kilometers.
 */
export interface LogRecordZoneDistance extends Entity {
  /** Gets or sets the date. */
  dateTime: Date;
  /** Gets or sets the {@link Device}. */
  device: Device;
  /** Gets or sets nullable {@link Single} Distance. */
  distance: number;
  /** Gets or sets {@link Zone}. */
  zone: Zone;
}
