//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";
import { ZoneSearch } from "./ZoneSearch";

/**
 *  The object used to specify the arguments when searching for
 *  {@link LogRecord} from GPSZoneDistance page(s).
 */
export interface LogRecordZoneDistanceSearch extends Search {
  /**
   * Gets or sets search for {@link LogRecordZoneDistance}s that were created for
   *  {@link DeviceSearch}(s).
   *  Available DeviceSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /**
   * Gets or sets search for {@link LogRecordZoneDistance}s that were recorded at this
   *  date or after.
   */
  fromDate: Date;
  /**
   * Gets or sets search for {@link LogRecordZoneDistance}s that were recorded at this
   *  date or before.
   */
  toDate: Date;
  /**
   * Gets or sets search for {@link LogRecordZoneDistance}s that were created for
   *  {@link ZoneSearch}(s).
   *  Available ZoneSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  zoneSearch: ZoneSearch;
}
