//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Device } from "./Device";
import { LogRecord } from "./LogRecord";

/**
 *  This stores unique geohash based on {@link LogRecordGeohash.LogRecord} for a {@link LogRecordGeohash.LogRecord}.
 *
 * @deprecated
 */
export interface LogRecordGeohash extends Entity {
  /** Gets or sets the associated Log Record date time. */
  dateTime: Date;
  /** Gets or sets the {@link Device} associated with the {@link LogRecordGeohash}. */
  device: Device;
  /** Gets or sets geohash of precision 6 based on latitude and longitude of {@link LogRecordGeohash.LogRecord}. */
  geohash: string;
  /** Gets or sets the {@link LogRecordGeohash.LogRecord}. */
  logRecord: LogRecord;
}
