//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Device } from "./Device";
import { MaintenanceNotificationRule } from "./MaintenanceNotificationRule";
import { NotificationMaintenanceReminderData } from "./NotificationMaintenanceReminderData";

/**
 *  An upcoming event related to ab {@link EventOccurrence}.
 *
 * @deprecated
 */
export interface MaintenanceNotificationState extends Entity {
  /** Gets or sets the notification data attached to this state */
  data: NotificationMaintenanceReminderData;
  /** Gets or sets the date on which the notification was last issued. */
  dateNotified: Date;
  /** Gets or sets the due days at the time the notification was last issued. */
  daysDue: string;
  /**
   * @inheritdoc
   */
  device: Device;
  /** Gets or sets the due engine hours at the time the notification was last issued. */
  engineHoursDue: string;
  /** Gets or sets the associated MaintenanceNotificaitonRule {@link MaintenanceNotificationRule}. */
  notificationRule: MaintenanceNotificationRule;
  /** Gets or sets the due kilometers at the time the notification was last issued. */
  odometerDue: number;
}
