//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Recipient } from "./Recipient";
import { EventRule } from "./EventRule";

/**
 *  An upcoming event related to ab {@link EventOccurrence}.
 *
 * @deprecated
 */
export interface MaintenanceNotificationRule extends Entity {
  /** Gets or sets the number of days before the maintenance rule becomes overdue to trigger the notification */
  daysDueTrigger: string;
  /** Gets or sets the amount of engine hours before the maintenance rule becomes overdue to trigger the notification */
  engineHoursTrigger: string;
  /** Gets or sets the maintenance event rule {@link MaintenanceNotificationRule.EventRule} for this notification rule. */
  eventRule: EventRule;
  /** Gets or sets the number of kilometers before the maintenance rule becomes overdue to trigger the notification */
  odometerTrigger: number;
  /** Gets or sets the recipient {@link MaintenanceNotificationRule.Recipient} of the notification. */
  recipient: Recipient;
}
