//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";

/** An {@link Entity} that has a name field. */
export interface NameEntity extends Entity {
  /** Gets or sets the name of this entity that uniquely identifies it and is used when displaying this entity. */
  name: string;
}
