//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NotificationData } from "./NotificationData";
import { EventRule } from "./EventRule";
import { NotificationType } from "./NotificationType";
import { Device } from "./Device";

/** The notification data pertaining to Maintenance Reminders. */
export interface NotificationMaintenanceReminderData extends NotificationData {
  /** Gets or sets the device serial nubmer for this notification. */
  device: Device;
  /** Gets or sets the maintenance reminder that holds the data for this notification. */
  eventRule: EventRule;
  /** Gets or sets the information for the notification maintenance reminder data. */
  info: string;
  /** Gets or sets the event rule that holds the data for this notification. */
  remainingDays: string;
  /** Gets or sets the event rule that holds the data for this notification. */
  remainingDistance: number;
  /** Gets or sets the event rule that holds the data for this notification. */
  remainingEngineHours: string;
  /** Gets or sets the {@link NotificationType} of the notification. */
  type: NotificationType;
}
