//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The type of the data stored in NotificationBinary. */
export type NotificationBinaryFileType =
  | "None"
  | "AudioAlarmFile"
  | "EmailTemplate"
  | "WebRequestTemplate"
  | "TextTemplate";
