//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The type of {@link Notification}. */
export enum NotificationType {
  /** Notification is info or status data */
  Info = "Info",
  /**
   * Notification is an application exception (server and client errors) that are due to factors outside of user control.
   *
   * @remarks NotificationApplicationExceptionData is being deprecated, send errors directly to FogBugz instead.
   */
  ApplicationException = "ApplicationException",
  /** Notification is due to an exception rule being triggered */
  Exception = "Exception",
  /** Notification is System News */
  News = "News",
  /** Notification will be processed and have it's Info updated. */
  ExceptionToBeProcessed = "ExceptionToBeProcessed",
  /** Notification is an application exception (server and/or client errors) that are due to user inputs/actions that the user can fix. */
  ApplicationExceptionForUsers = "ApplicationExceptionForUsers",
  /** Notification is user account settings changed. */
  MessageForUser = "MessageForUser",
  /**
   * Notification that a user was modified (created, removed, modified, etc.) for administrators (SystemNotice subscribers) with appropriate permissions.
   *
   * @remarks Related: {@link NotificationUserModifiedData}, {@link UserModification}, {@link UserModifiedInfo}, {@link UserModifiedValueInfo}.
   */
  UserModified = "UserModified",
  /**
   * Notification for administrators (SystemNotice subscribers) that are due to user inputs/actions.
   *
   * @remarks Related: {@link NotificationForAdminUsersData}.
   */
  ApplicationNotificationForAdmins = "ApplicationNotificationForAdmins",
  /**
   * Notification for maintenance reminders.
   *
   * @remarks Related: {@link NotificationMaintenanceReminderData}.
   */
  MaintenanceNotification = "MaintenanceNotification",
}
