//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The type of {@link Notification}. */
export type NotificationType =
  | "Info"
  | "ApplicationException"
  | "Exception"
  | "News"
  | "ExceptionToBeProcessed"
  | "ApplicationExceptionForUsers"
  | "MessageForUser"
  | "UserModified"
  | "ApplicationNotificationForAdmins"
  | "MaintenanceNotification"
  | "DeviceShareNotification"
  | "Report";
