//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NotificationData } from "./NotificationData";
import { UserModification } from "./UserModification";

/**
 * A class for notifying of changes to a {@link User} by an administrator {@link User}. Provides information
 *  about who was changed, who did the changes, what type of changes happened, and any values that were changed if applicable.
 *
 * @remarks Matching {@link NotificationType} is {@link NotificationType.UserModified}.
 *  Notifications of this type are only delivered to SystemNotice subscribers who have valid Group scope and {@link SecurityIdentifier}.
 */
export interface NotificationUserModifiedData extends NotificationData {
  /** Gets the type of {@link UserModification} that occurred. */
  modificationAction: UserModification;
  /**
   * Gets additional info about the {@link NotificationUserModifiedData.ModificationAction} stored in a data class.
   *
   * @remarks This info is JSON-serialized and stored in the "sInfo" column of the NotificationData table.
   */
  userModifiedInfo: unknown;
}
