//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Defines options for a posted road speed request. */
export type PostedRoadSpeedOptions =
  | "None"
  | "NoEstimates"
  | "NoCommunity"
  | "NoCommercial";
