//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { SupportedPropertyType } from "./SupportedPropertyType";
import { PropertySet } from "./PropertySet";

/** The custom property of an entity that is customizable. */
export interface Property extends EntityWithVersion {
  /** Gets or sets the External Reference of the Property. */
  externalReference: string;
  /** Gets or sets a value indicating whether the Property needs to be populated or not before the entity can be saved. */
  isRequired: boolean;
  /** Gets or sets a value indicating whether the Property is visible or not to the UI. */
  isVisible: boolean;
  /** Gets or sets the maximum length of the Property. */
  maxLength: number;
  /** Gets or sets the minimum length of the Property. */
  minLength: number;
  /** Gets or sets the Name of the Property. */
  name: string;
  /** Gets or sets the {@link Property.PropertySet} that this Property belongs to. */
  propertySet: PropertySet;
  /** Gets or sets the support type of the Property. */
  propertyType: SupportedPropertyType;
}
