//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { Property } from "./Property";
import { Group } from "./Group";

/** The property set that groups {@link Property} together based on a grouping structure. */
export interface PropertySet extends EntityWithVersion {
  /** Gets or sets the External Reference of the PropertySet. */
  externalReference: string;
  /** Gets or sets the {@link Group}s of the PropertySet. */
  groups: Group[];
  /** Gets or sets the Name of the PropertySet. */
  name: string;
  /** Gets or sets the Properties of the PropertySet. */
  properties: Property[];
}
