//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Device } from "./Device";

/** The distance a BEV or PHEV can travel on a full charge. The range estimate is based on historical energy consumption, distance traveled, and battery capacity. */
export interface RangeEstimate {
  /** Gets or sets the date and time (UTC, ISO 8601 format) when the {@link RangeEstimate} was calculated. */
  detectionDate: Date;
  /** Gets or sets the {@link Device} associated with the {@link RangeEstimate}. */
  device: Device;
  /**
   * Gets or sets the lower bound range estimate (for 90% confidence interval), measured in kilometers.
   *  <para />
   *  This means there is a 90% probability that the vehicle’s range is between RangeEstimateLowerBoundKm and RangeEstimateUpperBoundKm.
   */
  rangeEstimateLowerBoundKm: number;
  /** Gets or sets the mean range estimate, measured in kilometers. */
  rangeEstimateMeanKm: number;
  /**
   * Gets or sets the upper bound range estimate (for 90% confidence interval), measured in kilometers.
   *  <para />
   *  This means that there is a 90% probability that the vehicle’s range is between RangeEstimateLowerBoundKm and RangeEstimateUpperBoundKm.
   */
  rangeEstimateUpperBoundKm: number;
  /**
   * Gets or sets the estimation method used to calculate the range estimates.
   *  <para />
   *  If the method is BatteryEstimation, the calculation is based on the energy readings coming in and out of the battery.
   *  If the method is SoCEstimation, the calculation is based on the detected state-of-charge deltas at the beginning and end of trips.
   */
  rangeEstimationMethod: string;
  /** Gets or sets the vehicle identification number (VIN). Must be 17 characters. */
  vin: string;
}
