//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The type of notification message that is generated for a {@link Recipient}. */
export type RecipientType =
  | "LogOnly"
  | "Email"
  | "LogPopup"
  | "LogUrgentPopup"
  | "WebService"
  | "TextMessage"
  | "ChangeStatus"
  | "BeepThreeTimesRapidly"
  | "BeepThreeTimes"
  | "BeepTenTimesRapidly"
  | "LogPopupInfo"
  | "WebRequest"
  | "AssignToGroup"
  | "TextToSpeech"
  | "LogNewsPopup"
  | "BeepThreeTimesRapidlyAllowDelay"
  | "BeepThreeTimesAllowDelay"
  | "BeepTenTimesRapidlyAllowDelay"
  | "TextToSpeechAllowDelay"
  | "TripTypeChange"
  | "EmailToGroup"
  | "HosEnabled"
  | "HosDisabled"
  | "RestrictedDataMode"
  | "ExpireShareableLink"
  | "DeviceShareFailure"
  | "MediaServiceTrigger"
  | "SmsToUser"
  | "EmailToHierarchy"
  | "PushNotification"
  | "CreateWorkRequest"
  | "WhatsAppToUser";
