//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { DateRange } from "./DateRange";

/** Stores the binary data for a generate excel report. */
export interface ReportStorage extends EntityWithVersion {
  /** Gets or sets the excel binary data. */
  binaryData: number[];
  /** Gets or sets a {@link DateTime} of when the report was generated. */
  creationDate: Date;
  /** Gets or sets the start of the reports date range. */
  reportDateRange: DateRange;
  /** Gets or sets the name of the report. */
  reportName: string;
  /** Gets or sets the type of the report. */
  reportType: string;
}
