//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Report template type for {@link ReportTemplate}. */
export type ReportTemplateType =
  | "Custom"
  | "Report"
  | "Advanced"
  | "Dashboard"
  | "Preloaded";
