//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Report template type for {@link ReportTemplate}. */
export enum ReportTemplateType {
  /** Uploaded user reports */
  Custom = "Custom",
  /** Exportable report view with simplified columns */
  Report = "Report",
  /** Exportable report views with all columns */
  Advanced = "Advanced",
  /** Default dashboard */
  Dashboard = "Dashboard",
  /** Used for other preloaded templates */
  Preloaded = "Preloaded",
}
