//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";

/**
 *  The object used to specify the arguments when searching for
 *  {@link ReportTag}(s).
 */
export interface ReportTagSearch extends Search {
  /** Gets or sets search for {@link ReportTag}s coinciding with this ReportTemplateId. */
  reportTemplateId: string;
}
