//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { User } from "./User";
import { ReportArgumentType } from "./ReportArgumentType";

/** TypedArgument, all report arguments should be inherited from this class. */
export interface ReportTypedArgument {
  /** Gets or sets redirecting {@link User}. */
  redirectingUser: User;
  /** Gets or sets a value indicating whether to redirect SendReportTrue. */
  redirectSendReportTrue: boolean;
  /** Gets or sets {@link ReportTypedArgument.ReportArgumentType}. */
  reportArgumentType: ReportArgumentType;
}
