//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The frequency with which reports can be generated. */
export type ReportFrequency =
  | "None"
  | "FiveMinutes"
  | "ThirtyMinutes"
  | "Hourly"
  | "Daily"
  | "Weekly"
  | "Monthly"
  | "WhenNeed"
  | "Minute"
  | "BiWeekly"
  | "FourWeeks"
  | "Quarterly";
