//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/**
 *  The object used to specify the arguments when searching for {@link RestrictedDataModeChange}(s).
 */
export interface RestrictedDataModeChangeSearch extends Search {
  /**
   * Gets or sets search for {@link RestrictedDataModeChange}s with this {@link RestrictedDataModeChangeSearch.DeviceSearch} Id.
   *  Available DeviceSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for {@link RestrictedDataModeChange}s recorded at this date or after. */
  fromDate: Date;
  /** Gets or sets a value indicating whether gets or sets a value to include the first {@link RestrictedDataModeChange} before the {@link RestrictedDataModeChangeSearch.FromDate}. If {@link RestrictedDataModeChangeSearch.FromDate} is <c>null</c> this has no effect. */
  includeFromDateOverlap: boolean;
  /** Gets or sets search for {@link RestrictedDataModeChange}s recorded at this date or before. */
  toDate: Date;
}
