//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Device } from "./Device";

/**
 *  A {@link Device} and date pair that represents the last time a particular
 *  {@link RouteExtract} has been executed for a specific vehicle.
 *
 * @deprecated
 */
export interface RouteExtract extends Entity {
  /** Gets or sets the vehicle object to which the last date of the extract applies. */
  device: Device;
  /** Gets or sets the date when the extract has been completed for this vehicle. */
  lastExtractDateTime: Date;
}
