//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Device } from "./Device";

/** Data for a fleet cluster. */
export interface SafetyVehicleInsight {
  /**
   * @inheritdoc
   */
  aggregatedAreaRisk: number;
  /**
   * @inheritdoc
   */
  areaRiskClassificationEnum: number;
  /**
   * @inheritdoc
   */
  areaRiskClassificationText: string;
  /**
   * @inheritdoc
   */
  collisionCount: number;
  /**
   * @inheritdoc
   */
  crashProbabilityBenchmarkKm: number;
  /**
   * @inheritdoc
   */
  crashProbabilityBenchmarkMile: number;
  /**
   * @inheritdoc
   */
  crashProbabilityBestInClassKm: number;
  /**
   * @inheritdoc
   */
  crashProbabilityBestInClassMile: number;
  /**
   * @inheritdoc
   */
  crashProbabilityKm: number;
  /**
   * @inheritdoc
   */
  crashProbabilityMile: number;
  /**
   * @inheritdoc
   */
  crashProbabilityRange: string;
  /**
   * @inheritdoc
   */
  crashProbabilityRank: number;
  /**
   * @inheritdoc
   */
  crashProbabilityRiskLabel: string;
  /**
   * @inheritdoc
   */
  daysDriven: number;
  /** Gets or sets the device */
  device: Device;
  /**
   * @inheritdoc
   */
  distanceToday: number;
  /**
   * @inheritdoc
   */
  durationToday: number;
  /**
   * @inheritdoc
   */
  harshAccelerationRange: string;
  /**
   * @inheritdoc
   */
  harshAccelerationRank: number;
  /**
   * @inheritdoc
   */
  harshBrakingRange: string;
  /**
   * @inheritdoc
   */
  harshBrakingRank: number;
  /**
   * @inheritdoc
   */
  harshCorneringRange: string;
  /**
   * @inheritdoc
   */
  harshCorneringRank: number;
  /** Gets or sets the major version of the safety insight data. */
  majorVersion: number;
  /**
   * @inheritdoc
   */
  metaData: string;
  /** Gets or sets the minor version of the safety insight data. */
  minorVersion: number;
  /**
   * @inheritdoc
   */
  observationDate: Date;
  /**
   * @inheritdoc
   */
  overallSafetyRank: number;
  /** Gets or sets the patch version of the safety insight data. */
  patchVersion: number;
  /**
   * @inheritdoc
   */
  predictedCrashes: number;
  /**
   * @inheritdoc
   */
  predictedCrashesBenchmark: number;
  /**
   * @inheritdoc
   */
  predictedCrashesBestInClass: number;
  /**
   * @inheritdoc
   */
  relativeRiskKm: number;
  /**
   * @inheritdoc
   */
  relativeRiskMile: number;
  /**
   * @inheritdoc
   */
  relativeRiskRange: string;
  /**
   * @inheritdoc
   */
  seatbeltRank: number;
  /**
   * @inheritdoc
   */
  speedingRange: string;
  /**
   * @inheritdoc
   */
  speedingRank: number;
  /**
   * @inheritdoc
   */
  tailgatingDistanceKmToday: number;
  /**
   * @inheritdoc
   */
  tailgatingDistanceKmTripWindow: number;
  /**
   * @inheritdoc
   */
  tailgatingRange: string;
  /**
   * @inheritdoc
   */
  tailgatingRank: number;
  /**
   * @inheritdoc
   */
  totalDistanceKm7Days: number;
  /**
   * @inheritdoc
   */
  totalDistanceKmTripWindow: number;
  /**
   * @inheritdoc
   */
  totalDurationHrs7Days: number;
  /**
   * @inheritdoc
   */
  totalDurationHrsTripWindow: number;
}
