//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { ScheduleFrequency } from "./ScheduleFrequency";

/** The class representing a schedule. */
export interface Schedule extends Entity {
  /** Gets or sets the days which schedule repeats on. */
  daysOfWeek: number[];
  /** Gets or sets the end date for the schedule. */
  endDate: Date;
  /** Gets or sets the frequency of the schedule. */
  frequency: ScheduleFrequency;
  /** Gets or sets the repeat cycle. */
  repeatCycle: number;
  /** Gets or sets the start date for the schedule. */
  startDate: Date;
}
