//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";

/**
 *  The object used to specify the arguments when searching for
 *  {@link SecurityId}(s).
 *
 * @deprecated
 */
export interface SecurityIdSearch extends Search {
  /** Gets or sets a Search for SecurityId that has this customPageName. */
  customPageName: string;
}
