//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntity } from "./NameEntity";

/** The state the {@link ShareableLink} class */
export interface ShareableLinkState extends NameEntity {
  /** Gets or sets the unique identifier for this entity. */
  id: string;
  /** Gets or sets the key of this entity that uniquely identifies it and is used when getting this entity from the database. */
  name: string;
}
