//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Sort direction. */
export enum SortDirection {
  /** Ascending order. */
  Asc = "Asc",
  /** Descending order. */
  Desc = "Desc",
}
