//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Denotes the supported types for a given {@link Property} . */
export enum SupportedPropertyType {
  /** Integer custom property. */
  Integer = "Integer",
  /** String custom property. */
  String = "String",
  /** Boolean custom property. */
  Boolean = "Boolean",
}
