//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";

/** The object used to specify the arguments when searching {@link Tag} entries. */
export interface TagSearch extends Search {
  /**
   * Gets or sets search for Tags with this Name. Wildcard can be used by prepending/appending "%" to string.
   *  Example "%name%".
   */
  name: string;
  /** Gets or sets search for tag names. Supports up to 500 names. Does not support wildcards. */
  names: string[];
  /** Gets or sets search for Tag with given Tag Ids. Supports up to 500 Ids. */
  tagIds: string[];
}
