//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { GroupSearch } from "./GroupSearch";
import { GroupFilterCondition } from "./GroupFilterCondition";

/**
 *  The object used to specify the arguments when searching for
 *  {@link Trailer}(s).
 */
export interface TrailerSearch extends Search {
  /** Gets or sets for Trailers that are members of these groups or one of it's children using and/or relations . */
  groupFilterCondition: GroupFilterCondition;
  /**
   * Gets or sets search for Trailers that are members of these {@link GroupSearch}(s) one of
   *  it's children or
   *  one of it's parents. Available GroupSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  groups: GroupSearch[];
  /** Gets or sets search for Trailers with a name containing this {@link String}. Wildcard can be used by prepending/appending "%" to string. */
  name: string;
}
