//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntityWithVersion } from "./NameEntityWithVersion";
import { Group } from "./Group";

/**
 *  A trailer which can be attached and detached from a vehicle with a
 *  {@link TrailerAttachment} record.
 */
export interface Trailer extends NameEntityWithVersion {
  /** Gets or sets free text field where any user information can be stored and referenced for this entity. Default [""]. */
  comment: string;
  /** Gets or sets the list of trailer groups. */
  groups: Group[];
  /** Gets or sets the unique {@link Id} of the trailer. */
  id: string;
  /** Gets or sets the name of the trailer. Maximum length [255]. */
  name: string;
}
