//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Device } from "./Device";

/**
 *  This stores unique geohash based on {@link LogRecord} for a {@link Trip}.
 *
 * @deprecated
 */
export interface TripGeohash extends Entity {
  /** Gets or sets the associated trip start date time. */
  dateTime: Date;
  /** Gets or sets the {@link Device} associated with the {@link TripGeohash}. */
  device: Device;
  /** Gets or sets geohash of precision 6 based on latitude and longitude of {@link LogRecord}. */
  geohash: string;
}
