//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/**
 *  The object used to specify the arguments when searching for {@link TripTypeChange}(s).
 */
export interface TripTypeChangeSearch extends Search {
  /**
   * Gets or sets filter by the {@link DeviceSearch} options. Providing a device ID will
   *  search for any TripTypeChanges that are assigned to that Device.
   *  Providing the Groups will search for TripTypeChanges for that have Devices in that group.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for {@link TripTypeChange}s recorded at this date or after. */
  fromDate: Date;
  /** Gets or sets a value indicating whether gets or sets a value to include the first {@link TripTypeChange} before the {@link TripTypeChangeSearch.FromDate}. If {@link TripTypeChangeSearch.FromDate} is <c>null</c> this has no effect. */
  includeFromDateOverlap: boolean;
  /** Gets or sets search for {@link TripTypeChange}s recorded at this date or before. */
  toDate: Date;
}
