//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";

/** A class used to search for {@link TripAnnotation}s. */
export interface TripAnnotationSearch extends Search {
  /**
   * Gets or sets filter by the {@link DeviceSearch} options. Providing a device {@link Id} will
   *  search for any {@link TripAnnotation}s for that Device.
   */
  deviceSearch: DeviceSearch;
  /**
   * Gets or sets the {@link DateTime} to search for search for {@link TripAnnotation}s at or
   *  after.
   */
  fromDate: Date;
  /**
   * Gets or sets the {@link DateTime} to search for search for {@link TripAnnotation}s at or
   *  before.
   */
  toDate: Date;
}
