//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Device } from "./Device";

/** A class used to annotate a trip. Represents a comment at a moment in time for a device. */
export interface TripAnnotation extends Entity {
  /** Gets or sets the {@link TripAnnotation.DateTime} of the annotation. */
  dateTime: Date;
  /** Gets or sets the {@link TripAnnotation.Device} of the annotation. */
  device: Device;
  /** Gets or sets the text of the annotation. */
  text: string;
}
