//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";

/** The object used to specify the arguments when searching for {@link UploadTransaction}(s). */
export interface UploadTransactionSearch extends Search {
  /** Gets or sets a value indicating whether to search for {@link UploadTransaction} with this EntityName. */
  entityName: string;
  /** Gets or sets a value indicating whether to search for {@link UploadTransaction} with this EntityUploadRequestId. */
  entityUploadRequestId: number;
  /** Gets or sets a value indicating whether to search the {@link UploadTransaction} objects by the {@link UploadTransactionStatus}. */
  status: number;
}
