//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { HosRuleSet2 } from "./HosRuleSet2";
import { User } from "./User";

/** A user's Hos Ruleset. */
export interface UserHosRuleSet extends EntityWithVersion {
  /** Gets or sets the active from. */
  dateTime: Date;
  /** Gets or sets the ruleset. */
  hosRuleSet: HosRuleSet2;
  /** Gets or sets the start of day. */
  startOfDay: string;
  /** Gets or sets the user. */
  user: User;
}
