//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The user authentication type. */
export type UserAuthenticationType =
  | "None"
  | "BasicAuthentication"
  | "WindowsAuthentication"
  | "MyAdmin"
  | "SAML"
  | "ServiceAccount";
