//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 * The object used to specify the search criteria for finding {@link User}
 *  based on their welcome email and verification status.
 *  An OR condition is applied between the criteria, meaning any of the status parameters can match.
 */
export interface UserWelcomeEmailStatusSearch {
  /** Gets or sets search for Users who have been sent a welcome email but not verified yet. */
  verificationPending: boolean;
  /** Gets or sets search for Users who have not been sent a welcome email. */
  welcomeEmailNotSent: boolean;
}
