//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { UserSearch } from "./UserSearch";

/**
 *  The object used to specify the arguments when searching for
 *  {@link HosRuleSet} objects.
 */
export interface UserHosRuleSetSearch extends Search {
  /** Gets or sets search for hos ruleset objects that were recorded at this date or after. */
  fromDate: Date;
  /**
   * Gets or sets
   *  Search for {@link UserHosRuleSet}s with a maximum of this version.
   *
   * @deprecated
   */
  maxVersion: number;
  /**
   * Gets or sets
   *  Search for {@link UserHosRuleSet}s with a minimum of this version.
   *
   * @deprecated
   */
  minVersion: number;
  /** Gets or sets search for hos ruleset objects that were recorded at this date or before. */
  toDate: Date;
  /**
   * Gets or sets search for hos ruleset objects with this {@link UserSearch}.
   *  Available UserSearch options are:.
   *  <list><item><description>Id</description></item><item><description>GroupSearch</description></item></list>
   */
  userSearch: UserSearch;
}
