//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";
import { DeviceSearch } from "./DeviceSearch";
import { UserSearch } from "./UserSearch";
import { EntityLinkType } from "./EntityLink/EntityLinkType";

/**
 *  The object used to specify the arguments when searching for {@link UserDeviceLink}(s).
 *
 * @deprecated
 */
export interface UserDeviceLinkSearch extends Search {
  /** Gets or sets search for UserDeviceLink that were recorded with this ToDate or after. */
  afterToDate: Date;
  /**
   * Gets or sets search for UserDeviceLinks for this {@link DeviceSearch} Id.
   *  Available DeviceSearch options are:.
   *  <list><item><description>Id</description></item></list>
   *
   * @remarks UserSearch is always applied first if both DeviceSearch and UserSearch are provided.
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for UserDeviceLink that were recorded at this date or after. */
  fromDate: Date;
  /** Gets or sets a value indicating whether to include boundary links. */
  includeBoundaryLinks: boolean;
  /** Gets or sets search for UserDeviceLinks that match the specified {@link EntityLinkType} */
  linkTypes: EntityLinkType[];
  /** Gets or sets search for UserDeviceLink that were recorded at this date or before. */
  toDate: Date;
  /**
   * Gets or sets search for UserDeviceLink with this {@link UserSearch} Id.
   *  Available UserSearch options are:.
   *  <list><item><description>Id</description></item></list>
   */
  userSearch: UserSearch;
}
