//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The type of encryption of {@link VehicleConfiguration}. */
export enum VehicleConfigurationEncryptionType {
  /** No encryption */
  NoEncryption = "NoEncryption",
  /** AES-256. Encrypted by key from credentials.xml */
  AES256CredentialsKey = "AES256CredentialsKey",
}
