//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "./EntityWithVersion";
import { Device } from "./Device";

/** VehicleConfiguration parameters entity. */
export interface VehicleConfiguration extends EntityWithVersion {
  /** Gets or sets the {@link Device} associated with this VehicleConfiguration. */
  device: Device;
}
