//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The names of vehicle feature categories, including external devices detected by the device and features that are manually activated by the server. */
export type VehicleFeatureCategory =
  | "UnknownDevice"
  | "Garmin"
  | "Iridium"
  | "Hos"
  | "Nfc"
  | "GoTalk"
  | "Mobileye"
  | "Valor"
  | "WiFi"
  | "SaltSpreader"
  | "GoActive"
  | "OBDPresent"
  | "OBDEnabled"
  | "ContinuousConnect"
  | "IOX_CarShare"
  | "GarminHos"
  | "GeotabDriveHos";
