//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Device } from "./Device";
import { IntervalAggregateType } from "./IntervalAggregateType";

/** Represents aggregated vehicle downtime data. */
export interface VehicleDowntime {
  /** Gets or sets the {@link VehicleDowntime.AggregateType} of this record. */
  aggregateType: IntervalAggregateType;
  /** Gets or sets the date and time when the vehicle downtime record was first inserted into the database. */
  dateInserted: Date;
  /** Gets or sets the {@link Device}. */
  device: Device;
  /** Gets or sets the total count of downtime events. */
  downtimeCount: number;
  /** Gets or sets the total time duration in seconds. */
  downtimeDuration: number;
  /** Gets or sets the local date of the aggregation. */
  localDate: Date;
  /** Gets or sets the major version of vehicle downtime. */
  majorVersion: number;
  /** Gets or sets the minor version of vehicle downtime. */
  minorVersion: number;
  /** Gets or sets the patch version of vehicle downtime. */
  patchVersion: number;
  /** Gets or sets the repair class for the downtime. */
  repairClass: string;
  /** Gets or sets the source reason for the downtime. */
  sourceReason: string;
  /** Gets or sets the IANA Timezone id of the record. Default ["Etc/UTC"]. */
  timeZoneId: string;
}
