//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** WebRequest Template Http Verb. */
export type WebRequestTemplateHttpVerb = "Get" | "Post";
