//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntity } from "./NameEntity";
import { WidgetType } from "./WidgetType";
import { ReportPeriod } from "./ReportPeriod";
import { User } from "./User";

/** Widget class represents a single widget that is a part of dashboard displayed on dashboard page. */
export interface Widget extends NameEntity {
  /** Gets or sets the date the widget is active from. Default [UtcNow]. */
  activeFrom: Date;
  /** Gets or sets the date the widget is active to. Default [MaxDate]. */
  activeTo: Date;
  /** Gets or sets the details of the widget. The details are in json format. Default [""]. */
  jsonDetails: string;
  /** Gets or sets the {@link User} who created the widget. */
  owner: User;
  /** Gets or sets the {@link ReportPeriod} of scheduled report. */
  period: ReportPeriod;
  /** Gets or sets the widget type. */
  type: WidgetType;
}
