//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The object used to specify the arguments when searching for a {@link WifiHotspot}. */
export interface WifiHotspotSearch {}
