//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntity } from "./NameEntity";

/** The type of the zone. */
export interface ZoneType extends NameEntity {
  /** Gets or sets a free text field where any user information can be stored and referenced for this entity. Default [""]. */
  comment: string;
}
