//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "./Search";

/** The object used to specify the arguments when searching for a {@link ZoneMetadata}. */
export interface ZoneMetadataSearch extends Search {
  /** Gets or sets list of zone ids to get zonemetadata for all the zone ids. */
  zoneIds: string[];
}
