//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "./Entity";
import { Zone } from "./Zone";
import { ZoneMetadataType } from "./ZoneMetadataType";

/** The metadata of Zone. */
export interface ZoneMetadata extends Entity {
  /** Gets or sets the metadata type. */
  metadataType: ZoneMetadataType;
  /** Gets or sets value of the metadata. */
  numericValue: number;
  /** Gets or sets value of the metadata. */
  stringData: string;
  /** Gets or sets the zone. */
  zone: Zone;
}
