//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Specifies the particular hash algorithm type. */
export type HashAlgorithmType = "None" | "Md5" | "Sha256" | "Sha512";
