//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { RegistrationStatus } from "./RegistrationStatus";

/** Lite class to store JSON blob data regarding a registration attempt to the Gateway. */
export interface RegisterDeviceResultLite {
  /** Gets or sets the registration enum value. */
  registrationStatus: RegistrationStatus;
}
