//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { DeviceSearch } from "../DeviceSearch";

/** The object used to specify the arguments when searching for a {@link FuelAndEnergySnapshotProcessing} entry. */
export interface FuelAndEnergySnapshotProcessingSearch extends Search {
  /**
   * Gets or sets the device search criteria for the FuelAndEnergySnapshotProcessing entry with this {@link DeviceSearch} Id. Available DeviceSearch options are:.
   *  <list><item><description>Id</description><description>Groups</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets the from date, which is used to search for Snapshot Processing recorded on or after this date. */
  fromDate: Date;
  /** Gets or sets the IsProcessingComplete flag, which is used to search for Snapshot Processing that is completed. */
  isProcessingComplete: boolean;
  /** Gets or sets the to snapshot type, which is used to search for Snapshot Processing. */
  snapshotType: string;
  /** Gets or sets the to date, which is used to search for Snapshot Processing recorded on or before this date. */
  toDate: Date;
}
