//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 *  Various Electric Energy Economy units Geotab supports. Currently supported units: L-e/100 km, km/L-e, kWh/100 km, Wh/km, km/kWh, MPG-e (US), MPG-e (Imp), kWh/100 miles, Wh/mile and mile/kWh.
 */
export type ElectricEnergyEconomyUnit =
  | "LitersEPer100Km"
  | "KmPerLitersE"
  | "KiloWhPer100Km"
  | "WhPerKm"
  | "KmPerKiloWh"
  | "MPGEUS"
  | "MPGEImperial"
  | "KiloWhPer100Miles"
  | "WhPerMile"
  | "MilePerKiloWh"
  | "KiloWhPerKm"
  | "KiloWhPerMile";
