//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Used to represent different Google Map styles. */
export enum GoogleMapStyle {
  /** Google map road map view. */
  Roadmap = "Roadmap",
  /** Google map hybrid view. */
  Hybrid = "Hybrid",
  /** Google map terrain view. */
  Terrain = "Terrain",
  /** Google map satellite view. */
  Satellite = "Satellite",
}
