//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 *  Various supported Volume units Geotab supports.
 */
export enum VolumeUnit {
  /** The liter volume unit. */
  Liter = "Liter",
  /** The gallon US volume unit. */
  GallonUS = "GallonUS",
  /** The gallon Imperial volume unit. */
  GallonImp = "GallonImp",
}
