//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The {@link Zone}s which will be displayed to a given user on the map. */
export type ZoneDisplayMode = "None" | "All" | "Default";
