//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { BasicDiagnostic } from "../Engine/BasicDiagnostic";
import { Device } from "../Device";
import { EventOccurrence } from "../EventOccurrence";

/** The data change for a particular diagnostic. */
export interface DiagnosticValueStatus extends Entity {
  /** Gets or sets the creation {@link DateTime} of the {@link DiagnosticValueStatus}. */
  createdAt: Date;
  /** Gets or sets the device related to the {@link DiagnosticValueStatus}. */
  device: Device;
  /** Gets or sets the diagnostic related to the {@link DiagnosticValueStatus}. */
  diagnostic: BasicDiagnostic;
  /** Gets or sets whether the data is considered ON or OFF. */
  isOn: boolean;
  /** Gets or sets the last value reported */
  lastValue: number;
  /** Gets or sets the device related to the {@link EventOccurrence}. */
  maintenanceRecord: EventOccurrence;
}
