//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { DocScanningEntityType } from "./DocScanningEntityType";
import { DocScanningState } from "./DocScanningState";

/** Search criteria for {@link DocumentScanning}. */
export interface DocumentScanningSearch extends Search {
  /** Gets or sets the entity ID to search for. */
  entityId: string;
  /** Gets or sets the entity type to search for. */
  entityType: DocScanningEntityType;
  /** Gets or sets the document scanning state to search for. */
  state: DocScanningState;
}
