//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Maintenance Status */
export type MaintenanceStatus =
  | "Draft"
  | "Open"
  | "Assigned"
  | "InProgress"
  | "OnHold"
  | "Completed"
  | "Canceled";
