//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 * Maintenance Source
 *  If the enum is changed, the MaintenanceWorkOrder Status property summary has to be updated as well.
 *  Note: Because of evolution of the source property MaintenanceSourceType would be now a better fit for this enum.
 */
export type MaintenanceSource =
  | "Manual"
  | "Scheduled"
  | "DataInsight"
  | "DriverReported"
  | "Faults"
  | "Rules";
