//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntityWithVersion } from "../NameEntityWithVersion";
import { MaintenanceSchedule } from "../MaintenanceSchedule";
import { Device } from "../Device";
import { MaintenanceWorkOrder } from "./MaintenanceWorkOrder";
import { Currency } from "../Currencies/Currency";
import { EventType } from "../EventType";
import { MediaFile } from "../Files/MediaFile";

/** Maintenance Work Order Job for a particular device. */
export interface MaintenanceWorkOrderJob extends NameEntityWithVersion {
  /** Gets or sets the currency of the work job. */
  costCurrency: string;
  /** Gets or sets the currency in which costs will be displayed. */
  costCurrencyConverted: Currency;
  /** Gets or sets a value indicating whether the currency conversion failed */
  currencyConversionFailed: boolean;
  /** Gets or sets the date completed of the work job. */
  dateCompleted: Date;
  /** Gets or sets the date the work job was created. */
  dateTime: Date;
  /**
   * @inheritdoc
   */
  deletedDateTime: Date;
  /** Gets or sets the description of the work job. */
  description: string;
  /** Gets or sets the {@link MaintenanceWorkOrderJob.Device} related to the work job. */
  device: Device;
  /** Gets or sets the current engine hours reading of the {@link MaintenanceWorkOrderJob.Device}. */
  engineHoursReading: string;
  /** Gets the current engine hours of the {@link MaintenanceWorkOrderJob.Device} rounded to the nearest whole hour. */
  engineHoursReadingInHours: number;
  /** Gets or sets the event description. */
  eventDescription: string;
  /** Gets or sets the hours spent on the work job. */
  hours: number;
  /** Gets or sets a value indicating whether the work job is closed. */
  isClosed: boolean;
  /** Gets or sets the labor costs of the work job. */
  laborCosts: number;
  /** Gets or sets the labor costs converted of the work job. */
  laborCostsConverted: number;
  /** Gets or sets the {@link EventType} of the work job. */
  maintenanceType: EventType;
  /** Gets or sets the list of {@link MediaFile} for a event. */
  mediaFiles: MediaFile[];
  /** Gets or sets the metadata of the work job. */
  metadata: { [key: string]: string };
  /** Gets or sets the notes for the work job. */
  notes: string;
  /** Gets or sets the current odometer reading of the {@link MaintenanceWorkOrderJob.Device}. */
  odometerReading: number;
  /** Gets or sets the current odometer reading of the {@link MaintenanceWorkOrderJob.Device}. */
  odometerReadingDisplay: number;
  /** Gets or sets the parts costs of the work job. */
  partsCost: number;
  /** Gets or sets the parts costs converted of the work job. */
  partsCostConverted: number;
  /** Gets or sets the reference of the work job. */
  reference: string;
  /** Gets or sets the {@link MaintenanceSchedule} related to the work job. */
  schedule: MaintenanceSchedule;
  /** Gets or sets the service work accomplished code for the work job. */
  serviceWorkAccomplishedCode: number;
  /** Gets or sets the severity of the work job. */
  severityCode: number;
  /** Gets or sets the severity of the work job. */
  severityCodeDisplay: number;
  /** Gets or sets the shipping cost of the work job. */
  shippingCosts: number;
  /** Gets or sets the shipping cost converted of the work job. */
  shippingCostsConverted: number;
  /** Gets or sets the start date and time of the work job. */
  startDate: Date;
  /** Gets or sets the status of the work job. */
  statusCode: number;
  /** Gets or sets the status of the work job. */
  statusCodeDisplay: number;
  /** Gets or sets the tax costs of the work job. */
  taxCosts: number;
  /** Gets or sets the tax costs of the work job. */
  taxCostsConverted: number;
  /** Gets or sets the total costs of the work job. */
  totalCosts: number;
  /** Gets or sets the total costs of the work job. */
  totalCostsConverted: number;
  /** Gets or sets the triggered date the work job is due. */
  triggeredDate: Date;
  /** Gets or sets the date the job was updated. */
  updateDate: Date;
  /** Gets or sets the VMRS (Vehicle Maintenance Reporting Standards) system code of the work job. */
  vmrsSystemCode: number;
  /** Gets or sets the related work order job. */
  workOrder: MaintenanceWorkOrder;
}
