//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntityWithVersion } from "../NameEntityWithVersion";
import { Device } from "../Device";
import { User } from "../User";
import { Zone } from "../Zone";
import { MediaFile } from "../Files/MediaFile";

/** Maintenance Work Order for a particular device. */
export interface MaintenanceWorkOrder extends NameEntityWithVersion {
  /** Gets or sets the {@link User} assigned to the work order. */
  assignedTo: User;
  /** Gets or sets the date the work order was completed by the user. Should be later than {@link MaintenanceWorkOrder.DateTime}. */
  completedDateTime: Date;
  /** Gets or sets the currency cost for the work order. */
  costCurrency: string;
  /** Gets or sets the currency cost from user setting for the work order. */
  costCurrencyConverted: string;
  /** Gets or sets a value indicating whether the currency conversion failed */
  currencyConversionFailed: boolean;
  /** Gets or sets the date the work order was open by the user. Must be earlier than {@link MaintenanceWorkOrder.CompletedDateTime}. */
  dateTime: Date;
  /**
   * @inheritdoc
   */
  deletedDateTime: Date;
  /** Gets or sets the device of the work order. */
  device: Device;
  /** Gets or sets the date the work order is due. */
  dueOnDate: Date;
  /** Gets or sets the current engine hours reading of the {@link MaintenanceWorkOrder.Device}. */
  engineHoursReading: string;
  /** Gets the current engine hours of the {@link MaintenanceWorkOrder.Device} rounded to the nearest whole hour. */
  engineHoursReadingInHours: number;
  /** Gets or sets the labor cost of the work order. */
  laborCost: number;
  /** Gets or sets the labor cost converted of the work order. */
  laborCostConverted: number;
  /** Gets or sets the list of {@link MediaFile} for a event. */
  mediaFiles: MediaFile[];
  /** Gets or sets the notes of the work order. */
  notes: string;
  /** Gets or sets the current odometer reading of the {@link MaintenanceWorkOrder.Device}. */
  odometerReading: number;
  /** Gets or sets the current odometer reading of the {@link MaintenanceWorkOrder.Device}. */
  odometerReadingDisplay: number;
  /** Gets or sets the {@link User} that opened the work order. */
  openedByUser: User;
  /** Gets or sets the parts cost of the work order. */
  partsCost: number;
  /** Gets or sets the parts cost converted of the work order. */
  partsCostConverted: number;
  /** Gets or sets the priority of the work order. */
  priorityCode: number;
  /** Gets or sets the priority of the work order. */
  priorityCodeDisplay: number;
  /** Gets or sets the reference of the order. */
  reference: string;
  /** Gets or sets the "Repair Class of the work order. */
  repairClass: number;
  /** Gets or sets the "Repair Class of the work order. */
  repairClassDisplay: number;
  /** Gets or sets the Reason For Repair of the work order. */
  repairReason: number;
  /** Gets or sets the Reason For Repair of the work order. */
  repairReasonDisplay: number;
  /** Gets or sets the shipping cost of the work order. */
  shippingCost: number;
  /** Gets or sets the shipping cost converted of the work order. */
  shippingCostConverted: number;
  /** Gets or sets the status of the work order. */
  statusCode: number;
  /** Gets or sets the status of the work order. */
  statusCodeDisplay: number;
  /** Gets or sets the tax cost of the work order. */
  taxCost: number;
  /** Gets or sets the tax cost converted of the work order. */
  taxCostConverted: number;
  /** Gets or sets the period during which the work order was open. */
  timeOpen: string;
  /** Gets or sets the total cost of the work order. */
  totalCost: number;
  /** Gets or sets the total cost converted of the work order. */
  totalCostConverted: number;
  /** Gets or sets the update date of the work order. */
  updatedDate: Date;
  /** Gets or sets the zone of repair site of the work order. */
  zone: Zone;
}
