//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";

/** The object used to specify the arguments when searching for {@link AddInConfiguration}. */
export interface AddInConfigurationSearch extends Search {
  /** Gets or sets the name of this Add-In. */
  name: string;
  /** Gets or sets the solution id related to this Add-In. */
  solutionId: string;
  /** Gets or sets the email address for support related to this Add-In. */
  supportEmail: string;
}
