//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { AddInConfiguration } from "./AddInConfiguration";

/** Represents populated MyGeotab addin. */
export interface AddIn extends Entity {
  /** Gets or sets addin Configuration */
  configuration: AddInConfiguration;
  /** Gets or sets addin error message */
  errorMessage: string;
  /** Gets or sets addin Url */
  url: string;
}
