//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Installation type for the device. - e.g. "New Installation" in case of first time install. */
export enum InstallationType {
  /** Default installation type which can be used in case of reading in old version from the updated database. */
  Unknown = "Unknown",
  /** Type of installation is New Installation. */
  NewInstallation = "NewInstallation",
  /** Type of Installation is Swap Devices */
  SwapDevices = "SwapDevices",
  /** Type of Installation is Service Device */
  ServiceDevice = "ServiceDevice",
  /** Type of Installation is Remove Device */
  RemoveDevice = "RemoveDevice",
}
