//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Exception area type. This must match to the Error Reporting areas for the MyGeotab project. */
export type AreaType =
  | "None"
  | "Unspecified"
  | "CustomerSpecific"
  | "Database"
  | "Documentation"
  | "Drive"
  | "Eld"
  | "IoxAddOns"
  | "Language"
  | "Logging"
  | "MapServer"
  | "Notifications"
  | "ObjectModel"
  | "Optimization"
  | "Reports"
  | "RulesProcessor"
  | "Sdk"
  | "Serializer"
  | "UserInterface"
  | "UnitTests"
  | "WebServer";
