//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Severity level. */
export enum SeverityLevel {
  /** Serious issue. Immediate actions may be required. */
  Critical = "Critical",
  /** Potential problem. Some actions may be required. */
  Warning = "Warning",
  /** FYI. No actions are required. */
  Info = "Info",
}
