//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The current database transfer status. */
export type DatabaseTransferStatus =
  | "None"
  | "Idle"
  | "InProgress"
  | "AlreadyInProgress"
  | "LimitExceeded";
