//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The conditions used as part of an entity link rule. */
export interface EntityLinkRuleConditions {
  /** Gets or sets the value of the destination count condition. */
  destinationCount: number;
}
