//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The type of {@link EntityLinkType}. */
export enum EntityLinkType {
  /** A device link type is specified. */
  Device = "Device",
  /** A device to driver link type is specified. */
  DeviceDriver = "DeviceDriver",
  /** A device to co-driver link type is specified. */
  DeviceCoDriver = "DeviceCoDriver",
  /** A device to passenger link type is specified. */
  DevicePassenger = "DevicePassenger",
}
