//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../../Entity";

/** The object used to contain the database dashboard cache info. */
export interface DashboardCache extends Entity {
  /** Gets or sets the dashboard as binary data. */
  binaryData: number[];
  /** Gets or sets the dashboard cache expiry date. */
  expiryDate: Date;
  /** Gets or sets the dashboard key. */
  key: string;
}
