//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntityWithVersion } from "../NameEntityWithVersion";
import { MediaType } from "./MediaType";
import { Driver } from "../Driver";
import { Device } from "../Device";
import { Status } from "./Status";

/** The entity which describes the binary media. */
export interface MediaFile extends NameEntityWithVersion {
  /** Gets or sets the {@link Device} associated with the file. */
  device: Device;
  /** Gets or sets the {@link Driver} associated with the file. */
  driver: Driver;
  /** Gets or sets the from date. */
  fromDate: Date;
  /** Gets or sets the {@link MediaType}. */
  mediaType: MediaType;
  /** Gets or sets file metadata in JSON format. */
  metaData: string;
  /** Gets or sets the {@link Id} of the solution which added the data. */
  solutionId: string;
  /** Gets or sets the file processing {@link Status}. */
  status: Status;
  /** Gets or sets the list of tags to provide context to the file. */
  tags: unknown[];
  /** Gets or sets the list of files which serve as the thumbnail for this file. */
  thumbnails: MediaFile[];
  /** Gets or sets the to date. */
  toDate: Date;
}
