//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The status of an uploaded file. */
export enum Status {
  /** The status is unknown. */
  Unknown = "Unknown",
  /** The file is being processed. */
  Processing = "Processing",
  /** The file is ready. */
  Ready = "Ready",
  /** Media file has not been uploaded. */
  NoFile = "NoFile",
}
