import { AddInData } from "./Checkmate/ObjectModel/AddInData";
import { AnnotationLog } from "./Checkmate/ObjectModel/AnnotationLog";
import { AssetLink } from "./Checkmate/ObjectModel/AssetLink";
import { AssetLinkDetails } from "./Checkmate/ObjectModel/AssetLinkDetails";
import { AssetSeparationSubscription } from "./Checkmate/ObjectModel/AssetSeparationSubscription";
import { Audit } from "./Checkmate/ObjectModel/Audit";
import { BatteryStateOfHealth } from "./Checkmate/ObjectModel/BatteryStateOfHealth";
import { BinaryData } from "./Checkmate/ObjectModel/BinaryData";
import { Camera } from "./Checkmate/ObjectModel/Camera";
import { CameraHealth } from "./Checkmate/ObjectModel/CameraHealth";
import { CameraStatus } from "./Checkmate/ObjectModel/CameraStatus";
import { Certificate } from "./Checkmate/ObjectModel/Certificate";
import { CoachingSession } from "./Checkmate/ObjectModel/CoachingSession";
import { CustomData } from "./Checkmate/ObjectModel/CustomData";
import { CustomReportSchedule } from "./Checkmate/ObjectModel/CustomReportSchedule";
import { DebugData } from "./Checkmate/ObjectModel/DebugData";
import { Defect } from "./Checkmate/ObjectModel/Defect";
import { DefectRemark } from "./Checkmate/ObjectModel/DefectRemark";
import { Device } from "./Checkmate/ObjectModel/Device";
import { DeviceCommunicationHistory } from "./Checkmate/ObjectModel/DeviceCommunicationHistory";
import { DeviceCommunicationStatus } from "./Checkmate/ObjectModel/DeviceCommunicationStatus";
import { DeviceLink } from "./Checkmate/ObjectModel/DeviceLink";
import { DeviceMasterFlag } from "./Checkmate/ObjectModel/DeviceMasterFlag";
import { DeviceShare } from "./Checkmate/ObjectModel/DeviceShare";
import { DeviceStatusInfo } from "./Checkmate/ObjectModel/DeviceStatusInfo";
import { DiscreteAvailabilitySnapshot } from "./Checkmate/ObjectModel/DiscreteAvailabilitySnapshot";
import { DistributionList } from "./Checkmate/ObjectModel/DistributionList";
import { DriverChange } from "./Checkmate/ObjectModel/DriverChange";
import { DriverRegulation } from "./Checkmate/ObjectModel/DriverRegulation";
import { DriverRegulationServiceScheduleInfo } from "./Checkmate/ObjectModel/DriverRegulationServiceScheduleInfo";
import { DutyStatusAvailability } from "./Checkmate/ObjectModel/DutyStatusAvailability";
import { DutyStatusLog } from "./Checkmate/ObjectModel/DutyStatusLog";
import { DutyStatusViolation } from "./Checkmate/ObjectModel/DutyStatusViolation";
import { DVIRDefect } from "./Checkmate/ObjectModel/DVIRDefect";
import { DVIRLog } from "./Checkmate/ObjectModel/DVIRLog";
import { ElectrificationAggregation } from "./Checkmate/ObjectModel/ElectrificationAggregation";
import { EmployeeRoutePlan } from "./Checkmate/ObjectModel/EmployeeRoutePlan";
import { EntityUploadRequest } from "./Checkmate/ObjectModel/EntityUploadRequest";
import { EventDeviation } from "./Checkmate/ObjectModel/EventDeviation";
import { EventOccurrence } from "./Checkmate/ObjectModel/EventOccurrence";
import { EventOccurrenceDue } from "./Checkmate/ObjectModel/EventOccurrenceDue";
import { EventType } from "./Checkmate/ObjectModel/EventType";
import { ExceptionEventMediaLink } from "./Checkmate/ObjectModel/ExceptionEventMediaLink";
import { FaultCycle } from "./Checkmate/ObjectModel/FaultCycle";
import { FaultRichData } from "./Checkmate/ObjectModel/FaultRichData";
import { Feedback } from "./Checkmate/ObjectModel/Feedback";
import { FeedVersionTrackingData } from "./Checkmate/ObjectModel/FeedVersionTrackingData";
import { FuelAndEnergySetting } from "./Checkmate/ObjectModel/FuelAndEnergySetting";
import { FuelAndEnergyUsedAggregation } from "./Checkmate/ObjectModel/FuelAndEnergyUsedAggregation";
import { FuelTaxDetail } from "./Checkmate/ObjectModel/FuelTaxDetail";
import { Group } from "./Checkmate/ObjectModel/Group";
import { GroupAddIn } from "./Checkmate/ObjectModel/GroupAddIn";
import { GroupDevice } from "./Checkmate/ObjectModel/GroupDevice";
import { GroupFilter } from "./Checkmate/ObjectModel/GroupFilter";
import { GroupZoneMetadata } from "./Checkmate/ObjectModel/GroupZoneMetadata";
import { HosRulesetConfig } from "./Checkmate/ObjectModel/HosRulesetConfig";
import { HosStatusInfo } from "./Checkmate/ObjectModel/HosStatusInfo";
import { IdlingExceptionAggregation } from "./Checkmate/ObjectModel/IdlingExceptionAggregation";
import { IdlingFuelPercentageAggregation } from "./Checkmate/ObjectModel/IdlingFuelPercentageAggregation";
import { InspectedItem } from "./Checkmate/ObjectModel/InspectedItem";
import { InspectionLog } from "./Checkmate/ObjectModel/InspectionLog";
import { Investigation } from "./Checkmate/ObjectModel/Investigation";
import { InvestigationAttachment } from "./Checkmate/ObjectModel/InvestigationAttachment";
import { InvestigationComment } from "./Checkmate/ObjectModel/InvestigationComment";
import { IoxAddOn } from "./Checkmate/ObjectModel/IoxAddOn";
import { IoxAddOnStatus } from "./Checkmate/ObjectModel/IoxAddOnStatus";
import { IoxWorksConfigFileInfo } from "./Checkmate/ObjectModel/IoxWorksConfigFileInfo";
import { LiveCompletionMapConfig } from "./Checkmate/ObjectModel/LiveCompletionMapConfig";
import { LogRecord } from "./Checkmate/ObjectModel/LogRecord";
import { LogRecordGeohash } from "./Checkmate/ObjectModel/LogRecordGeohash";
import { LogRecordZoneDistance } from "./Checkmate/ObjectModel/LogRecordZoneDistance";
import { LostModeChange } from "./Checkmate/ObjectModel/LostModeChange";
import { MaintenanceNotificationRule } from "./Checkmate/ObjectModel/MaintenanceNotificationRule";
import { MaintenanceNotificationState } from "./Checkmate/ObjectModel/MaintenanceNotificationState";
import { MaintenanceSchedule } from "./Checkmate/ObjectModel/MaintenanceSchedule";
import { MediaRequestNotification } from "./Checkmate/ObjectModel/MediaRequestNotification";
import { MimeTask } from "./Checkmate/ObjectModel/MimeTask";
import { Notification } from "./Checkmate/ObjectModel/Notification";
import { Property } from "./Checkmate/ObjectModel/Property";
import { PropertySet } from "./Checkmate/ObjectModel/PropertySet";
import { QueuedEntityRemoveTask } from "./Checkmate/ObjectModel/QueuedEntityRemoveTask";
import { RangeEstimate } from "./Checkmate/ObjectModel/RangeEstimate";
import { Recipient } from "./Checkmate/ObjectModel/Recipient";
import { ReportStorage } from "./Checkmate/ObjectModel/ReportStorage";
import { ReportTag } from "./Checkmate/ObjectModel/ReportTag";
import { ReportTemplate } from "./Checkmate/ObjectModel/ReportTemplate";
import { RestrictedDataModeChange } from "./Checkmate/ObjectModel/RestrictedDataModeChange";
import { Route } from "./Checkmate/ObjectModel/Route";
import { RouteExtract } from "./Checkmate/ObjectModel/RouteExtract";
import { SafetyDriverInsight } from "./Checkmate/ObjectModel/SafetyDriverInsight";
import { SafetyFleetBenchmark } from "./Checkmate/ObjectModel/SafetyFleetBenchmark";
import { SafetyFleetInsight } from "./Checkmate/ObjectModel/SafetyFleetInsight";
import { SafetyVehicleInsight } from "./Checkmate/ObjectModel/SafetyVehicleInsight";
import { SecurityId } from "./Checkmate/ObjectModel/SecurityId";
import { ServiceState } from "./Checkmate/ObjectModel/ServiceState";
import { ShareableLink } from "./Checkmate/ObjectModel/ShareableLink";
import { ShipmentLog } from "./Checkmate/ObjectModel/ShipmentLog";
import { TextMessage } from "./Checkmate/ObjectModel/TextMessage";
import { Trailer } from "./Checkmate/ObjectModel/Trailer";
import { TrailerAttachment } from "./Checkmate/ObjectModel/TrailerAttachment";
import { Trip } from "./Checkmate/ObjectModel/Trip";
import { TripAnnotation } from "./Checkmate/ObjectModel/TripAnnotation";
import { TripGeohash } from "./Checkmate/ObjectModel/TripGeohash";
import { TripTypeChange } from "./Checkmate/ObjectModel/TripTypeChange";
import { UploadTransaction } from "./Checkmate/ObjectModel/UploadTransaction";
import { User } from "./Checkmate/ObjectModel/User";
import { UserDeviceLink } from "./Checkmate/ObjectModel/UserDeviceLink";
import { UserHosRuleSet } from "./Checkmate/ObjectModel/UserHosRuleSet";
import { UserLoginStatus } from "./Checkmate/ObjectModel/UserLoginStatus";
import { UserSupport } from "./Checkmate/ObjectModel/UserSupport";
import { VehicleDowntime } from "./Checkmate/ObjectModel/VehicleDowntime";
import { WifiHotspot } from "./Checkmate/ObjectModel/WifiHotspot";
import { WorkHoliday } from "./Checkmate/ObjectModel/WorkHoliday";
import { WorkTime } from "./Checkmate/ObjectModel/WorkTime";
import { Zone } from "./Checkmate/ObjectModel/Zone";
import { ZoneMetadata } from "./Checkmate/ObjectModel/ZoneMetadata";
import { ZoneType } from "./Checkmate/ObjectModel/ZoneType";
import { AddIn } from "./Checkmate/ObjectModel/AddIns/AddIn";
import { ChargeEvent } from "./Checkmate/ObjectModel/Charging/ChargeEvent";
import { ConsentStatus } from "./Checkmate/ObjectModel/Consent/ConsentStatus";
import { ConsentStatusAudit } from "./Checkmate/ObjectModel/Consent/ConsentStatusAudit";
import { Option } from "./Checkmate/ObjectModel/Consent/Option";
import { Product } from "./Checkmate/ObjectModel/Consent/Product";
import { DeviceRegistrationState } from "./Checkmate/ObjectModel/DeviceRegistration/DeviceRegistrationState";
import { DeviceReplacementInfo } from "./Checkmate/ObjectModel/DeviceReplacement/DeviceReplacementInfo";
import { EmissionComplianceEvent } from "./Checkmate/ObjectModel/EmissionReporting/EmissionComplianceEvent";
import { EmissionReport } from "./Checkmate/ObjectModel/EmissionReporting/EmissionReport";
import { EmissionServiceConnectionLog } from "./Checkmate/ObjectModel/EmissionReporting/EmissionServiceConnectionLog";
import { EmissionVehicleCycle } from "./Checkmate/ObjectModel/EmissionReporting/EmissionVehicleCycle";
import { EmissionVehicleCycleMessage } from "./Checkmate/ObjectModel/EmissionReporting/EmissionVehicleCycleMessage";
import { EmissionVehicleEnrollment } from "./Checkmate/ObjectModel/EmissionReporting/EmissionVehicleEnrollment";
import { EnergySnapshotRecord } from "./Checkmate/ObjectModel/Energy/EnergySnapshotRecord";
import { Controller } from "./Checkmate/ObjectModel/Engine/Controller";
import { Diagnostic } from "./Checkmate/ObjectModel/Engine/Diagnostic";
import { DiagnosticData } from "./Checkmate/ObjectModel/Engine/DiagnosticData";
import { DiagnosticLookupTable } from "./Checkmate/ObjectModel/Engine/DiagnosticLookupTable";
import { DiagnosticMapping } from "./Checkmate/ObjectModel/Engine/DiagnosticMapping";
import { EngineType } from "./Checkmate/ObjectModel/Engine/EngineType";
import { FailureMode } from "./Checkmate/ObjectModel/Engine/FailureMode";
import { FaultData } from "./Checkmate/ObjectModel/Engine/FaultData";
import { ParameterGroup } from "./Checkmate/ObjectModel/Engine/ParameterGroup";
import { Source } from "./Checkmate/ObjectModel/Engine/Source";
import { StatusData } from "./Checkmate/ObjectModel/Engine/StatusData";
import { UnitOfMeasure } from "./Checkmate/ObjectModel/Engine/UnitOfMeasure";
import { DisplayMeasurementProfile } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfile";
import { DisplayMeasurementProfileDetail } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileDetail";
import { DisplayUnitOfMeasure } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayUnitOfMeasure";
import { UserDisplayProfile } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/UserDisplayProfile";
import { EntityLinkRule } from "./Checkmate/ObjectModel/EntityLink/EntityLinkRule";
import { EntitySetting } from "./Checkmate/ObjectModel/EntitySettings/EntitySetting";
import { EVStatusInfo } from "./Checkmate/ObjectModel/EVStatus/EVStatusInfo";
import { EvsaConfiguration } from "./Checkmate/ObjectModel/EvSuitabilityAssessment/EvsaConfiguration";
import { EvsaRequest } from "./Checkmate/ObjectModel/EvSuitabilityAssessment/EvsaRequest";
import { ExceptionEvent } from "./Checkmate/ObjectModel/Exceptions/ExceptionEvent";
import { ExceptionEventAttachment } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventAttachment";
import { ExceptionEventComment } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventComment";
import { Rule } from "./Checkmate/ObjectModel/Exceptions/Rule";
import { MediaFile } from "./Checkmate/ObjectModel/Files/MediaFile";
import { FillUp } from "./Checkmate/ObjectModel/Fuel/FillUp";
import { FuelAndEnergyUsed } from "./Checkmate/ObjectModel/Fuel/FuelAndEnergyUsed";
import { FuelSnapshotRecord } from "./Checkmate/ObjectModel/Fuel/FuelSnapshotRecord";
import { FuelTransaction } from "./Checkmate/ObjectModel/Fuel/FuelTransaction";
import { FuelUpEvent } from "./Checkmate/ObjectModel/Fuel/FuelUpEvent";
import { FuelUsed } from "./Checkmate/ObjectModel/Fuel/FuelUsed";
import { PotentialFuelFraudEvent } from "./Checkmate/ObjectModel/Fuel/PotentialFuelFraud/PotentialFuelFraudEvent";
import { DashboardCache } from "./Checkmate/ObjectModel/Checkmate/Reports/DashboardCache";
import { DriverRegulationReprocessRequest } from "./Checkmate/ObjectModel/HOS/DriverRegulationReprocessRequest";
import { InstallRecord } from "./Checkmate/ObjectModel/InstallRecords/InstallRecord";
import { DiagnosticValueStatus } from "./Checkmate/ObjectModel/Maintenance/DiagnosticValueStatus";
import { DocumentScanning } from "./Checkmate/ObjectModel/Maintenance/DocumentScanning";
import { MaintenanceWorkOrder } from "./Checkmate/ObjectModel/Maintenance/MaintenanceWorkOrder";
import { MaintenanceWorkOrderJob } from "./Checkmate/ObjectModel/Maintenance/MaintenanceWorkOrderJob";
import { MaintenanceWorkRequest } from "./Checkmate/ObjectModel/Maintenance/MaintenanceWorkRequest";
import { BackfillStatus } from "./Checkmate/ObjectModel/Processing/BackfillStatus";
import { PushToken } from "./Checkmate/ObjectModel/PushNotifications/PushToken";
import { DeviceReprocessRequest } from "./Checkmate/ObjectModel/Reprocessing/DeviceReprocessRequest";
import { ReprocessRequest } from "./Checkmate/ObjectModel/Reprocessing/ReprocessRequest";
import { SustainabilityElectrificationSummary } from "./Checkmate/ObjectModel/Sustainability/SustainabilityElectrificationSummary";
import { SustainabilityGroupIdlingSummary } from "./Checkmate/ObjectModel/Sustainability/SustainabilityGroupIdlingSummary";
import { SustainabilityMonthlySummary } from "./Checkmate/ObjectModel/Sustainability/SustainabilityMonthlySummary";
import { TachographDriverActivity } from "./Checkmate/ObjectModel/Tachograph/TachographDriverActivity";
import { TachographDrivingTimeStatus } from "./Checkmate/ObjectModel/Tachograph/TachographDrivingTimeStatus";
import { TachographActivitiesCertificate } from "./Checkmate/ObjectModel/Tachograph/ActivitiesCertificates/TachographActivitiesCertificate";
import { TachographCompanyCard } from "./Checkmate/ObjectModel/Tachograph/CompanyCards/TachographCompanyCard";
import { TachographDataFile } from "./Checkmate/ObjectModel/Tachograph/Files/TachographDataFile";
import { TachographVehicleInspection } from "./Checkmate/ObjectModel/Tachograph/Inspections/TachographVehicleInspection";

export type EntityTypes = {
  AddIn: AddIn;
  AddInData: AddInData;
  AnnotationLog: AnnotationLog;
  AssetLink: AssetLink;
  AssetLinkDetails: AssetLinkDetails;
  AssetSeparationSubscription: AssetSeparationSubscription;
  Audit: Audit;
  BackfillStatus: BackfillStatus;
  BatteryStateOfHealth: BatteryStateOfHealth;
  BinaryData: BinaryData;
  Camera: Camera;
  CameraHealth: CameraHealth;
  CameraStatus: CameraStatus;
  Certificate: Certificate;
  ChargeEvent: ChargeEvent;
  CoachingSession: CoachingSession;
  ConsentStatus: ConsentStatus;
  ConsentStatusAudit: ConsentStatusAudit;
  Controller: Controller;
  CustomData: CustomData;
  CustomReportSchedule: CustomReportSchedule;
  DashboardCache: DashboardCache;
  DebugData: DebugData;
  Defect: Defect;
  DefectRemark: DefectRemark;
  Device: Device;
  DeviceCommunicationHistory: DeviceCommunicationHistory;
  DeviceCommunicationStatus: DeviceCommunicationStatus;
  DeviceLink: DeviceLink;
  DeviceMasterFlag: DeviceMasterFlag;
  DeviceRegistrationState: DeviceRegistrationState;
  DeviceReplacementInfo: DeviceReplacementInfo;
  DeviceReprocessRequest: DeviceReprocessRequest;
  DeviceShare: DeviceShare;
  DeviceStatusInfo: DeviceStatusInfo;
  Diagnostic: Diagnostic;
  DiagnosticData: DiagnosticData;
  DiagnosticLookupTable: DiagnosticLookupTable;
  DiagnosticMapping: DiagnosticMapping;
  DiagnosticValueStatus: DiagnosticValueStatus;
  DiscreteAvailabilitySnapshot: DiscreteAvailabilitySnapshot;
  DisplayMeasurementProfile: DisplayMeasurementProfile;
  DisplayMeasurementProfileDetail: DisplayMeasurementProfileDetail;
  DisplayUnitOfMeasure: DisplayUnitOfMeasure;
  DistributionList: DistributionList;
  DocumentScanning: DocumentScanning;
  DriverChange: DriverChange;
  DriverRegulation: DriverRegulation;
  DriverRegulationReprocessRequest: DriverRegulationReprocessRequest;
  DriverRegulationServiceScheduleInfo: DriverRegulationServiceScheduleInfo;
  DutyStatusAvailability: DutyStatusAvailability;
  DutyStatusLog: DutyStatusLog;
  DutyStatusViolation: DutyStatusViolation;
  DVIRDefect: DVIRDefect;
  DVIRLog: DVIRLog;
  ElectrificationAggregation: ElectrificationAggregation;
  EmissionComplianceEvent: EmissionComplianceEvent;
  EmissionReport: EmissionReport;
  EmissionServiceConnectionLog: EmissionServiceConnectionLog;
  EmissionVehicleCycle: EmissionVehicleCycle;
  EmissionVehicleCycleMessage: EmissionVehicleCycleMessage;
  EmissionVehicleEnrollment: EmissionVehicleEnrollment;
  EmployeeRoutePlan: EmployeeRoutePlan;
  EnergySnapshotRecord: EnergySnapshotRecord;
  EngineType: EngineType;
  EntityLinkRule: EntityLinkRule;
  EntitySetting: EntitySetting;
  EntityUploadRequest: EntityUploadRequest;
  EventDeviation: EventDeviation;
  EventOccurrence: EventOccurrence;
  EventOccurrenceDue: EventOccurrenceDue;
  EventType: EventType;
  EvsaConfiguration: EvsaConfiguration;
  EvsaRequest: EvsaRequest;
  EVStatusInfo: EVStatusInfo;
  ExceptionEvent: ExceptionEvent;
  ExceptionEventAttachment: ExceptionEventAttachment;
  ExceptionEventComment: ExceptionEventComment;
  ExceptionEventMediaLink: ExceptionEventMediaLink;
  FailureMode: FailureMode;
  FaultCycle: FaultCycle;
  FaultData: FaultData;
  FaultRichData: FaultRichData;
  Feedback: Feedback;
  FeedVersionTrackingData: FeedVersionTrackingData;
  FillUp: FillUp;
  FuelAndEnergySetting: FuelAndEnergySetting;
  FuelAndEnergyUsed: FuelAndEnergyUsed;
  FuelAndEnergyUsedAggregation: FuelAndEnergyUsedAggregation;
  FuelSnapshotRecord: FuelSnapshotRecord;
  FuelTaxDetail: FuelTaxDetail;
  FuelTransaction: FuelTransaction;
  FuelUpEvent: FuelUpEvent;
  FuelUsed: FuelUsed;
  Group: Group;
  GroupAddIn: GroupAddIn;
  GroupDevice: GroupDevice;
  GroupFilter: GroupFilter;
  GroupZoneMetadata: GroupZoneMetadata;
  HosRulesetConfig: HosRulesetConfig;
  HosStatusInfo: HosStatusInfo;
  IdlingExceptionAggregation: IdlingExceptionAggregation;
  IdlingFuelPercentageAggregation: IdlingFuelPercentageAggregation;
  InspectedItem: InspectedItem;
  InspectionLog: InspectionLog;
  InstallRecord: InstallRecord;
  Investigation: Investigation;
  InvestigationAttachment: InvestigationAttachment;
  InvestigationComment: InvestigationComment;
  IoxAddOn: IoxAddOn;
  IoxAddOnStatus: IoxAddOnStatus;
  IoxWorksConfigFileInfo: IoxWorksConfigFileInfo;
  LiveCompletionMapConfig: LiveCompletionMapConfig;
  LogRecord: LogRecord;
  LogRecordGeohash: LogRecordGeohash;
  LogRecordZoneDistance: LogRecordZoneDistance;
  LostModeChange: LostModeChange;
  MaintenanceNotificationRule: MaintenanceNotificationRule;
  MaintenanceNotificationState: MaintenanceNotificationState;
  MaintenanceSchedule: MaintenanceSchedule;
  MaintenanceWorkOrder: MaintenanceWorkOrder;
  MaintenanceWorkOrderJob: MaintenanceWorkOrderJob;
  MaintenanceWorkRequest: MaintenanceWorkRequest;
  MediaFile: MediaFile;
  MediaRequestNotification: MediaRequestNotification;
  MimeTask: MimeTask;
  Notification: Notification;
  Option: Option;
  ParameterGroup: ParameterGroup;
  PotentialFuelFraudEvent: PotentialFuelFraudEvent;
  Product: Product;
  Property: Property;
  PropertySet: PropertySet;
  PushToken: PushToken;
  QueuedEntityRemoveTask: QueuedEntityRemoveTask;
  RangeEstimate: RangeEstimate;
  Recipient: Recipient;
  ReportStorage: ReportStorage;
  ReportTag: ReportTag;
  ReportTemplate: ReportTemplate;
  ReprocessRequest: ReprocessRequest;
  RestrictedDataModeChange: RestrictedDataModeChange;
  Route: Route;
  RouteExtract: RouteExtract;
  Rule: Rule;
  SafetyDriverInsight: SafetyDriverInsight;
  SafetyFleetBenchmark: SafetyFleetBenchmark;
  SafetyFleetInsight: SafetyFleetInsight;
  SafetyVehicleInsight: SafetyVehicleInsight;
  SecurityId: SecurityId;
  ServiceState: ServiceState;
  ShareableLink: ShareableLink;
  ShipmentLog: ShipmentLog;
  Source: Source;
  StatusData: StatusData;
  SustainabilityElectrificationSummary: SustainabilityElectrificationSummary;
  SustainabilityGroupIdlingSummary: SustainabilityGroupIdlingSummary;
  SustainabilityMonthlySummary: SustainabilityMonthlySummary;
  TachographActivitiesCertificate: TachographActivitiesCertificate;
  TachographCompanyCard: TachographCompanyCard;
  TachographDataFile: TachographDataFile;
  TachographDriverActivity: TachographDriverActivity;
  TachographDrivingTimeStatus: TachographDrivingTimeStatus;
  TachographVehicleInspection: TachographVehicleInspection;
  TextMessage: TextMessage;
  Trailer: Trailer;
  TrailerAttachment: TrailerAttachment;
  Trip: Trip;
  TripAnnotation: TripAnnotation;
  TripGeohash: TripGeohash;
  TripTypeChange: TripTypeChange;
  UnitOfMeasure: UnitOfMeasure;
  UploadTransaction: UploadTransaction;
  User: User;
  UserDeviceLink: UserDeviceLink;
  UserDisplayProfile: UserDisplayProfile;
  UserHosRuleSet: UserHosRuleSet;
  UserLoginStatus: UserLoginStatus;
  UserSupport: UserSupport;
  VehicleDowntime: VehicleDowntime;
  WifiHotspot: WifiHotspot;
  WorkHoliday: WorkHoliday;
  WorkTime: WorkTime;
  Zone: Zone;
  ZoneMetadata: ZoneMetadata;
  ZoneType: ZoneType;
};
