import { AddInData } from "./Checkmate/ObjectModel/AddInData";
import { AnnotationLog } from "./Checkmate/ObjectModel/AnnotationLog";
import { Audit } from "./Checkmate/ObjectModel/Audit";
import { BinaryData } from "./Checkmate/ObjectModel/BinaryData";
import { Certificate } from "./Checkmate/ObjectModel/Certificate";
import { CustomData } from "./Checkmate/ObjectModel/CustomData";
import { Dashboard } from "./Checkmate/ObjectModel/Dashboard";
import { DebugData } from "./Checkmate/ObjectModel/DebugData";
import { Defect } from "./Checkmate/ObjectModel/Defect";
import { DefectRemark } from "./Checkmate/ObjectModel/DefectRemark";
import { Device } from "./Checkmate/ObjectModel/Device";
import { DeviceLink } from "./Checkmate/ObjectModel/DeviceLink";
import { DeviceMasterFlag } from "./Checkmate/ObjectModel/DeviceMasterFlag";
import { DeviceShare } from "./Checkmate/ObjectModel/DeviceShare";
import { DeviceStatusInfo } from "./Checkmate/ObjectModel/DeviceStatusInfo";
import { DistributionList } from "./Checkmate/ObjectModel/DistributionList";
import { DriverChange } from "./Checkmate/ObjectModel/DriverChange";
import { DriverRegulation } from "./Checkmate/ObjectModel/DriverRegulation";
import { DutyStatusAvailability } from "./Checkmate/ObjectModel/DutyStatusAvailability";
import { DutyStatusLog } from "./Checkmate/ObjectModel/DutyStatusLog";
import { DutyStatusViolation } from "./Checkmate/ObjectModel/DutyStatusViolation";
import { DVIRDefect } from "./Checkmate/ObjectModel/DVIRDefect";
import { DVIRLog } from "./Checkmate/ObjectModel/DVIRLog";
import { EmployeeRoutePlan } from "./Checkmate/ObjectModel/EmployeeRoutePlan";
import { EventDeviation } from "./Checkmate/ObjectModel/EventDeviation";
import { EventOccurrence } from "./Checkmate/ObjectModel/EventOccurrence";
import { EventOccurrenceDue } from "./Checkmate/ObjectModel/EventOccurrenceDue";
import { EventRule } from "./Checkmate/ObjectModel/EventRule";
import { FeedVersionTrackingData } from "./Checkmate/ObjectModel/FeedVersionTrackingData";
import { FuelTaxDetail } from "./Checkmate/ObjectModel/FuelTaxDetail";
import { Group } from "./Checkmate/ObjectModel/Group";
import { GroupDevice } from "./Checkmate/ObjectModel/GroupDevice";
import { GroupFilter } from "./Checkmate/ObjectModel/GroupFilter";
import { GroupZoneMetadata } from "./Checkmate/ObjectModel/GroupZoneMetadata";
import { HosRulesetConfig } from "./Checkmate/ObjectModel/HosRulesetConfig";
import { IoxAddOn } from "./Checkmate/ObjectModel/IoxAddOn";
import { IoxAddOnStatus } from "./Checkmate/ObjectModel/IoxAddOnStatus";
import { LiveCompletionMapConfig } from "./Checkmate/ObjectModel/LiveCompletionMapConfig";
import { LogRecord } from "./Checkmate/ObjectModel/LogRecord";
import { LogRecordZoneDistance } from "./Checkmate/ObjectModel/LogRecordZoneDistance";
import { MaintenanceNotificationRule } from "./Checkmate/ObjectModel/MaintenanceNotificationRule";
import { MaintenanceNotificationState } from "./Checkmate/ObjectModel/MaintenanceNotificationState";
import { MimeTask } from "./Checkmate/ObjectModel/MimeTask";
import { Notification } from "./Checkmate/ObjectModel/Notification";
import { Property } from "./Checkmate/ObjectModel/Property";
import { PropertySet } from "./Checkmate/ObjectModel/PropertySet";
import { Recipient } from "./Checkmate/ObjectModel/Recipient";
import { ReportStorage } from "./Checkmate/ObjectModel/ReportStorage";
import { ReportTemplate } from "./Checkmate/ObjectModel/ReportTemplate";
import { RestrictedDataModeChange } from "./Checkmate/ObjectModel/RestrictedDataModeChange";
import { Route } from "./Checkmate/ObjectModel/Route";
import { RouteExtract } from "./Checkmate/ObjectModel/RouteExtract";
import { SecurityId } from "./Checkmate/ObjectModel/SecurityId";
import { ServiceState } from "./Checkmate/ObjectModel/ServiceState";
import { ShareableLink } from "./Checkmate/ObjectModel/ShareableLink";
import { ShipmentLog } from "./Checkmate/ObjectModel/ShipmentLog";
import { TextMessage } from "./Checkmate/ObjectModel/TextMessage";
import { Trailer } from "./Checkmate/ObjectModel/Trailer";
import { TrailerAttachment } from "./Checkmate/ObjectModel/TrailerAttachment";
import { Trip } from "./Checkmate/ObjectModel/Trip";
import { TripAnnotation } from "./Checkmate/ObjectModel/TripAnnotation";
import { TripGeohash } from "./Checkmate/ObjectModel/TripGeohash";
import { TripTypeChange } from "./Checkmate/ObjectModel/TripTypeChange";
import { User } from "./Checkmate/ObjectModel/User";
import { UserDeviceLink } from "./Checkmate/ObjectModel/UserDeviceLink";
import { UserHosRuleSet } from "./Checkmate/ObjectModel/UserHosRuleSet";
import { UserLoginStatus } from "./Checkmate/ObjectModel/UserLoginStatus";
import { UserSupport } from "./Checkmate/ObjectModel/UserSupport";
import { Widget } from "./Checkmate/ObjectModel/Widget";
import { WifiHotspot } from "./Checkmate/ObjectModel/WifiHotspot";
import { WorkHoliday } from "./Checkmate/ObjectModel/WorkHoliday";
import { WorkTime } from "./Checkmate/ObjectModel/WorkTime";
import { Zone } from "./Checkmate/ObjectModel/Zone";
import { ZoneType } from "./Checkmate/ObjectModel/ZoneType";
import { AddIn } from "./Checkmate/ObjectModel/AddIns/AddIn";
import { ChargeEvent } from "./Checkmate/ObjectModel/Charging/ChargeEvent";
import { DeviceRegistrationState } from "./Checkmate/ObjectModel/DeviceRegistration/DeviceRegistrationState";
import { DeviceReplacementInfo } from "./Checkmate/ObjectModel/DeviceReplacement/DeviceReplacementInfo";
import { EnergySnapshotRecord } from "./Checkmate/ObjectModel/Energy/EnergySnapshotRecord";
import { Controller } from "./Checkmate/ObjectModel/Engine/Controller";
import { Diagnostic } from "./Checkmate/ObjectModel/Engine/Diagnostic";
import { DiagnosticMapping } from "./Checkmate/ObjectModel/Engine/DiagnosticMapping";
import { EngineType } from "./Checkmate/ObjectModel/Engine/EngineType";
import { FailureMode } from "./Checkmate/ObjectModel/Engine/FailureMode";
import { FaultData } from "./Checkmate/ObjectModel/Engine/FaultData";
import { ParameterGroup } from "./Checkmate/ObjectModel/Engine/ParameterGroup";
import { Source } from "./Checkmate/ObjectModel/Engine/Source";
import { StatusData } from "./Checkmate/ObjectModel/Engine/StatusData";
import { UnitOfMeasure } from "./Checkmate/ObjectModel/Engine/UnitOfMeasure";
import { DisplayMeasurementProfile } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfile";
import { DisplayMeasurementProfileDetail } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileDetail";
import { DisplayUnitOfMeasure } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayUnitOfMeasure";
import { UserDisplayProfile } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/UserDisplayProfile";
import { EntityLinkRule } from "./Checkmate/ObjectModel/EntityLink/EntityLinkRule";
import { EntitySetting } from "./Checkmate/ObjectModel/EntitySettings/EntitySetting";
import { ExceptionEvent } from "./Checkmate/ObjectModel/Exceptions/ExceptionEvent";
import { ExceptionEventAttachment } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventAttachment";
import { ExceptionEventComment } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventComment";
import { Rule } from "./Checkmate/ObjectModel/Exceptions/Rule";
import { VirtualExceptionEvent } from "./Checkmate/ObjectModel/Exceptions/VirtualExceptionEvent";
import { MediaFile } from "./Checkmate/ObjectModel/Files/MediaFile";
import { FillUp } from "./Checkmate/ObjectModel/Fuel/FillUp";
import { FuelSnapshotRecord } from "./Checkmate/ObjectModel/Fuel/FuelSnapshotRecord";
import { FuelTransaction } from "./Checkmate/ObjectModel/Fuel/FuelTransaction";
import { FuelUpEvent } from "./Checkmate/ObjectModel/Fuel/FuelUpEvent";
import { FuelUsed } from "./Checkmate/ObjectModel/Fuel/FuelUsed";
import { InstallRecord } from "./Checkmate/ObjectModel/InstallRecords/InstallRecord";
import { BackfillStatus } from "./Checkmate/ObjectModel/Processing/BackfillStatus";
import { DeviceReprocessRequest } from "./Checkmate/ObjectModel/Reprocessing/DeviceReprocessRequest";
import { TachographActivitiesCertificate } from "./Checkmate/ObjectModel/Tachograph/ActivitiesCertificates/TachographActivitiesCertificate";
import { TachographCompanyCard } from "./Checkmate/ObjectModel/Tachograph/CompanyCards/TachographCompanyCard";
import { TachographDataFile } from "./Checkmate/ObjectModel/Tachograph/Files/TachographDataFile";
import { TachographVehicleInspection } from "./Checkmate/ObjectModel/Tachograph/Inspections/TachographVehicleInspection";

export type EntityTypes = {
  AddIn: AddIn;
  AddInData: AddInData;
  AnnotationLog: AnnotationLog;
  Audit: Audit;
  BackfillStatus: BackfillStatus;
  BinaryData: BinaryData;
  Certificate: Certificate;
  ChargeEvent: ChargeEvent;
  Controller: Controller;
  CustomData: CustomData;
  Dashboard: Dashboard;
  DebugData: DebugData;
  Defect: Defect;
  DefectRemark: DefectRemark;
  Device: Device;
  DeviceLink: DeviceLink;
  DeviceMasterFlag: DeviceMasterFlag;
  DeviceRegistrationState: DeviceRegistrationState;
  DeviceReplacementInfo: DeviceReplacementInfo;
  DeviceReprocessRequest: DeviceReprocessRequest;
  DeviceShare: DeviceShare;
  DeviceStatusInfo: DeviceStatusInfo;
  Diagnostic: Diagnostic;
  DiagnosticMapping: DiagnosticMapping;
  DisplayMeasurementProfile: DisplayMeasurementProfile;
  DisplayMeasurementProfileDetail: DisplayMeasurementProfileDetail;
  DisplayUnitOfMeasure: DisplayUnitOfMeasure;
  DistributionList: DistributionList;
  DriverChange: DriverChange;
  DriverRegulation: DriverRegulation;
  DutyStatusAvailability: DutyStatusAvailability;
  DutyStatusLog: DutyStatusLog;
  DutyStatusViolation: DutyStatusViolation;
  DVIRDefect: DVIRDefect;
  DVIRLog: DVIRLog;
  EmployeeRoutePlan: EmployeeRoutePlan;
  EnergySnapshotRecord: EnergySnapshotRecord;
  EngineType: EngineType;
  EntityLinkRule: EntityLinkRule;
  EntitySetting: EntitySetting;
  EventDeviation: EventDeviation;
  EventOccurrence: EventOccurrence;
  EventOccurrenceDue: EventOccurrenceDue;
  EventRule: EventRule;
  ExceptionEvent: ExceptionEvent;
  ExceptionEventAttachment: ExceptionEventAttachment;
  ExceptionEventComment: ExceptionEventComment;
  FailureMode: FailureMode;
  FaultData: FaultData;
  FeedVersionTrackingData: FeedVersionTrackingData;
  FillUp: FillUp;
  FuelSnapshotRecord: FuelSnapshotRecord;
  FuelTaxDetail: FuelTaxDetail;
  FuelTransaction: FuelTransaction;
  FuelUpEvent: FuelUpEvent;
  FuelUsed: FuelUsed;
  Group: Group;
  GroupDevice: GroupDevice;
  GroupFilter: GroupFilter;
  GroupZoneMetadata: GroupZoneMetadata;
  HosRulesetConfig: HosRulesetConfig;
  InstallRecord: InstallRecord;
  IoxAddOn: IoxAddOn;
  IoxAddOnStatus: IoxAddOnStatus;
  LiveCompletionMapConfig: LiveCompletionMapConfig;
  LogRecord: LogRecord;
  LogRecordZoneDistance: LogRecordZoneDistance;
  MaintenanceNotificationRule: MaintenanceNotificationRule;
  MaintenanceNotificationState: MaintenanceNotificationState;
  MediaFile: MediaFile;
  MimeTask: MimeTask;
  Notification: Notification;
  ParameterGroup: ParameterGroup;
  Property: Property;
  PropertySet: PropertySet;
  Recipient: Recipient;
  ReportStorage: ReportStorage;
  ReportTemplate: ReportTemplate;
  RestrictedDataModeChange: RestrictedDataModeChange;
  Route: Route;
  RouteExtract: RouteExtract;
  Rule: Rule;
  SecurityId: SecurityId;
  ServiceState: ServiceState;
  ShareableLink: ShareableLink;
  ShipmentLog: ShipmentLog;
  Source: Source;
  StatusData: StatusData;
  TachographActivitiesCertificate: TachographActivitiesCertificate;
  TachographCompanyCard: TachographCompanyCard;
  TachographDataFile: TachographDataFile;
  TachographVehicleInspection: TachographVehicleInspection;
  TextMessage: TextMessage;
  Trailer: Trailer;
  TrailerAttachment: TrailerAttachment;
  Trip: Trip;
  TripAnnotation: TripAnnotation;
  TripGeohash: TripGeohash;
  TripTypeChange: TripTypeChange;
  UnitOfMeasure: UnitOfMeasure;
  User: User;
  UserDeviceLink: UserDeviceLink;
  UserDisplayProfile: UserDisplayProfile;
  UserHosRuleSet: UserHosRuleSet;
  UserLoginStatus: UserLoginStatus;
  UserSupport: UserSupport;
  VirtualExceptionEvent: VirtualExceptionEvent;
  Widget: Widget;
  WifiHotspot: WifiHotspot;
  WorkHoliday: WorkHoliday;
  WorkTime: WorkTime;
  Zone: Zone;
  ZoneType: ZoneType;
};
