import { AddInDataSearch } from "./Checkmate/ObjectModel/AddInDataSearch";
import { AnnotationLogSearch } from "./Checkmate/ObjectModel/AnnotationLogSearch";
import { AuditSearch } from "./Checkmate/ObjectModel/AuditSearch";
import { BinaryDataSearch } from "./Checkmate/ObjectModel/BinaryDataSearch";
import { CertificateSearch } from "./Checkmate/ObjectModel/CertificateSearch";
import { CustomDataSearch } from "./Checkmate/ObjectModel/CustomDataSearch";
import { DashboardSearch } from "./Checkmate/ObjectModel/DashboardSearch";
import { DebugDataSearch } from "./Checkmate/ObjectModel/DebugDataSearch";
import { DefectRemarkSearch } from "./Checkmate/ObjectModel/DefectRemarkSearch";
import { DefectSearch } from "./Checkmate/ObjectModel/DefectSearch";
import { DeviceLinkSearch } from "./Checkmate/ObjectModel/DeviceLinkSearch";
import { DeviceMasterFlagSearch } from "./Checkmate/ObjectModel/DeviceMasterFlagSearch";
import { DeviceSearch } from "./Checkmate/ObjectModel/DeviceSearch";
import { DeviceShareSearch } from "./Checkmate/ObjectModel/DeviceShareSearch";
import { DeviceStatusInfoSearch } from "./Checkmate/ObjectModel/DeviceStatusInfoSearch";
import { DistributionListSearch } from "./Checkmate/ObjectModel/DistributionListSearch";
import { DriverChangeSearch } from "./Checkmate/ObjectModel/DriverChangeSearch";
import { DriverRegulationSearch } from "./Checkmate/ObjectModel/DriverRegulationSearch";
import { DutyStatusAvailabilitySearch } from "./Checkmate/ObjectModel/DutyStatusAvailabilitySearch";
import { DutyStatusLogSearch } from "./Checkmate/ObjectModel/DutyStatusLogSearch";
import { DutyStatusViolationSearch } from "./Checkmate/ObjectModel/DutyStatusViolationSearch";
import { DVIRDefectSearch } from "./Checkmate/ObjectModel/DVIRDefectSearch";
import { DVIRLogSearch } from "./Checkmate/ObjectModel/DVIRLogSearch";
import { EmployeeRoutePlanSearch } from "./Checkmate/ObjectModel/EmployeeRoutePlanSearch";
import { EventDeviationSearch } from "./Checkmate/ObjectModel/EventDeviationSearch";
import { EventOccurrenceDueSearch } from "./Checkmate/ObjectModel/EventOccurrenceDueSearch";
import { EventOccurrenceSearch } from "./Checkmate/ObjectModel/EventOccurrenceSearch";
import { EventRuleSearch } from "./Checkmate/ObjectModel/EventRuleSearch";
import { FeedVersionTrackingDataSearch } from "./Checkmate/ObjectModel/FeedVersionTrackingDataSearch";
import { FuelTaxDetailSearch } from "./Checkmate/ObjectModel/FuelTaxDetailSearch";
import { GroupDeviceSearch } from "./Checkmate/ObjectModel/GroupDeviceSearch";
import { GroupFilterSearch } from "./Checkmate/ObjectModel/GroupFilterSearch";
import { GroupSearch } from "./Checkmate/ObjectModel/GroupSearch";
import { GroupZoneMetadataSearch } from "./Checkmate/ObjectModel/GroupZoneMetadataSearch";
import { HosRulesetConfigSearch } from "./Checkmate/ObjectModel/HosRulesetConfigSearch";
import { IoxAddOnSearch } from "./Checkmate/ObjectModel/IoxAddOnSearch";
import { IoxAddOnStatusSearch } from "./Checkmate/ObjectModel/IoxAddOnStatusSearch";
import { LiveCompletionMapConfigSearch } from "./Checkmate/ObjectModel/LiveCompletionMapConfigSearch";
import { LogRecordSearch } from "./Checkmate/ObjectModel/LogRecordSearch";
import { LogRecordZoneDistanceSearch } from "./Checkmate/ObjectModel/LogRecordZoneDistanceSearch";
import { MaintenanceNotificationRuleSearch } from "./Checkmate/ObjectModel/MaintenanceNotificationRuleSearch";
import { MaintenanceNotificationStateSearch } from "./Checkmate/ObjectModel/MaintenanceNotificationStateSearch";
import { MimeTaskSearch } from "./Checkmate/ObjectModel/MimeTaskSearch";
import { NotificationSearch } from "./Checkmate/ObjectModel/NotificationSearch";
import { PropertySearch } from "./Checkmate/ObjectModel/PropertySearch";
import { PropertySetSearch } from "./Checkmate/ObjectModel/PropertySetSearch";
import { RecipientSearch } from "./Checkmate/ObjectModel/RecipientSearch";
import { ReportStorageSearch } from "./Checkmate/ObjectModel/ReportStorageSearch";
import { ReportTemplateSearch } from "./Checkmate/ObjectModel/ReportTemplateSearch";
import { RestrictedDataModeChangeSearch } from "./Checkmate/ObjectModel/RestrictedDataModeChangeSearch";
import { RouteExtractSearch } from "./Checkmate/ObjectModel/RouteExtractSearch";
import { RouteSearch } from "./Checkmate/ObjectModel/RouteSearch";
import { SecurityIdSearch } from "./Checkmate/ObjectModel/SecurityIdSearch";
import { ServiceStateSearch } from "./Checkmate/ObjectModel/ServiceStateSearch";
import { ShareableLinkSearch } from "./Checkmate/ObjectModel/ShareableLinkSearch";
import { ShipmentLogSearch } from "./Checkmate/ObjectModel/ShipmentLogSearch";
import { TextMessageSearch } from "./Checkmate/ObjectModel/TextMessageSearch";
import { TrailerAttachmentSearch } from "./Checkmate/ObjectModel/TrailerAttachmentSearch";
import { TrailerSearch } from "./Checkmate/ObjectModel/TrailerSearch";
import { TripAnnotationSearch } from "./Checkmate/ObjectModel/TripAnnotationSearch";
import { TripGeohashSearch } from "./Checkmate/ObjectModel/TripGeohashSearch";
import { TripSearch } from "./Checkmate/ObjectModel/TripSearch";
import { TripTypeChangeSearch } from "./Checkmate/ObjectModel/TripTypeChangeSearch";
import { UserDeviceLinkSearch } from "./Checkmate/ObjectModel/UserDeviceLinkSearch";
import { UserHosRuleSetSearch } from "./Checkmate/ObjectModel/UserHosRuleSetSearch";
import { UserLoginStatusSearch } from "./Checkmate/ObjectModel/UserLoginStatusSearch";
import { UserSearch } from "./Checkmate/ObjectModel/UserSearch";
import { UserSupportSearch } from "./Checkmate/ObjectModel/UserSupportSearch";
import { WidgetSearch } from "./Checkmate/ObjectModel/WidgetSearch";
import { WifiHotspotSearch } from "./Checkmate/ObjectModel/WifiHotspotSearch";
import { WorkHolidaySearch } from "./Checkmate/ObjectModel/WorkHolidaySearch";
import { WorkTimeSearch } from "./Checkmate/ObjectModel/WorkTimeSearch";
import { ZoneSearch } from "./Checkmate/ObjectModel/ZoneSearch";
import { ZoneTypeSearch } from "./Checkmate/ObjectModel/ZoneTypeSearch";
import { AddInSearch } from "./Checkmate/ObjectModel/AddIns/AddInSearch";
import { ChargeEventSearch } from "./Checkmate/ObjectModel/Charging/ChargeEventSearch";
import { DeviceRegistrationStateSearch } from "./Checkmate/ObjectModel/DeviceRegistration/DeviceRegistrationStateSearch";
import { DeviceReplacementInfoSearch } from "./Checkmate/ObjectModel/DeviceReplacement/DeviceReplacementInfoSearch";
import { EnergySnapshotRecordSearch } from "./Checkmate/ObjectModel/Energy/EnergySnapshotRecordSearch";
import { ControllerSearch } from "./Checkmate/ObjectModel/Engine/ControllerSearch";
import { DiagnosticMappingSearch } from "./Checkmate/ObjectModel/Engine/DiagnosticMappingSearch";
import { DiagnosticSearch } from "./Checkmate/ObjectModel/Engine/DiagnosticSearch";
import { EngineTypeSearch } from "./Checkmate/ObjectModel/Engine/EngineTypeSearch";
import { FailureModeSearch } from "./Checkmate/ObjectModel/Engine/FailureModeSearch";
import { FaultDataSearch } from "./Checkmate/ObjectModel/Engine/FaultDataSearch";
import { ParameterGroupSearch } from "./Checkmate/ObjectModel/Engine/ParameterGroupSearch";
import { SourceSearch } from "./Checkmate/ObjectModel/Engine/SourceSearch";
import { StatusDataSearch } from "./Checkmate/ObjectModel/Engine/StatusDataSearch";
import { UnitOfMeasureSearch } from "./Checkmate/ObjectModel/Engine/UnitOfMeasureSearch";
import { DisplayMeasurementProfileDetailSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileDetailSearch";
import { DisplayMeasurementProfileSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileSearch";
import { DisplayUnitOfMeasureSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayUnitOfMeasureSearch";
import { UserDisplayProfileSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/UserDisplayProfileSearch";
import { EntityLinkRuleSearch } from "./Checkmate/ObjectModel/EntityLink/EntityLinkRuleSearch";
import { EntitySettingSearch } from "./Checkmate/ObjectModel/EntitySettings/EntitySettingSearch";
import { ExceptionEventAttachmentSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventAttachmentSearch";
import { ExceptionEventCommentSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventCommentSearch";
import { ExceptionEventSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventSearch";
import { RuleSearch } from "./Checkmate/ObjectModel/Exceptions/RuleSearch";
import { VirtualExceptionEventSearch } from "./Checkmate/ObjectModel/Exceptions/VirtualExceptionEventSearch";
import { MediaFileSearch } from "./Checkmate/ObjectModel/Files/MediaFileSearch";
import { FillUpSearch } from "./Checkmate/ObjectModel/Fuel/FillUpSearch";
import { FuelSnapshotRecordSearch } from "./Checkmate/ObjectModel/Fuel/FuelSnapshotRecordSearch";
import { FuelTransactionSearch } from "./Checkmate/ObjectModel/Fuel/FuelTransactionSearch";
import { FuelUpEventSearch } from "./Checkmate/ObjectModel/Fuel/FuelUpEventSearch";
import { FuelUsedSearch } from "./Checkmate/ObjectModel/Fuel/FuelUsedSearch";
import { InstallRecordSearch } from "./Checkmate/ObjectModel/InstallRecords/InstallRecordSearch";
import { BackfillStatusSearch } from "./Checkmate/ObjectModel/Processing/BackfillStatusSearch";
import { DeviceReprocessRequestSearch } from "./Checkmate/ObjectModel/Reprocessing/DeviceReprocessRequestSearch";
import { TachographActivitiesCertificateSearch } from "./Checkmate/ObjectModel/Tachograph/ActivitiesCertificates/TachographActivitiesCertificateSearch";
import { TachographCompanyCardSearch } from "./Checkmate/ObjectModel/Tachograph/CompanyCards/TachographCompanyCardSearch";
import { TachographDataFileSearch } from "./Checkmate/ObjectModel/Tachograph/Files/TachographDataFileSearch";
import { TachographVehicleInspectionSearch } from "./Checkmate/ObjectModel/Tachograph/Inspections/TachographVehicleInspectionSearch";

export type SearchTypes = {
  AddInData: AddInDataSearch;
  AddIn: AddInSearch;
  AnnotationLog: AnnotationLogSearch;
  Audit: AuditSearch;
  BackfillStatus: BackfillStatusSearch;
  BinaryData: BinaryDataSearch;
  Certificate: CertificateSearch;
  ChargeEvent: ChargeEventSearch;
  Controller: ControllerSearch;
  CustomData: CustomDataSearch;
  Dashboard: DashboardSearch;
  DebugData: DebugDataSearch;
  DefectRemark: DefectRemarkSearch;
  Defect: DefectSearch;
  DeviceLink: DeviceLinkSearch;
  DeviceMasterFlag: DeviceMasterFlagSearch;
  DeviceRegistrationState: DeviceRegistrationStateSearch;
  DeviceReplacementInfo: DeviceReplacementInfoSearch;
  DeviceReprocessRequest: DeviceReprocessRequestSearch;
  Device: DeviceSearch;
  DeviceShare: DeviceShareSearch;
  DeviceStatusInfo: DeviceStatusInfoSearch;
  DiagnosticMapping: DiagnosticMappingSearch;
  Diagnostic: DiagnosticSearch;
  DisplayMeasurementProfileDetail: DisplayMeasurementProfileDetailSearch;
  DisplayMeasurementProfile: DisplayMeasurementProfileSearch;
  DisplayUnitOfMeasure: DisplayUnitOfMeasureSearch;
  DistributionList: DistributionListSearch;
  DriverChange: DriverChangeSearch;
  DriverRegulation: DriverRegulationSearch;
  DutyStatusAvailability: DutyStatusAvailabilitySearch;
  DutyStatusLog: DutyStatusLogSearch;
  DutyStatusViolation: DutyStatusViolationSearch;
  DVIRDefect: DVIRDefectSearch;
  DVIRLog: DVIRLogSearch;
  EmployeeRoutePlan: EmployeeRoutePlanSearch;
  EnergySnapshotRecord: EnergySnapshotRecordSearch;
  EngineType: EngineTypeSearch;
  EntityLinkRule: EntityLinkRuleSearch;
  EntitySetting: EntitySettingSearch;
  EventDeviation: EventDeviationSearch;
  EventOccurrenceDue: EventOccurrenceDueSearch;
  EventOccurrence: EventOccurrenceSearch;
  EventRule: EventRuleSearch;
  ExceptionEventAttachment: ExceptionEventAttachmentSearch;
  ExceptionEventComment: ExceptionEventCommentSearch;
  ExceptionEvent: ExceptionEventSearch;
  FailureMode: FailureModeSearch;
  FaultData: FaultDataSearch;
  FeedVersionTrackingData: FeedVersionTrackingDataSearch;
  FillUp: FillUpSearch;
  FuelSnapshotRecord: FuelSnapshotRecordSearch;
  FuelTaxDetail: FuelTaxDetailSearch;
  FuelTransaction: FuelTransactionSearch;
  FuelUpEvent: FuelUpEventSearch;
  FuelUsed: FuelUsedSearch;
  GroupDevice: GroupDeviceSearch;
  GroupFilter: GroupFilterSearch;
  Group: GroupSearch;
  GroupZoneMetadata: GroupZoneMetadataSearch;
  HosRulesetConfig: HosRulesetConfigSearch;
  InstallRecord: InstallRecordSearch;
  IoxAddOn: IoxAddOnSearch;
  IoxAddOnStatus: IoxAddOnStatusSearch;
  LiveCompletionMapConfig: LiveCompletionMapConfigSearch;
  LogRecord: LogRecordSearch;
  LogRecordZoneDistance: LogRecordZoneDistanceSearch;
  MaintenanceNotificationRule: MaintenanceNotificationRuleSearch;
  MaintenanceNotificationState: MaintenanceNotificationStateSearch;
  MediaFile: MediaFileSearch;
  MimeTask: MimeTaskSearch;
  Notification: NotificationSearch;
  ParameterGroup: ParameterGroupSearch;
  Property: PropertySearch;
  PropertySet: PropertySetSearch;
  Recipient: RecipientSearch;
  ReportStorage: ReportStorageSearch;
  ReportTemplate: ReportTemplateSearch;
  RestrictedDataModeChange: RestrictedDataModeChangeSearch;
  RouteExtract: RouteExtractSearch;
  Route: RouteSearch;
  Rule: RuleSearch;
  SecurityId: SecurityIdSearch;
  ServiceState: ServiceStateSearch;
  ShareableLink: ShareableLinkSearch;
  ShipmentLog: ShipmentLogSearch;
  Source: SourceSearch;
  StatusData: StatusDataSearch;
  TachographActivitiesCertificate: TachographActivitiesCertificateSearch;
  TachographCompanyCard: TachographCompanyCardSearch;
  TachographDataFile: TachographDataFileSearch;
  TachographVehicleInspection: TachographVehicleInspectionSearch;
  TextMessage: TextMessageSearch;
  TrailerAttachment: TrailerAttachmentSearch;
  Trailer: TrailerSearch;
  TripAnnotation: TripAnnotationSearch;
  TripGeohash: TripGeohashSearch;
  Trip: TripSearch;
  TripTypeChange: TripTypeChangeSearch;
  UnitOfMeasure: UnitOfMeasureSearch;
  UserDeviceLink: UserDeviceLinkSearch;
  UserDisplayProfile: UserDisplayProfileSearch;
  UserHosRuleSet: UserHosRuleSetSearch;
  UserLoginStatus: UserLoginStatusSearch;
  User: UserSearch;
  UserSupport: UserSupportSearch;
  VirtualExceptionEvent: VirtualExceptionEventSearch;
  Widget: WidgetSearch;
  WifiHotspot: WifiHotspotSearch;
  WorkHoliday: WorkHolidaySearch;
  WorkTime: WorkTimeSearch;
  Zone: ZoneSearch;
  ZoneType: ZoneTypeSearch;
};
