import { AddInDataSearch } from "./Checkmate/ObjectModel/AddInDataSearch";
import { AnnotationLogSearch } from "./Checkmate/ObjectModel/AnnotationLogSearch";
import { AssetLinkDetailsSearch } from "./Checkmate/ObjectModel/AssetLinkDetailsSearch";
import { AssetLinkSearch } from "./Checkmate/ObjectModel/AssetLinkSearch";
import { AssetSeparationSubscriptionSearch } from "./Checkmate/ObjectModel/AssetSeparationSubscriptionSearch";
import { AuditSearch } from "./Checkmate/ObjectModel/AuditSearch";
import { BatteryStateOfHealthSearch } from "./Checkmate/ObjectModel/BatteryStateOfHealthSearch";
import { BinaryDataSearch } from "./Checkmate/ObjectModel/BinaryDataSearch";
import { CameraHealthSearch } from "./Checkmate/ObjectModel/CameraHealthSearch";
import { CameraSearch } from "./Checkmate/ObjectModel/CameraSearch";
import { CameraStatusSearch } from "./Checkmate/ObjectModel/CameraStatusSearch";
import { CertificateSearch } from "./Checkmate/ObjectModel/CertificateSearch";
import { CoachingSessionSearch } from "./Checkmate/ObjectModel/CoachingSessionSearch";
import { CustomDataSearch } from "./Checkmate/ObjectModel/CustomDataSearch";
import { CustomReportScheduleSearch } from "./Checkmate/ObjectModel/CustomReportScheduleSearch";
import { DebugDataSearch } from "./Checkmate/ObjectModel/DebugDataSearch";
import { DefectRemarkSearch } from "./Checkmate/ObjectModel/DefectRemarkSearch";
import { DefectSearch } from "./Checkmate/ObjectModel/DefectSearch";
import { DeviceCommunicationHistorySearch } from "./Checkmate/ObjectModel/DeviceCommunicationHistorySearch";
import { DeviceCommunicationStatusSearch } from "./Checkmate/ObjectModel/DeviceCommunicationStatusSearch";
import { DeviceLinkSearch } from "./Checkmate/ObjectModel/DeviceLinkSearch";
import { DeviceMasterFlagSearch } from "./Checkmate/ObjectModel/DeviceMasterFlagSearch";
import { DeviceSearch } from "./Checkmate/ObjectModel/DeviceSearch";
import { DeviceShareSearch } from "./Checkmate/ObjectModel/DeviceShareSearch";
import { DeviceStatusInfoSearch } from "./Checkmate/ObjectModel/DeviceStatusInfoSearch";
import { DiscreteAvailabilitySnapshotSearch } from "./Checkmate/ObjectModel/DiscreteAvailabilitySnapshotSearch";
import { DistributionListSearch } from "./Checkmate/ObjectModel/DistributionListSearch";
import { DriverChangeSearch } from "./Checkmate/ObjectModel/DriverChangeSearch";
import { DriverRegulationSearch } from "./Checkmate/ObjectModel/DriverRegulationSearch";
import { DriverRegulationServiceScheduleInfoSearch } from "./Checkmate/ObjectModel/DriverRegulationServiceScheduleInfoSearch";
import { DutyStatusAvailabilitySearch } from "./Checkmate/ObjectModel/DutyStatusAvailabilitySearch";
import { DutyStatusLogSearch } from "./Checkmate/ObjectModel/DutyStatusLogSearch";
import { DutyStatusViolationSearch } from "./Checkmate/ObjectModel/DutyStatusViolationSearch";
import { DVIRDefectSearch } from "./Checkmate/ObjectModel/DVIRDefectSearch";
import { DVIRLogSearch } from "./Checkmate/ObjectModel/DVIRLogSearch";
import { ElectrificationAggregationSearch } from "./Checkmate/ObjectModel/ElectrificationAggregationSearch";
import { EmployeeRoutePlanSearch } from "./Checkmate/ObjectModel/EmployeeRoutePlanSearch";
import { EntityUploadRequestSearch } from "./Checkmate/ObjectModel/EntityUploadRequestSearch";
import { EventDeviationSearch } from "./Checkmate/ObjectModel/EventDeviationSearch";
import { EventOccurrenceDueSearch } from "./Checkmate/ObjectModel/EventOccurrenceDueSearch";
import { EventOccurrenceSearch } from "./Checkmate/ObjectModel/EventOccurrenceSearch";
import { EventTypeSearch } from "./Checkmate/ObjectModel/EventTypeSearch";
import { ExceptionEventMediaLinkSearch } from "./Checkmate/ObjectModel/ExceptionEventMediaLinkSearch";
import { FaultCycleSearch } from "./Checkmate/ObjectModel/FaultCycleSearch";
import { FaultRichDataSearch } from "./Checkmate/ObjectModel/FaultRichDataSearch";
import { FeedbackSearch } from "./Checkmate/ObjectModel/FeedbackSearch";
import { FeedVersionTrackingDataSearch } from "./Checkmate/ObjectModel/FeedVersionTrackingDataSearch";
import { FuelAndEnergySettingSearch } from "./Checkmate/ObjectModel/FuelAndEnergySettingSearch";
import { FuelAndEnergyUsedAggregationSearch } from "./Checkmate/ObjectModel/FuelAndEnergyUsedAggregationSearch";
import { FuelTaxDetailSearch } from "./Checkmate/ObjectModel/FuelTaxDetailSearch";
import { GroupAddInSearch } from "./Checkmate/ObjectModel/GroupAddInSearch";
import { GroupDeviceSearch } from "./Checkmate/ObjectModel/GroupDeviceSearch";
import { GroupFilterSearch } from "./Checkmate/ObjectModel/GroupFilterSearch";
import { GroupSearch } from "./Checkmate/ObjectModel/GroupSearch";
import { GroupZoneMetadataSearch } from "./Checkmate/ObjectModel/GroupZoneMetadataSearch";
import { HosRulesetConfigSearch } from "./Checkmate/ObjectModel/HosRulesetConfigSearch";
import { HosStatusInfoSearch } from "./Checkmate/ObjectModel/HosStatusInfoSearch";
import { IdlingExceptionAggregationSearch } from "./Checkmate/ObjectModel/IdlingExceptionAggregationSearch";
import { IdlingFuelPercentageAggregationSearch } from "./Checkmate/ObjectModel/IdlingFuelPercentageAggregationSearch";
import { InspectedItemSearch } from "./Checkmate/ObjectModel/InspectedItemSearch";
import { InspectionLogSearch } from "./Checkmate/ObjectModel/InspectionLogSearch";
import { InvestigationAttachmentSearch } from "./Checkmate/ObjectModel/InvestigationAttachmentSearch";
import { InvestigationCommentSearch } from "./Checkmate/ObjectModel/InvestigationCommentSearch";
import { InvestigationSearch } from "./Checkmate/ObjectModel/InvestigationSearch";
import { IoxAddOnSearch } from "./Checkmate/ObjectModel/IoxAddOnSearch";
import { IoxAddOnStatusSearch } from "./Checkmate/ObjectModel/IoxAddOnStatusSearch";
import { IoxWorksConfigFileInfoSearch } from "./Checkmate/ObjectModel/IoxWorksConfigFileInfoSearch";
import { LiveCompletionMapConfigSearch } from "./Checkmate/ObjectModel/LiveCompletionMapConfigSearch";
import { LogRecordGeohashSearch } from "./Checkmate/ObjectModel/LogRecordGeohashSearch";
import { LogRecordSearch } from "./Checkmate/ObjectModel/LogRecordSearch";
import { LogRecordZoneDistanceSearch } from "./Checkmate/ObjectModel/LogRecordZoneDistanceSearch";
import { LostModeChangeSearch } from "./Checkmate/ObjectModel/LostModeChangeSearch";
import { MaintenanceNotificationRuleSearch } from "./Checkmate/ObjectModel/MaintenanceNotificationRuleSearch";
import { MaintenanceNotificationStateSearch } from "./Checkmate/ObjectModel/MaintenanceNotificationStateSearch";
import { MaintenanceScheduleSearch } from "./Checkmate/ObjectModel/MaintenanceScheduleSearch";
import { MediaRequestNotificationSearch } from "./Checkmate/ObjectModel/MediaRequestNotificationSearch";
import { MimeTaskSearch } from "./Checkmate/ObjectModel/MimeTaskSearch";
import { NotificationSearch } from "./Checkmate/ObjectModel/NotificationSearch";
import { PropertySearch } from "./Checkmate/ObjectModel/PropertySearch";
import { PropertySetSearch } from "./Checkmate/ObjectModel/PropertySetSearch";
import { QueuedEntityRemoveTaskSearch } from "./Checkmate/ObjectModel/QueuedEntityRemoveTaskSearch";
import { RangeEstimateSearch } from "./Checkmate/ObjectModel/RangeEstimateSearch";
import { RecipientSearch } from "./Checkmate/ObjectModel/RecipientSearch";
import { ReportStorageSearch } from "./Checkmate/ObjectModel/ReportStorageSearch";
import { ReportTagSearch } from "./Checkmate/ObjectModel/ReportTagSearch";
import { ReportTemplateSearch } from "./Checkmate/ObjectModel/ReportTemplateSearch";
import { RestrictedDataModeChangeSearch } from "./Checkmate/ObjectModel/RestrictedDataModeChangeSearch";
import { RouteExtractSearch } from "./Checkmate/ObjectModel/RouteExtractSearch";
import { RouteSearch } from "./Checkmate/ObjectModel/RouteSearch";
import { SafetyDriverInsightSearch } from "./Checkmate/ObjectModel/SafetyDriverInsightSearch";
import { SafetyFleetBenchmarkSearch } from "./Checkmate/ObjectModel/SafetyFleetBenchmarkSearch";
import { SafetyFleetInsightSearch } from "./Checkmate/ObjectModel/SafetyFleetInsightSearch";
import { SafetyVehicleInsightSearch } from "./Checkmate/ObjectModel/SafetyVehicleInsightSearch";
import { SecurityIdSearch } from "./Checkmate/ObjectModel/SecurityIdSearch";
import { ServiceStateSearch } from "./Checkmate/ObjectModel/ServiceStateSearch";
import { ShareableLinkSearch } from "./Checkmate/ObjectModel/ShareableLinkSearch";
import { ShipmentLogSearch } from "./Checkmate/ObjectModel/ShipmentLogSearch";
import { TextMessageSearch } from "./Checkmate/ObjectModel/TextMessageSearch";
import { TrailerAttachmentSearch } from "./Checkmate/ObjectModel/TrailerAttachmentSearch";
import { TrailerSearch } from "./Checkmate/ObjectModel/TrailerSearch";
import { TripAnnotationSearch } from "./Checkmate/ObjectModel/TripAnnotationSearch";
import { TripGeohashSearch } from "./Checkmate/ObjectModel/TripGeohashSearch";
import { TripSearch } from "./Checkmate/ObjectModel/TripSearch";
import { TripTypeChangeSearch } from "./Checkmate/ObjectModel/TripTypeChangeSearch";
import { UploadTransactionSearch } from "./Checkmate/ObjectModel/UploadTransactionSearch";
import { UserDeviceLinkSearch } from "./Checkmate/ObjectModel/UserDeviceLinkSearch";
import { UserHosRuleSetSearch } from "./Checkmate/ObjectModel/UserHosRuleSetSearch";
import { UserLoginStatusSearch } from "./Checkmate/ObjectModel/UserLoginStatusSearch";
import { UserSearch } from "./Checkmate/ObjectModel/UserSearch";
import { UserSupportSearch } from "./Checkmate/ObjectModel/UserSupportSearch";
import { VehicleDowntimeSearch } from "./Checkmate/ObjectModel/VehicleDowntimeSearch";
import { WifiHotspotSearch } from "./Checkmate/ObjectModel/WifiHotspotSearch";
import { WorkHolidaySearch } from "./Checkmate/ObjectModel/WorkHolidaySearch";
import { WorkTimeSearch } from "./Checkmate/ObjectModel/WorkTimeSearch";
import { ZoneMetadataSearch } from "./Checkmate/ObjectModel/ZoneMetadataSearch";
import { ZoneSearch } from "./Checkmate/ObjectModel/ZoneSearch";
import { ZoneTypeSearch } from "./Checkmate/ObjectModel/ZoneTypeSearch";
import { AddInConfigurationSearch } from "./Checkmate/ObjectModel/AddIns/AddInConfigurationSearch";
import { AddInSearch } from "./Checkmate/ObjectModel/AddIns/AddInSearch";
import { ChargeEventSearch } from "./Checkmate/ObjectModel/Charging/ChargeEventSearch";
import { ConsentStatusAuditSearch } from "./Checkmate/ObjectModel/Consent/ConsentStatusAuditSearch";
import { ConsentStatusSearch } from "./Checkmate/ObjectModel/Consent/ConsentStatusSearch";
import { OptionSearch } from "./Checkmate/ObjectModel/Consent/OptionSearch";
import { ProductSearch } from "./Checkmate/ObjectModel/Consent/ProductSearch";
import { DeviceRegistrationStateSearch } from "./Checkmate/ObjectModel/DeviceRegistration/DeviceRegistrationStateSearch";
import { DeviceReplacementInfoSearch } from "./Checkmate/ObjectModel/DeviceReplacement/DeviceReplacementInfoSearch";
import { EmissionComplianceEventSearch } from "./Checkmate/ObjectModel/EmissionReporting/EmissionComplianceEventSearch";
import { EmissionReportSearch } from "./Checkmate/ObjectModel/EmissionReporting/EmissionReportSearch";
import { EmissionServiceConnectionLogSearch } from "./Checkmate/ObjectModel/EmissionReporting/EmissionServiceConnectionLogSearch";
import { EmissionVehicleCycleMessageSearch } from "./Checkmate/ObjectModel/EmissionReporting/EmissionVehicleCycleMessageSearch";
import { EmissionVehicleCycleSearch } from "./Checkmate/ObjectModel/EmissionReporting/EmissionVehicleCycleSearch";
import { EmissionVehicleEnrollmentSearch } from "./Checkmate/ObjectModel/EmissionReporting/EmissionVehicleEnrollmentSearch";
import { EnergySnapshotRecordSearch } from "./Checkmate/ObjectModel/Energy/EnergySnapshotRecordSearch";
import { ControllerSearch } from "./Checkmate/ObjectModel/Engine/ControllerSearch";
import { DiagnosticDataSearch } from "./Checkmate/ObjectModel/Engine/DiagnosticDataSearch";
import { DiagnosticLookupTableSearch } from "./Checkmate/ObjectModel/Engine/DiagnosticLookupTableSearch";
import { DiagnosticMappingSearch } from "./Checkmate/ObjectModel/Engine/DiagnosticMappingSearch";
import { DiagnosticSearch } from "./Checkmate/ObjectModel/Engine/DiagnosticSearch";
import { EngineTypeSearch } from "./Checkmate/ObjectModel/Engine/EngineTypeSearch";
import { FailureModeSearch } from "./Checkmate/ObjectModel/Engine/FailureModeSearch";
import { FaultDataSearch } from "./Checkmate/ObjectModel/Engine/FaultDataSearch";
import { ParameterGroupSearch } from "./Checkmate/ObjectModel/Engine/ParameterGroupSearch";
import { SourceSearch } from "./Checkmate/ObjectModel/Engine/SourceSearch";
import { StatusDataSearch } from "./Checkmate/ObjectModel/Engine/StatusDataSearch";
import { UnitOfMeasureSearch } from "./Checkmate/ObjectModel/Engine/UnitOfMeasureSearch";
import { DisplayMeasurementProfileDetailSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileDetailSearch";
import { DisplayMeasurementProfileSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileSearch";
import { DisplayUnitOfMeasureSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayUnitOfMeasureSearch";
import { UserDisplayProfileSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/UserDisplayProfileSearch";
import { EntityLinkRuleSearch } from "./Checkmate/ObjectModel/EntityLink/EntityLinkRuleSearch";
import { EntitySettingSearch } from "./Checkmate/ObjectModel/EntitySettings/EntitySettingSearch";
import { EVStatusInfoSearch } from "./Checkmate/ObjectModel/EVStatus/EVStatusInfoSearch";
import { EvsaConfigurationSearch } from "./Checkmate/ObjectModel/EvSuitabilityAssessment/EvsaConfigurationSearch";
import { EvsaRequestSearch } from "./Checkmate/ObjectModel/EvSuitabilityAssessment/EvsaRequestSearch";
import { ExceptionEventAttachmentSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventAttachmentSearch";
import { ExceptionEventCommentSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventCommentSearch";
import { ExceptionEventSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventSearch";
import { RuleSearch } from "./Checkmate/ObjectModel/Exceptions/RuleSearch";
import { MediaFileSearch } from "./Checkmate/ObjectModel/Files/MediaFileSearch";
import { FillUpSearch } from "./Checkmate/ObjectModel/Fuel/FillUpSearch";
import { FuelAndEnergyUsedSearch } from "./Checkmate/ObjectModel/Fuel/FuelAndEnergyUsedSearch";
import { FuelSnapshotRecordSearch } from "./Checkmate/ObjectModel/Fuel/FuelSnapshotRecordSearch";
import { FuelTransactionSearch } from "./Checkmate/ObjectModel/Fuel/FuelTransactionSearch";
import { FuelUpEventSearch } from "./Checkmate/ObjectModel/Fuel/FuelUpEventSearch";
import { FuelUsedSearch } from "./Checkmate/ObjectModel/Fuel/FuelUsedSearch";
import { PotentialFuelFraudEventSearch } from "./Checkmate/ObjectModel/Fuel/PotentialFuelFraud/PotentialFuelFraudEventSearch";
import { DashboardCacheSearch } from "./Checkmate/ObjectModel/Checkmate/Reports/DashboardCacheSearch";
import { DriverRegulationReprocessRequestSearch } from "./Checkmate/ObjectModel/HOS/DriverRegulationReprocessRequestSearch";
import { InstallRecordSearch } from "./Checkmate/ObjectModel/InstallRecords/InstallRecordSearch";
import { DiagnosticValueStatusSearch } from "./Checkmate/ObjectModel/Maintenance/DiagnosticValueStatusSearch";
import { DocumentScanningSearch } from "./Checkmate/ObjectModel/Maintenance/DocumentScanningSearch";
import { MaintenanceWorkOrderJobSearch } from "./Checkmate/ObjectModel/Maintenance/MaintenanceWorkOrderJobSearch";
import { MaintenanceWorkOrderSearch } from "./Checkmate/ObjectModel/Maintenance/MaintenanceWorkOrderSearch";
import { MaintenanceWorkRequestSearch } from "./Checkmate/ObjectModel/Maintenance/MaintenanceWorkRequestSearch";
import { BackfillStatusSearch } from "./Checkmate/ObjectModel/Processing/BackfillStatusSearch";
import { PushTokenSearch } from "./Checkmate/ObjectModel/PushNotifications/PushTokenSearch";
import { DeviceReprocessRequestSearch } from "./Checkmate/ObjectModel/Reprocessing/DeviceReprocessRequestSearch";
import { ReprocessRequestSearch } from "./Checkmate/ObjectModel/Reprocessing/ReprocessRequestSearch";
import { SustainabilityElectrificationSummarySearch } from "./Checkmate/ObjectModel/Sustainability/SustainabilityElectrificationSummarySearch";
import { SustainabilityGroupIdlingSummarySearch } from "./Checkmate/ObjectModel/Sustainability/SustainabilityGroupIdlingSummarySearch";
import { SustainabilityMonthlySummarySearch } from "./Checkmate/ObjectModel/Sustainability/SustainabilityMonthlySummarySearch";
import { TachographDriverActivitySearch } from "./Checkmate/ObjectModel/Tachograph/TachographDriverActivitySearch";
import { TachographDrivingTimeStatusSearch } from "./Checkmate/ObjectModel/Tachograph/TachographDrivingTimeStatusSearch";
import { TachographActivitiesCertificateSearch } from "./Checkmate/ObjectModel/Tachograph/ActivitiesCertificates/TachographActivitiesCertificateSearch";
import { TachographCompanyCardSearch } from "./Checkmate/ObjectModel/Tachograph/CompanyCards/TachographCompanyCardSearch";
import { TachographDataFileSearch } from "./Checkmate/ObjectModel/Tachograph/Files/TachographDataFileSearch";
import { TachographVehicleInspectionSearch } from "./Checkmate/ObjectModel/Tachograph/Inspections/TachographVehicleInspectionSearch";

export type SearchTypes = {
  AddInConfiguration: AddInConfigurationSearch;
  AddInData: AddInDataSearch;
  AddIn: AddInSearch;
  AnnotationLog: AnnotationLogSearch;
  AssetLinkDetails: AssetLinkDetailsSearch;
  AssetLink: AssetLinkSearch;
  AssetSeparationSubscription: AssetSeparationSubscriptionSearch;
  Audit: AuditSearch;
  BackfillStatus: BackfillStatusSearch;
  BatteryStateOfHealth: BatteryStateOfHealthSearch;
  BinaryData: BinaryDataSearch;
  CameraHealth: CameraHealthSearch;
  Camera: CameraSearch;
  CameraStatus: CameraStatusSearch;
  Certificate: CertificateSearch;
  ChargeEvent: ChargeEventSearch;
  CoachingSession: CoachingSessionSearch;
  ConsentStatusAudit: ConsentStatusAuditSearch;
  ConsentStatus: ConsentStatusSearch;
  Controller: ControllerSearch;
  CustomData: CustomDataSearch;
  CustomReportSchedule: CustomReportScheduleSearch;
  DashboardCache: DashboardCacheSearch;
  DebugData: DebugDataSearch;
  DefectRemark: DefectRemarkSearch;
  Defect: DefectSearch;
  DeviceCommunicationHistory: DeviceCommunicationHistorySearch;
  DeviceCommunicationStatus: DeviceCommunicationStatusSearch;
  DeviceLink: DeviceLinkSearch;
  DeviceMasterFlag: DeviceMasterFlagSearch;
  DeviceRegistrationState: DeviceRegistrationStateSearch;
  DeviceReplacementInfo: DeviceReplacementInfoSearch;
  DeviceReprocessRequest: DeviceReprocessRequestSearch;
  Device: DeviceSearch;
  DeviceShare: DeviceShareSearch;
  DeviceStatusInfo: DeviceStatusInfoSearch;
  DiagnosticData: DiagnosticDataSearch;
  DiagnosticLookupTable: DiagnosticLookupTableSearch;
  DiagnosticMapping: DiagnosticMappingSearch;
  Diagnostic: DiagnosticSearch;
  DiagnosticValueStatus: DiagnosticValueStatusSearch;
  DiscreteAvailabilitySnapshot: DiscreteAvailabilitySnapshotSearch;
  DisplayMeasurementProfileDetail: DisplayMeasurementProfileDetailSearch;
  DisplayMeasurementProfile: DisplayMeasurementProfileSearch;
  DisplayUnitOfMeasure: DisplayUnitOfMeasureSearch;
  DistributionList: DistributionListSearch;
  DocumentScanning: DocumentScanningSearch;
  DriverChange: DriverChangeSearch;
  DriverRegulationReprocessRequest: DriverRegulationReprocessRequestSearch;
  DriverRegulation: DriverRegulationSearch;
  DriverRegulationServiceScheduleInfo: DriverRegulationServiceScheduleInfoSearch;
  DutyStatusAvailability: DutyStatusAvailabilitySearch;
  DutyStatusLog: DutyStatusLogSearch;
  DutyStatusViolation: DutyStatusViolationSearch;
  DVIRDefect: DVIRDefectSearch;
  DVIRLog: DVIRLogSearch;
  ElectrificationAggregation: ElectrificationAggregationSearch;
  EmissionComplianceEvent: EmissionComplianceEventSearch;
  EmissionReport: EmissionReportSearch;
  EmissionServiceConnectionLog: EmissionServiceConnectionLogSearch;
  EmissionVehicleCycleMessage: EmissionVehicleCycleMessageSearch;
  EmissionVehicleCycle: EmissionVehicleCycleSearch;
  EmissionVehicleEnrollment: EmissionVehicleEnrollmentSearch;
  EmployeeRoutePlan: EmployeeRoutePlanSearch;
  EnergySnapshotRecord: EnergySnapshotRecordSearch;
  EngineType: EngineTypeSearch;
  EntityLinkRule: EntityLinkRuleSearch;
  EntitySetting: EntitySettingSearch;
  EntityUploadRequest: EntityUploadRequestSearch;
  EventDeviation: EventDeviationSearch;
  EventOccurrenceDue: EventOccurrenceDueSearch;
  EventOccurrence: EventOccurrenceSearch;
  EventType: EventTypeSearch;
  EvsaConfiguration: EvsaConfigurationSearch;
  EvsaRequest: EvsaRequestSearch;
  EVStatusInfo: EVStatusInfoSearch;
  ExceptionEventAttachment: ExceptionEventAttachmentSearch;
  ExceptionEventComment: ExceptionEventCommentSearch;
  ExceptionEventMediaLink: ExceptionEventMediaLinkSearch;
  ExceptionEvent: ExceptionEventSearch;
  FailureMode: FailureModeSearch;
  FaultCycle: FaultCycleSearch;
  FaultData: FaultDataSearch;
  FaultRichData: FaultRichDataSearch;
  Feedback: FeedbackSearch;
  FeedVersionTrackingData: FeedVersionTrackingDataSearch;
  FillUp: FillUpSearch;
  FuelAndEnergySetting: FuelAndEnergySettingSearch;
  FuelAndEnergyUsedAggregation: FuelAndEnergyUsedAggregationSearch;
  FuelAndEnergyUsed: FuelAndEnergyUsedSearch;
  FuelSnapshotRecord: FuelSnapshotRecordSearch;
  FuelTaxDetail: FuelTaxDetailSearch;
  FuelTransaction: FuelTransactionSearch;
  FuelUpEvent: FuelUpEventSearch;
  FuelUsed: FuelUsedSearch;
  GroupAddIn: GroupAddInSearch;
  GroupDevice: GroupDeviceSearch;
  GroupFilter: GroupFilterSearch;
  Group: GroupSearch;
  GroupZoneMetadata: GroupZoneMetadataSearch;
  HosRulesetConfig: HosRulesetConfigSearch;
  HosStatusInfo: HosStatusInfoSearch;
  IdlingExceptionAggregation: IdlingExceptionAggregationSearch;
  IdlingFuelPercentageAggregation: IdlingFuelPercentageAggregationSearch;
  InspectedItem: InspectedItemSearch;
  InspectionLog: InspectionLogSearch;
  InstallRecord: InstallRecordSearch;
  InvestigationAttachment: InvestigationAttachmentSearch;
  InvestigationComment: InvestigationCommentSearch;
  Investigation: InvestigationSearch;
  IoxAddOn: IoxAddOnSearch;
  IoxAddOnStatus: IoxAddOnStatusSearch;
  IoxWorksConfigFileInfo: IoxWorksConfigFileInfoSearch;
  LiveCompletionMapConfig: LiveCompletionMapConfigSearch;
  LogRecordGeohash: LogRecordGeohashSearch;
  LogRecord: LogRecordSearch;
  LogRecordZoneDistance: LogRecordZoneDistanceSearch;
  LostModeChange: LostModeChangeSearch;
  MaintenanceNotificationRule: MaintenanceNotificationRuleSearch;
  MaintenanceNotificationState: MaintenanceNotificationStateSearch;
  MaintenanceSchedule: MaintenanceScheduleSearch;
  MaintenanceWorkOrderJob: MaintenanceWorkOrderJobSearch;
  MaintenanceWorkOrder: MaintenanceWorkOrderSearch;
  MaintenanceWorkRequest: MaintenanceWorkRequestSearch;
  MediaFile: MediaFileSearch;
  MediaRequestNotification: MediaRequestNotificationSearch;
  MimeTask: MimeTaskSearch;
  Notification: NotificationSearch;
  Option: OptionSearch;
  ParameterGroup: ParameterGroupSearch;
  PotentialFuelFraudEvent: PotentialFuelFraudEventSearch;
  Product: ProductSearch;
  Property: PropertySearch;
  PropertySet: PropertySetSearch;
  PushToken: PushTokenSearch;
  QueuedEntityRemoveTask: QueuedEntityRemoveTaskSearch;
  RangeEstimate: RangeEstimateSearch;
  Recipient: RecipientSearch;
  ReportStorage: ReportStorageSearch;
  ReportTag: ReportTagSearch;
  ReportTemplate: ReportTemplateSearch;
  ReprocessRequest: ReprocessRequestSearch;
  RestrictedDataModeChange: RestrictedDataModeChangeSearch;
  RouteExtract: RouteExtractSearch;
  Route: RouteSearch;
  Rule: RuleSearch;
  SafetyDriverInsight: SafetyDriverInsightSearch;
  SafetyFleetBenchmark: SafetyFleetBenchmarkSearch;
  SafetyFleetInsight: SafetyFleetInsightSearch;
  SafetyVehicleInsight: SafetyVehicleInsightSearch;
  SecurityId: SecurityIdSearch;
  ServiceState: ServiceStateSearch;
  ShareableLink: ShareableLinkSearch;
  ShipmentLog: ShipmentLogSearch;
  Source: SourceSearch;
  StatusData: StatusDataSearch;
  SustainabilityElectrificationSummary: SustainabilityElectrificationSummarySearch;
  SustainabilityGroupIdlingSummary: SustainabilityGroupIdlingSummarySearch;
  SustainabilityMonthlySummary: SustainabilityMonthlySummarySearch;
  TachographActivitiesCertificate: TachographActivitiesCertificateSearch;
  TachographCompanyCard: TachographCompanyCardSearch;
  TachographDataFile: TachographDataFileSearch;
  TachographDriverActivity: TachographDriverActivitySearch;
  TachographDrivingTimeStatus: TachographDrivingTimeStatusSearch;
  TachographVehicleInspection: TachographVehicleInspectionSearch;
  TextMessage: TextMessageSearch;
  TrailerAttachment: TrailerAttachmentSearch;
  Trailer: TrailerSearch;
  TripAnnotation: TripAnnotationSearch;
  TripGeohash: TripGeohashSearch;
  Trip: TripSearch;
  TripTypeChange: TripTypeChangeSearch;
  UnitOfMeasure: UnitOfMeasureSearch;
  UploadTransaction: UploadTransactionSearch;
  UserDeviceLink: UserDeviceLinkSearch;
  UserDisplayProfile: UserDisplayProfileSearch;
  UserHosRuleSet: UserHosRuleSetSearch;
  UserLoginStatus: UserLoginStatusSearch;
  User: UserSearch;
  UserSupport: UserSupportSearch;
  VehicleDowntime: VehicleDowntimeSearch;
  WifiHotspot: WifiHotspotSearch;
  WorkHoliday: WorkHolidaySearch;
  WorkTime: WorkTimeSearch;
  ZoneMetadata: ZoneMetadataSearch;
  Zone: ZoneSearch;
  ZoneType: ZoneTypeSearch;
};
