import type { AddInDataSearch } from "./Checkmate/ObjectModel/AddInDataSearch";
import type { AddInSearch } from "./Checkmate/ObjectModel/AddIns/AddInSearch";
import type { AnnotationLogSearch } from "./Checkmate/ObjectModel/AnnotationLogSearch";
import type { AuditSearch } from "./Checkmate/ObjectModel/AuditSearch";
import type { BinaryDataSearch } from "./Checkmate/ObjectModel/BinaryDataSearch";
import type { CertificateSearch } from "./Checkmate/ObjectModel/CertificateSearch";
import type { ChargeEventSearch } from "./Checkmate/ObjectModel/Charging/ChargeEventSearch";
import type { CustomDataSearch } from "./Checkmate/ObjectModel/CustomDataSearch";
import type { DashboardSearch } from "./Checkmate/ObjectModel/DashboardSearch";
import type { DebugDataSearch } from "./Checkmate/ObjectModel/DebugDataSearch";
import type { DefectRemarkSearch } from "./Checkmate/ObjectModel/DefectRemarkSearch";
import type { DefectSearch } from "./Checkmate/ObjectModel/DefectSearch";
import type { DeviceDataPrivacyChangeSearch } from "./Checkmate/ObjectModel/DeviceDataPrivacyChangeSearch";
import type { DeviceLinkSearch } from "./Checkmate/ObjectModel/DeviceLinkSearch";
import type { DeviceMasterFlagSearch } from "./Checkmate/ObjectModel/DeviceMasterFlagSearch";
import type { DeviceRegistrationStateSearch } from "./Checkmate/ObjectModel/DeviceRegistration/DeviceRegistrationStateSearch";
import type { DeviceReplacementInfoSearch } from "./Checkmate/ObjectModel/DeviceReplacement/DeviceReplacementInfoSearch";
import type { DeviceSearch } from "./Checkmate/ObjectModel/DeviceSearch";
import type { DeviceShareSearch } from "./Checkmate/ObjectModel/DeviceShareSearch";
import type { DeviceStatusInfoSearch } from "./Checkmate/ObjectModel/DeviceStatusInfoSearch";
import type { DistributionListSearch } from "./Checkmate/ObjectModel/DistributionListSearch";
import type { DriverChangeSearch } from "./Checkmate/ObjectModel/DriverChangeSearch";
import type { DriverRegulationSearch } from "./Checkmate/ObjectModel/DriverRegulationSearch";
import type { DutyStatusAvailabilitySearch } from "./Checkmate/ObjectModel/DutyStatusAvailabilitySearch";
import type { DutyStatusLogSearch } from "./Checkmate/ObjectModel/DutyStatusLogSearch";
import type { DutyStatusViolationSearch } from "./Checkmate/ObjectModel/DutyStatusViolationSearch";
import type { DVIRDefectSearch } from "./Checkmate/ObjectModel/DVIRDefectSearch";
import type { DVIRLogSearch } from "./Checkmate/ObjectModel/DVIRLogSearch";
import type { EmployeeRoutePlanSearch } from "./Checkmate/ObjectModel/EmployeeRoutePlanSearch";
import type { EnergyConsumedSearch } from "./Checkmate/ObjectModel/Energy/EnergyConsumedSearch";
import type { EnergySnapshotRecordSearch } from "./Checkmate/ObjectModel/Energy/EnergySnapshotRecordSearch";
import type { ControllerSearch } from "./Checkmate/ObjectModel/Engine/ControllerSearch";
import type { DiagnosticSearch } from "./Checkmate/ObjectModel/Engine/DiagnosticSearch";
import type { DisplayMeasurementProfileDetailSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileDetailSearch";
import type { DisplayMeasurementProfileSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayMeasurementProfileSearch";
import type { DisplayUnitOfMeasureSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/DisplayUnitOfMeasureSearch";
import type { UserDisplayProfileSearch } from "./Checkmate/ObjectModel/Engine/DisplayDiagnostic/UserDisplayProfileSearch";
import type { EngineTypeSearch } from "./Checkmate/ObjectModel/Engine/EngineTypeSearch";
import type { FailureModeSearch } from "./Checkmate/ObjectModel/Engine/FailureModeSearch";
import type { FaultDataSearch } from "./Checkmate/ObjectModel/Engine/FaultDataSearch";
import type { ParameterGroupSearch } from "./Checkmate/ObjectModel/Engine/ParameterGroupSearch";
import type { SourceSearch } from "./Checkmate/ObjectModel/Engine/SourceSearch";
import type { StatusDataSearch } from "./Checkmate/ObjectModel/Engine/StatusDataSearch";
import type { UnitOfMeasureSearch } from "./Checkmate/ObjectModel/Engine/UnitOfMeasureSearch";
import type { EntityLinkRuleSearch } from "./Checkmate/ObjectModel/EntityLink/EntityLinkRuleSearch";
import type { EventOccurrenceDueSearch } from "./Checkmate/ObjectModel/EventOccurrenceDueSearch";
import type { EventOccurrenceSearch } from "./Checkmate/ObjectModel/EventOccurrenceSearch";
import type { EventRuleSearch } from "./Checkmate/ObjectModel/EventRuleSearch";
import type { ExceptionEventAttachmentSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventAttachmentSearch";
import type { ExceptionEventCommentSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventCommentSearch";
import type { ExceptionEventSearch } from "./Checkmate/ObjectModel/Exceptions/ExceptionEventSearch";
import type { RuleSearch } from "./Checkmate/ObjectModel/Exceptions/RuleSearch";
import type { VirtualExceptionEventSearch } from "./Checkmate/ObjectModel/Exceptions/VirtualExceptionEventSearch";
import type { FeedVersionTrackingDataSearch } from "./Checkmate/ObjectModel/FeedVersionTrackingDataSearch";
import type { MediaFileSearch } from "./Checkmate/ObjectModel/Files/MediaFileSearch";
import type { FillUpSearch } from "./Checkmate/ObjectModel/Fuel/FillUpSearch";
import type { FuelSnapshotRecordSearch } from "./Checkmate/ObjectModel/Fuel/FuelSnapshotRecordSearch";
import type { FuelTransactionSearch } from "./Checkmate/ObjectModel/Fuel/FuelTransactionSearch";
import type { FuelUpEventSearch } from "./Checkmate/ObjectModel/Fuel/FuelUpEventSearch";
import type { FuelUsedSearch } from "./Checkmate/ObjectModel/Fuel/FuelUsedSearch";
import type { FuelTaxDetailSearch } from "./Checkmate/ObjectModel/FuelTaxDetailSearch";
import type { GroupDeviceSearch } from "./Checkmate/ObjectModel/GroupDeviceSearch";
import type { GroupFilterSearch } from "./Checkmate/ObjectModel/GroupFilterSearch";
import type { GroupSearch } from "./Checkmate/ObjectModel/GroupSearch";
import type { GroupZoneMetadataSearch } from "./Checkmate/ObjectModel/GroupZoneMetadataSearch";
import type { HosRulesetConfigSearch } from "./Checkmate/ObjectModel/HosRulesetConfigSearch";
import type { InstallRecordSearch } from "./Checkmate/ObjectModel/InstallRecords/InstallRecordSearch";
import type { IoxAddOnSearch } from "./Checkmate/ObjectModel/IoxAddOnSearch";
import type { LogRecordSearch } from "./Checkmate/ObjectModel/LogRecordSearch";
import type { LogRecordZoneDistanceSearch } from "./Checkmate/ObjectModel/LogRecordZoneDistanceSearch";
import type { MaintenanceNotificationRuleSearch } from "./Checkmate/ObjectModel/MaintenanceNotificationRuleSearch";
import type { MaintenanceNotificationStateSearch } from "./Checkmate/ObjectModel/MaintenanceNotificationStateSearch";
import type { MimeTaskSearch } from "./Checkmate/ObjectModel/MimeTaskSearch";
import type { NotificationSearch } from "./Checkmate/ObjectModel/NotificationSearch";
import type { EnergyConsumedProcessingSearch } from "./Checkmate/ObjectModel/Processing/EnergyConsumedProcessingSearch";
import type { FuelAndEnergySnapshotProcessingSearch } from "./Checkmate/ObjectModel/Processing/FuelAndEnergySnapshotProcessingSearch";
import type { PropertySearch } from "./Checkmate/ObjectModel/PropertySearch";
import type { PropertySetSearch } from "./Checkmate/ObjectModel/PropertySetSearch";
import type { RecipientSearch } from "./Checkmate/ObjectModel/RecipientSearch";
import type { ReportStorageSearch } from "./Checkmate/ObjectModel/ReportStorageSearch";
import type { ReportTemplateSearch } from "./Checkmate/ObjectModel/ReportTemplateSearch";
import type { DeviceReprocessRequestSearch } from "./Checkmate/ObjectModel/Reprocessing/DeviceReprocessRequestSearch";
import type { RouteExtractSearch } from "./Checkmate/ObjectModel/RouteExtractSearch";
import type { RouteSearch } from "./Checkmate/ObjectModel/RouteSearch";
import type { SecurityIdSearch } from "./Checkmate/ObjectModel/SecurityIdSearch";
import type { ServiceStateSearch } from "./Checkmate/ObjectModel/ServiceStateSearch";
import type { ShareableLinkSearch } from "./Checkmate/ObjectModel/ShareableLinkSearch";
import type { ShipmentLogSearch } from "./Checkmate/ObjectModel/ShipmentLogSearch";
import type { TextMessageSearch } from "./Checkmate/ObjectModel/TextMessageSearch";
import type { TrailerAttachmentSearch } from "./Checkmate/ObjectModel/TrailerAttachmentSearch";
import type { TrailerSearch } from "./Checkmate/ObjectModel/TrailerSearch";
import type { TripAnnotationSearch } from "./Checkmate/ObjectModel/TripAnnotationSearch";
import type { TripGeohashSearch } from "./Checkmate/ObjectModel/TripGeohashSearch";
import type { TripSearch } from "./Checkmate/ObjectModel/TripSearch";
import type { TripTypeChangeSearch } from "./Checkmate/ObjectModel/TripTypeChangeSearch";
import type { UserDeviceLinkSearch } from "./Checkmate/ObjectModel/UserDeviceLinkSearch";
import type { UserHosRuleSetSearch } from "./Checkmate/ObjectModel/UserHosRuleSetSearch";
import type { UserLoginStatusSearch } from "./Checkmate/ObjectModel/UserLoginStatusSearch";
import type { UserSearch } from "./Checkmate/ObjectModel/UserSearch";
import type { UserSupportSearch } from "./Checkmate/ObjectModel/UserSupportSearch";
import type { VehicleConfigurationSearch } from "./Checkmate/ObjectModel/VehicleConfigurationSearch";
import type { WidgetSearch } from "./Checkmate/ObjectModel/WidgetSearch";
import type { WifiHotspotSearch } from "./Checkmate/ObjectModel/WifiHotspotSearch";
import type { WorkHolidaySearch } from "./Checkmate/ObjectModel/WorkHolidaySearch";
import type { WorkTimeSearch } from "./Checkmate/ObjectModel/WorkTimeSearch";
import type { ZoneSearch } from "./Checkmate/ObjectModel/ZoneSearch";
import type { ZoneTypeSearch } from "./Checkmate/ObjectModel/ZoneTypeSearch";

export type SearchTypes = {
  AddInData: AddInDataSearch;
  AnnotationLog: AnnotationLogSearch;
  Audit: AuditSearch;
  BinaryData: BinaryDataSearch;
  Certificate: CertificateSearch;
  CustomData: CustomDataSearch;
  Property: PropertySearch;
  PropertySet: PropertySetSearch;
  Dashboard: DashboardSearch;
  DebugData: DebugDataSearch;
  DefectRemark: DefectRemarkSearch;
  Defect: DefectSearch;
  DeviceDataPrivacyChange: DeviceDataPrivacyChangeSearch;
  DeviceLink: DeviceLinkSearch;
  DeviceMasterFlag: DeviceMasterFlagSearch;
  Device: DeviceSearch;
  DeviceShare: DeviceShareSearch;
  DeviceStatusInfo: DeviceStatusInfoSearch;
  DistributionList: DistributionListSearch;
  DriverChange: DriverChangeSearch;
  DriverRegulation: DriverRegulationSearch;
  DutyStatusAvailability: DutyStatusAvailabilitySearch;
  DutyStatusLog: DutyStatusLogSearch;
  DutyStatusViolation: DutyStatusViolationSearch;
  DVIRDefect: DVIRDefectSearch;
  DVIRLog: DVIRLogSearch;
  EmployeeRoutePlan: EmployeeRoutePlanSearch;
  EventOccurrenceDue: EventOccurrenceDueSearch;
  EventOccurrence: EventOccurrenceSearch;
  EventRule: EventRuleSearch;
  FeedVersionTrackingData: FeedVersionTrackingDataSearch;
  FuelTaxDetail: FuelTaxDetailSearch;
  GroupDevice: GroupDeviceSearch;
  GroupFilter: GroupFilterSearch;
  Group: GroupSearch;
  GroupZoneMetadata: GroupZoneMetadataSearch;
  HosRulesetConfig: HosRulesetConfigSearch;
  IoxAddOn: IoxAddOnSearch;
  LogRecord: LogRecordSearch;
  LogRecordZoneDistance: LogRecordZoneDistanceSearch;
  MaintenanceNotificationRule: MaintenanceNotificationRuleSearch;
  MaintenanceNotificationState: MaintenanceNotificationStateSearch;
  MimeTask: MimeTaskSearch;
  Notification: NotificationSearch;
  Recipient: RecipientSearch;
  ReportStorage: ReportStorageSearch;
  ReportTemplate: ReportTemplateSearch;
  RouteExtract: RouteExtractSearch;
  Route: RouteSearch;
  SecurityId: SecurityIdSearch;
  ServiceState: ServiceStateSearch;
  ShareableLink: ShareableLinkSearch;
  ShipmentLog: ShipmentLogSearch;
  TextMessage: TextMessageSearch;
  TrailerAttachment: TrailerAttachmentSearch;
  Trailer: TrailerSearch;
  TripAnnotation: TripAnnotationSearch;
  TripGeohash: TripGeohashSearch;
  Trip: TripSearch;
  TripTypeChange: TripTypeChangeSearch;
  UserDeviceLink: UserDeviceLinkSearch;
  UserHosRuleSet: UserHosRuleSetSearch;
  UserLoginStatus: UserLoginStatusSearch;
  User: UserSearch;
  UserSupport: UserSupportSearch;
  VehicleConfiguration: VehicleConfigurationSearch;
  Widget: WidgetSearch;
  WifiHotspot: WifiHotspotSearch;
  WorkHoliday: WorkHolidaySearch;
  WorkTime: WorkTimeSearch;
  Zone: ZoneSearch;
  ZoneType: ZoneTypeSearch;
  DeviceReprocessRequest: DeviceReprocessRequestSearch;
  EnergyConsumedProcessing: EnergyConsumedProcessingSearch;
  FuelAndEnergySnapshotProcessing: FuelAndEnergySnapshotProcessingSearch;
  InstallRecord: InstallRecordSearch;
  FillUp: FillUpSearch;
  FuelSnapshotRecord: FuelSnapshotRecordSearch;
  FuelTransaction: FuelTransactionSearch;
  FuelUpEvent: FuelUpEventSearch;
  FuelUsed: FuelUsedSearch;
  MediaFile: MediaFileSearch;
  ExceptionEventAttachment: ExceptionEventAttachmentSearch;
  ExceptionEventComment: ExceptionEventCommentSearch;
  ExceptionEvent: ExceptionEventSearch;
  Rule: RuleSearch;
  VirtualExceptionEvent: VirtualExceptionEventSearch;
  EntityLinkRule: EntityLinkRuleSearch;
  Controller: ControllerSearch;
  Diagnostic: DiagnosticSearch;
  EngineType: EngineTypeSearch;
  FailureMode: FailureModeSearch;
  FaultData: FaultDataSearch;
  ParameterGroup: ParameterGroupSearch;
  Source: SourceSearch;
  StatusData: StatusDataSearch;
  UnitOfMeasure: UnitOfMeasureSearch;
  DisplayMeasurementProfileDetail: DisplayMeasurementProfileDetailSearch;
  DisplayMeasurementProfile: DisplayMeasurementProfileSearch;
  DisplayUnitOfMeasure: DisplayUnitOfMeasureSearch;
  UserDisplayProfile: UserDisplayProfileSearch;
  EnergyConsumed: EnergyConsumedSearch;
  EnergySnapshotRecord: EnergySnapshotRecordSearch;
  DeviceReplacementInfo: DeviceReplacementInfoSearch;
  DeviceRegistrationState: DeviceRegistrationStateSearch;
  ChargeEvent: ChargeEventSearch;
  AddIn: AddInSearch;
};
