//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** A type for filter {@link TachographDataFileSearch} by file type. */
export type TachographFileType = "Driver" | "Device";
