//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../../Search";
import { DeviceSearch } from "../../DeviceSearch";
import { UserSearch } from "../../UserSearch";
import { TachographFileType } from "./TachographFileType";
import { FloorToCeilingTimestampSearch } from "./FloorToCeilingTimestampSearch";
import { ActivityTimestampBetweenSearch } from "./ActivityTimestampBetweenSearch";

/** The object used to specify the arguments when searching for {@link TachographDataFile}. */
export interface TachographDataFileSearch extends Search {
  /**
   * @inheritdoc
   */
  activityTimestampBetween: ActivityTimestampBetweenSearch;
  /** Gets or sets search for TachographFile text into specific fields. */
  containsText: string;
  /** Gets or sets search for TachographFile Device Ids records are in the list. */
  deviceIds: string[];
  /**
   * Gets or sets filter by the {@link DeviceSearch} options. Providing a device ID will
   *  search for any TachographFile that are assigned to that Device.
   *  Providing the Groups will search for TachographFile for that have Devices in that group.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>Group</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for TachographFile Driver Ids records are in the list. */
  driverIds: string[];
  /** Gets or sets search for contains text in errors. */
  errorContains: string;
  /**
   * Gets or sets datetime to filter by ActivityTimestampEnd.
   *  It will return the last file of each driver where ActivityTimestampEnd is greater than this value.
   */
  fromActivityTimestampEnd: Date;
  /** Gets or sets search for TachographFile records that were logged at this date or after. */
  fromDate: Date;
  /**
   * @inheritdoc
   */
  fromFloorToCeilingTimestamp: FloorToCeilingTimestampSearch;
  /** Gets or sets search for TachographFile records that were generated at this date or after. */
  fromTimestamp: Date;
  /** Gets or sets search for TachographFile Device Ids records are in the list. */
  ids: string[];
  /** Gets or sets the flag to include binary data in the response. */
  includeBinaryData: boolean;
  /** Gets or sets search for files with a specific processing status. */
  processingStatus: number;
  /** Gets or sets search for TachographFile records that were logged at this date or before. */
  toDate: Date;
  /** Gets or sets search for TachographFile records that were generated at this date or before. */
  toTimestamp: Date;
  /** Gets or sets search for TachographFile records based on the type of file. */
  type: TachographFileType;
  /**
   * Gets or sets filter by the {@link UserSearch} options. Providing a user ID will
   *  search for any TachographFile that are assigned to that user.
   *  Providing the Groups will search for TachographFile for that have Users in that group.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>Group</description></item></list>
   */
  userSearch: UserSearch;
  /**
   * Gets or sets the row version of the
   *  {@link TachographDataFile}
   *  search criteria.
   */
  version: number;
  /** Gets or sets search for files without errors. */
  withoutError: boolean;
}
