//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** An enum that indicates the uploader status. */
export type ProcessingStatus =
  | "DaylightHoursProcessing"
  | "AfterHoursProcessing"
  | "DaylightHoursReprocessing"
  | "AfterHoursReprocessing"
  | "Idle"
  | "Unavailable";
