//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { Diagnostic } from "./Diagnostic";
import { Device } from "../Device";

/**
 * Stores deserialized diagnostic data from protobuf format. All fault-specific fields live inside
 *  {@link DiagnosticData.Value} — this class only holds common metadata (Id, DateTime, Diagnostic, Device).
 */
export interface DiagnosticData extends Entity {
  /** Gets or sets the date and time when the fault occurred. */
  dateTime: Date;
  /** Gets or sets the device that reported this fault. */
  device: Device;
  /** Gets or sets the diagnostic that triggered this fault. */
  diagnostic: Diagnostic;
  /** Gets or sets the deserialized protobuf content containing all diagnostic-specific fields. */
  value: unknown;
}
