//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";

/** The object used to specify the arguments when searching for {@link DiagnosticLookupTable}(s). */
export interface DiagnosticLookupTableSearch extends Search {
  /** Gets or sets search for DiagnosticLookupTables with these unique {@link Id}(s) (table names). */
  ids: string[];
  /**
   * Gets or sets search for DiagnosticLookupTables with this Name.
   *  Wildcard search is supported.
   */
  name: string;
}
