//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Represents the lamp status of a J1939 fault, see {@link FaultData}. */
export enum FaultLampState {
  /** Fault lamp is off, no active fault state. */
  None = "None",
  /** Malfunction lamp is active. */
  Malfunction = "Malfunction",
  /** Amber warning lamp is active. */
  Warning = "Warning",
  /** Red stop lamp is active. */
  Stop = "Stop",
  /** Protect lamp is active. */
  Protect = "Protect",
}
