//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Represents the lamp status of a J1939 fault, see {@link FaultData}. */
export type FaultLampState =
  | "None"
  | "Malfunction"
  | "Warning"
  | "Stop"
  | "Protect";
