//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { EmissionVehicleEnrollmentSearch } from "./EmissionVehicleEnrollmentSearch";

/** A search object for finding specific {@link EmissionComplianceEvent} records. */
export interface EmissionComplianceEventSearch extends Search {
  /**
   * Gets or sets a list of ComplianceStatus to search for all {@link EmissionComplianceEvent} records matching one of the compliance statuses.
   *  Valid "ComplianceStatus" values are:
   *  <list><item><description>Fail</description></item><item><description>Pass</description></item><item><description>NotReady</description></item><item><description>Incomplete</description></item><item><description>InvalidTesterId</description></item><item><description>OutdatedSoftwareVersion</description></item><item><description>VehicleNotApplicableForObdTesting</description></item><item><description>TestResultCouldNotBeDetermined</description></item><item><description>VehicleNotApplicableForCleanTruckCheck</description></item><item><description>InvalidTest</description></item><item><description>NoCompleteCycles</description></item></list>
   */
  complianceStatuses: string[];
  /**
   * Gets or sets an {@link EmissionComplianceEventSearch.EmissionVehicleEnrollmentSearch} to filter events based on their parent enrollment.
   *  Available search options are:
   *  <list type="bullet"><item><description>Id</description></item><item><description>EnrollmentIds</description></item></list>
   */
  emissionVehicleEnrollmentSearch: EmissionVehicleEnrollmentSearch;
  /**
   * Gets or sets the event type for the compliance event.
   *  Valid values are:
   *  <list type="bullet"><item><description>InitialDeadlineSet</description></item><item><description>ResponseReceived</description></item></list>
   */
  eventType: string;
  /** Gets or sets the start of the date range (exclusive) to search for events. This property typically filters on the CreatedDateTime of the entity. */
  fromDate: Date;
  /** Gets or sets the start of the date range (inclusive) to search for {@link EmissionComplianceEvent} records by their ScheduledDateTime. */
  fromScheduledDateTime: Date;
  /** Gets or sets the start of the date range (inclusive) to search for {@link EmissionComplianceEvent} records by their SubmittedDateTime. */
  fromSubmittedDateTime: Date;
  /**
   * Gets or sets a value to search for {@link EmissionComplianceEvent} records that have a compliance error.
   *  If true, returns records with ComplianceErrorCount greater than 0.
   *  If false, returns records with a zero or null error count.
   *  If unset (null), this filter is not applied.
   */
  hasComplianceError: boolean;
  /** Gets or sets the maximum version of the {@link EmissionComplianceEvent} to search for. */
  maxVersion: number;
  /**
   * Gets or sets a value indicating whether to return only the latest {@link EmissionComplianceEvent} for each associated {@link EmissionVehicleEnrollment}.
   *  If true, returns only the most recent event record (by version) per enrollment. The default value is false.
   */
  onlyLatestSubmission: boolean;
  /**
   * Gets or sets the submission schedule type to search for.
   *  Valid values are:
   *  <list type="bullet"><item><description>NextIgnitionOn</description></item><item><description>DateTime</description></item></list>
   */
  scheduleType: string;
  /** Gets or sets the end of the date range (exclusive) to search for events. This property typically filters on the CreatedDateTime of the entity. */
  toDate: Date;
  /** Gets or sets the end of the date range (inclusive) to search for {@link EmissionComplianceEvent} records by their ScheduledDateTime. */
  toScheduledDateTime: Date;
  /** Gets or sets the end of the date range (inclusive) to search for {@link EmissionComplianceEvent} records by their SubmittedDateTime. */
  toSubmittedDateTime: Date;
  /** Gets or sets the minimum version of the {@link EmissionComplianceEvent} to search for. */
  version: number;
}
