//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { DeviceSearch } from "../DeviceSearch";

/** Search class for {@link EmissionVehicleCycle}. */
export interface EmissionVehicleCycleSearch extends Search {
  /**
   * Gets or sets a value indicating whether to search for all {@link EmissionVehicleCycle}s with all messages received.
   *  If true, only returns {@link EmissionVehicleCycle}s for which all messages have been received; otherwise, returns all {@link EmissionVehicleCycle}s.
   *  Default is false.
   */
  allMessagesReceived: boolean;
  /** Gets or sets search for all {@link EmissionVehicleCycle}s with the given cycle ID. */
  cycleId: number;
  /**
   * Gets or sets a value indicating whether to search for {@link EmissionVehicleCycle}s with delivered reports only.
   *  If true, returns {@link EmissionVehicleCycle}s with delivered reports only; otherwise, return all {@link EmissionVehicleCycle}s.
   *  Default is false.
   */
  deliveredReportsOnly: boolean;
  /**
   * Gets or sets the {@link EmissionVehicleCycleSearch.DeviceSearch} to filter the {@link EmissionVehicleCycleSearch} result.
   *  Available DeviceSearch options are:
   *  <list><item><description>Id</description></item><item><description>DeviceIds</description></item></list>
   */
  deviceSearch: DeviceSearch;
  /** Gets or sets search for all {@link EmissionVehicleCycle}s with a specific fatal error. */
  fatalError: number;
  /** Gets or sets search for all {@link EmissionVehicleCycle}s with reports captured from this date. */
  fromDate: Date;
  /** Gets or sets search for all {@link EmissionVehicleCycle}s with reports submitted from this date. */
  fromSubmittedDate: Date;
  /**
   * Gets or sets a value to search for all {@link EmissionVehicleCycle}s with/without any fatal error.
   *  If true, only returns {@link EmissionVehicleCycle}s with fatal error;
   *  If false, only returns {@link EmissionVehicleCycle}s with no fatal error;
   *  If unset, return all {@link EmissionVehicleCycle}s matching other search criteria.
   */
  hasFatalError: boolean;
  /** Gets or sets search for all {@link EmissionVehicleCycle}s with the given protocol. */
  protocol: string;
  /** Gets or sets search for all {@link EmissionVehicleCycle}s with reports captured to this date. */
  toDate: Date;
  /** Gets or sets search for all {@link EmissionVehicleCycle}s with reports submitted to this date. */
  toSubmittedDate: Date;
  /** Gets or sets a value indicating whether to search for {@link EmissionVehicleCycle}s with undelivered reports only. */
  undeliveredReportsOnly: boolean;
}
