//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "../EntityWithVersion";
import { ConsentStatus } from "./ConsentStatus";
import { User } from "../User";

/** The audit records for consentstatus records. */
export interface ConsentStatusAudit extends EntityWithVersion {
  /** Gets or sets the user. */
  consentBy: User;
  /** Gets or sets the consent status ID. */
  consentStatus: ConsentStatus;
  /** Gets or sets the Is Granted. */
  isGranted: boolean;
  /** Gets or sets the timestamp of the consent. */
  start: Date;
  /** Gets or sets the timestamp of the consent last update. */
  timestamp: Date;
  /** Gets or sets the user. */
  user: User;
}
