//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";
import { ProductSearch } from "./ProductSearch";
import { UserSearch } from "../UserSearch";
import { OptionSearch } from "./OptionSearch";

/**
 *  The object used to specify the arguments when searching for {@link ConsentStatus}.
 */
export interface ConsentStatusSearch extends Search {
  /** Gets or sets search with a {@link ConsentStatusSearch.OptionSearch}. */
  optionSearch: OptionSearch;
  /** Gets or sets search based on the version of the Solution. */
  productSearch: ProductSearch;
  /**
   * Gets or sets search with a {@link UserSearch} Id.
   *  Available UserSearch options are:
   *  <list><item><description>Id</description></item></list>
   */
  userSearch: UserSearch;
}
