//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "../EntityWithVersion";
import { Option } from "./Option";
import { User } from "../User";

/** The most updated value regarding authorizations and consents. */
export interface ConsentStatus extends EntityWithVersion {
  /** Gets or sets the user. */
  consentBy: User;
  /** Gets or sets the Is Granted. */
  isGranted: boolean;
  /** Gets or sets the option ID. */
  option: Option;
  /** Gets or sets the timestamp of the consent. */
  timestamp: Date;
  /** Gets or sets the user. */
  user: User;
}
