//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ConsentStatusSearch } from "./ConsentStatusSearch";

/**
 *  The object used to specify the arguments when searching for {@link ConsentStatusAudit}.
 */
export interface ConsentStatusAuditSearch extends ConsentStatusSearch {
  /** Gets or sets search for Data Permissions at this date or after. */
  fromDate: Date;
  /** Gets or sets search for Data Permissions at this date or before. */
  toDate: Date;
}
