//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "../EntityWithVersion";
import { Product } from "./Product";

/** The option for a consent or authorization of a product in the database. */
export interface Option extends EntityWithVersion {
  /** Gets or sets the authorization associated with the option. */
  authOption: Option;
  /** Gets or sets the description of the option. */
  description: string;
  /** Gets or sets the option id. */
  optionId: string;
  /** Gets or sets the product associated with the option. */
  product: Product;
  /** Gets or sets the program to which the option belong to. */
  program: string;
}
