//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";

/** The object used to specify the arguments when searching for {@link Option}. */
export interface OptionSearch extends Search {
  /** Gets or sets the authorization option related to this {@link Option}. */
  authOptionId: string;
  /** Gets or sets the option id related to this {@link Option}. */
  optionId: string;
  /** Gets or sets the Product id related to this. */
  productId: string;
}
