//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../Search";

/** The object used to specify the arguments when searching for {@link Product}. */
export interface ProductSearch extends Search {
  /** Gets or sets the version id related to this {@link Product}. */
  productVersion: string;
  /** Gets or sets the solution id related to this {@link Product}. */
  solutionId: string;
}
