//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Represents the vendor source for enriching data. */
export type FaultRichDataVendorSource = "OnPremise" | "TripVision";
