//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../../Search";
import { DisplayMeasurementProfileSearch } from "./DisplayMeasurementProfileSearch";
import { DiagnosticSearch } from "../DiagnosticSearch";

/**
 * The object used to specify the arguments when searching for a {@link DisplayMeasurementProfileDetail}.
 *  When searching for DisplayMeasurementDProfileDetails including DisplayMeasurementProfileSearch and DiagnosticSearch
 *  the system will return all records that match the search criteria.
 *  This search has been designed to work efficiently with these combinations of parameters:<list><item><description>Id</description></item><item><description>DisplayMeasurementProfileSearch + DiagnosticSearch</description></item></list>
 */
export interface DisplayMeasurementProfileDetailSearch extends Search {
  /**
   * Gets or sets search for DisplayProfileDetail with this {@link DiagnosticSearch} Id.
   *  Available
   *  DiagnosticSearch options are:
   *  <list><item><description>Id</description></item></list>
   */
  diagnosticSearch: DiagnosticSearch;
  /**
   * Gets or sets search for DisplayProfileDetail with this {@link DisplayMeasurementProfileSearch} Id.
   *  Available
   *  DisplayMeasurementProfileSearch options are:
   *  <list><item><description>Id</description></item></list>
   */
  displayMeasurementProfileSearch: DisplayMeasurementProfileSearch;
  /** Gets or sets whether or not to get the display unit of measure details. */
  getUnitDetails: boolean;
}
