//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { NameEntityWithVersion } from "../../NameEntityWithVersion";

/**
 *  Contains the conversion between the base UnitOfMeasure to the DisplayUnitOfMeasure.
 *
 * @deprecated
 */
export interface DisplayUnitOfMeasure extends NameEntityWithVersion {
  /** Gets or sets the Identifier of the base unit of measure. */
  baseId: string;
  /** Gets or sets the conversion factor from base units to the current unit. */
  factorFromBase: number;
  /** Gets or sets a value indicating whether gets or sets whether or not an inversion operation is performed on unit conversion. */
  inversionOperation: boolean;
  /** Gets or sets the offset to convert from base unit to current unit. */
  offsetFromBase: number;
}
