//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Search } from "../../Search";
import { User } from "../../User";

/** The object used to specify the arguments when searching for a {@link UserDisplayProfile}. */
export interface UserDisplayProfileSearch extends Search {
  /** Gets or sets whether or not to get a default profile in user search; the default is not to retrieve a default profile when none is present in database. */
  getDefaultProfile: boolean;
  /** Gets or sets the user. */
  user: User;
}
