//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The supported currency */
export type Currency =
  | "Cad"
  | "Hkd"
  | "Usd"
  | "Aud"
  | "Brl"
  | "Cny"
  | "Eur"
  | "Inr"
  | "Idr"
  | "Jpy"
  | "Myr"
  | "Mxn"
  | "Nzd"
  | "Nok"
  | "Pen"
  | "Php"
  | "Rub"
  | "Sar"
  | "Sgd"
  | "Zar"
  | "Krw"
  | "Sek"
  | "Chf"
  | "Thb"
  | "Twd"
  | "Try"
  | "Gbp";
