//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { Group } from "../Group";

/** Represents the summarized sustainability idling data grouped by year and date for the specified date range. */
export interface SustainabilityGroupIdlingSummary extends Entity {
  /** Gets or sets the power train group associated with the data. */
  powertrainGroup: Group;
  /** Gets or sets the idling summaries for different powertrain groups */
  powertrainIdlingSummaries: unknown[];
}
