//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Group } from "../Group";

/** Represents an electrification summary for a powertrain group. */
export interface SustainabilityPowertrainElectrificationSummary {
  /**
   * Gets or sets the number of vehicles in the fleet that are best suited to be replaced with battery electric
   *  vehicles.
   */
  bevReplacementCount: number;
  /**
   * Gets or sets the number of vehicles in the fleet that are best suited to be replaced with plug-in hybrid
   *  electric vehicles.
   */
  phevReplacementCount: number;
  /**
   * Gets or sets the potential emission savings (CO2) in tons from implementing the suggested vehicle
   *  replacements in the fleet.
   */
  potentialEmissionSavingsTonsCo2: number;
  /**
   * Gets or sets the potential emission savings (CO2-equivalent) in tons from implementing the suggested vehicle
   *  replacements in the fleet.
   */
  potentialEmissionSavingsTonsCo2E: number;
  /** Gets or sets the group associated with the summary data. */
  powertrainGroup: Group;
  /** Gets or sets the total number of vehicles in the fleet. */
  totalVehicleCount: number;
}
