//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Indicates whether administrator of data base requires training or not */
export type RequireTraining = "Unknown" | "Yes" | "No" | "Maybe";
