//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityWithVersion } from "../EntityWithVersion";
import { Device } from "../Device";
import { StatusData } from "../Engine/StatusData";

/** The EVStatusInfo entity provides insights about the current state of an electric vehicle. */
export interface EVStatusInfo extends EntityWithVersion {
  /** Gets or sets the date and time (UTC, ISO 8601 format) when {@link EVStatusInfo} was last updated. */
  dateTime: Date;
  /** Gets or sets the {@link Device} associated with the EVStatusInfo. */
  device: Device;
  /**
   * Gets or sets the unique identifier for the specific {@link Entity} object in the Geotab system. See {@link Id}.
   *  <para />
   *  Note: This property is not available in Beta.
   */
  id: string;
  /**
   * Gets or sets the lower bound estimate for remaining EV range in kilometers (for 90% confidence interval).
   *  <para />
   *  This means there is a 90% probability that the vehicle’s remaining range is between RealTimeRangeRemainingLowerBoundKm and RealTimeRangeRemainingUpperBoundKm.
   */
  realTimeRangeRemainingLowerBoundKm: number;
  /** Gets or sets the estimated remaining range of the electric vehicle in kilometers. */
  realTimeRangeRemainingMeanKm: number;
  /**
   * Gets or sets the upper bound estimate for remaining EV range in kilometers (for 90% confidence interval).
   *  <para />
   *  This means there is a 90% probability that the vehicle’s remaining range is between RealTimeRangeRemainingLowerBoundKm and RealTimeRangeRemainingUpperBoundKm.
   */
  realTimeRangeRemainingUpperBoundKm: number;
  /**
   * Gets or sets the related status data:
   *  <list><item><description>Electric vehicle charging state (0 = not charging, 1 = AC charging, 2 = DC charging)</description></item><item><description>Battery state of charge (%)</description></item><item><description>Electric vehicle battery power (Watts)</description></item></list>
   */
  statusData: StatusData[];
  /** Gets or sets the estimated time (UTC, ISO 8601 format) when the EV battery will reach 100% charge. */
  timeToChargeTo100Percent: Date;
  /** Gets or sets the estimated time (UTC, ISO 8601 format) when the EV battery will reach 80% charge. */
  timeToChargeTo80Percent: Date;
  /** Gets or sets the estimated time (UTC, ISO 8601 format) when the EV battery will reach 90% charge. */
  timeToChargeTo90Percent: Date;
  /**
   * Gets or sets the version of the entity.
   *  <para />
   *  Note: This property is not available in Beta.
   */
  version: number;
}
