//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";

/** Represents the static settings for an EVSA request. Those will not change. */
export interface EvsaRequestSettings extends Entity {
  /** Gets or sets the Cia configuration */
  ciaConfig: string;
  /** Gets or sets the EVSA country code. */
  countryId: string;
  /** Gets or sets the EVSA request Id. */
  evsaRequestId: string;
  /** Gets or sets the {@link EvsaRequestSettings.EvsaVehicleData} associated with the {@link EvsaRequestSettings}. */
  evsaVehicleData: unknown[];
  /** Gets or sets the fuel efficiency */
  fuelEfficiency: string;
}
