//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";

/** Represents the configuration for an EVSA request. */
export interface EvsaConfiguration extends Entity {
  /** Gets or sets the electricity cost. */
  electricityCost: number;
  /** Gets or sets the EV premium. */
  evPremium: number;
  /** Gets or sets the {@link EvsaConfiguration.EvsaFleetVehicleSizes} associated with the {@link EvsaConfiguration}. */
  evsaFleetVehicleSizes: unknown[];
  /** Gets or sets the EVSA request Id. */
  evsaRequestId: string;
  /** Gets or sets the {@link EvsaConfiguration.EvsaVehicleEstimates} associated with the {@link EvsaConfiguration}. */
  evsaVehicleEstimates: unknown[];
  /** Gets or sets the fuel cost. */
  fuelCost: number;
  /** Gets or sets the monthly enroute charge. */
  monthlyEnrouteCharge: number;
  /** Gets or sets a value indicating whether BEV (Battery Electric Vehicle) is preferred. */
  preferBev: boolean;
  /** Gets or sets the Id of the procurement period. */
  procurementPeriodId: number;
  /** Gets or sets the procurement type. */
  procurementType: string;
  /** Gets or sets the selected non-EV vehicles (as a text representation, likely comma-separated IDs). */
  selectedNonEv: string;
}
