//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { EvsaConfiguration } from "./EvsaConfiguration";
import { EvsaRequestSettings } from "./EvsaRequestSettings";
import { Group } from "../Group";

/** Represents a EV Suitability Assessment request. */
export interface EvsaRequest extends Entity {
  /** Gets or sets the assessment name. */
  assessmentName: string;
  /** Gets or sets the assets count. */
  assetsCount: number;
  /** Gets or sets the {@link EvsaRequest.EvsaConfiguration} associated with the {@link EvsaRequest}. */
  evsaConfiguration: EvsaConfiguration;
  /** Gets or sets the date and time (UTC, ISO 8601 format) when the {@link EvsaRequest} was triggered. */
  evsaDateTime: Date;
  /** Gets or sets the {@link EvsaRequest.EvsaRequestSettings} associated with the {@link EvsaRequest}. */
  evsaRequestSettings: EvsaRequestSettings;
  /** Gets or sets the group(s) this preset belongs to. */
  groups: Group[];
  /** Gets or sets a value indicating whether the evsa report was opened. */
  isOpened: boolean;
  /** Gets or sets the job Id of the EVSA request. */
  jobId: string;
  /** Gets or sets the status of the evsa request. */
  status: string;
  /** Gets or sets the Id of the user triggering the EVSA. */
  userId: string;
}
