//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { User } from "../User";

/** Represents a request to reprocess driver regulations (violations and availability). */
export interface DriverRegulationReprocessRequest extends Entity {
  /** Gets or sets a value indicating the date the reprocess request was created. */
  createdDate: Date;
  /**
   * @inheritdoc
   */
  dateTime: Date;
  /** Gets or sets a value indicating the cutoff date for reprocessing. */
  fromDate: Date;
  /** Gets or sets a value indicating the user who requested the reprocess. */
  requestedBy: string;
  /**
   * Gets or sets a value describing the current status of the driver regulation reprocess request.
   *  See {@link DriverRegulationReprocessRequestStatus} for valid values.
   */
  status: string;
  /** Gets or sets the user for whom to reprocess driver regulations. */
  user: User;
}
