//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Describes the state of a {@link DriverRegulationReprocessRequest}. */
export type DriverRegulationReprocessRequestStatus =
  | "Scheduled"
  | "Processing"
  | "Success"
  | "Failure"
  | "Cancelled";
