//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Represents the current type of the charge. */
export enum ChargeType {
  /** Alternating Current. */
  AC = "AC",
  /** Direct Current. */
  DC = "DC",
  /** Charge type is unknown. */
  Unknown = "Unknown",
}
