//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The charging state as reported by the device. */
export type DeviceReportedChargingState =
  | "NotCharging"
  | "ACCharging"
  | "DCCharging"
  | "ChargingUnknownSource";
