//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { Device } from "../Device";
import { ReprocessRequestStatus } from "./ReprocessRequestStatus";

/** Represents a request to reprocess data for a specific device. */
export interface DeviceReprocessRequest extends Entity {
  /** Gets the FromDate. Required by {@link IDateTimeProvider}. See {@link DeviceReprocessRequest.FromDate}. */
  dateTime: Date;
  /** Gets or sets the device for which data will be reprocessed. */
  device: Device;
  /** Gets or sets a value indicating the cutoff date for reprocssing. */
  fromDate: Date;
  /** Gets a value indicating whether this request is in a terminal state. */
  isComplete: boolean;
  /**
   * Gets a value indicating whether all data will be reprocessed. If   then all data will
   *  be reprocessed. If   then only rules will be re-evaluated.
   */
  isCompleteReprocess: boolean;
  /** Gets or sets the {@link Id} that uniquely identifies the parent {@link ReprocessRequest}. */
  reprocessRequestId: string;
  /**
   * Gets or sets the list of Rule Ids to re-evaluate. If left blank, rules will not be re-evaluated, and
   *  existing exceptions will not be modified.
   */
  ruleIds: string[];
  /** Gets or sets a value representing the current status of the {@link DeviceReprocessRequest}. */
  status: ReprocessRequestStatus;
  /**
   * Gets or sets additional information regarding the current status of the
   *  {@link DeviceReprocessRequest}.
   */
  statusText: string;
}
