//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from "../Entity";
import { FilterType } from "./FilterType";
import { DeviceSearch } from "../DeviceSearch";
import { ReprocessRequestStatus } from "./ReprocessRequestStatus";

/** Represents a request to reprocess data for one or more devices. */
export interface ReprocessRequest extends Entity {
  /** Gets the DateTime. Required by {@link IDateTimeProvider}. */
  dateTime: Date;
  /**
   * Gets or sets the list of Ids that represent a filter that can be resolved to a list of Devices. How
   *  these Ids are resolved depends on the {@link FilterType}.
   */
  deviceFilterIds: string[];
  /**
   * Gets or sets a value indicating the type of filter used to identify the Devices that this
   *  {@link ReprocessRequest} applies to.
   */
  deviceFilterType: FilterType;
  /** Gets or sets the logical groups filter that can be resolved to a list of Devices. */
  deviceSearchFilter: DeviceSearch;
  /** Gets or sets a value indicating the cutoff date for reprocssing. */
  fromDate: Date;
  /** Gets or sets a value indicating the user who requested the reprocess. */
  requestedBy: string;
  /**
   * Gets or sets the list of Rule Ids to re-evaluate. If left blank, rules will not be re-evaluated, and
   *  existing exceptions will not be modified.
   */
  ruleIds: string[];
  /** Gets or sets a value describes the current status of the Reprocess Request as a whole. */
  status: ReprocessRequestStatus;
  /** Gets or sets additional information regarding the current status of the {@link ReprocessRequest}. */
  statusText: string;
}
