//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The currently supported exception info tag key. */
export type ExceptionInfoTag =
  | "Database"
  | "Source"
  | "Area"
  | "SeverityLevel"
  | "Description"
  | "Warning"
  | "UserName";
