//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The currently supported Sql Database types. */
export enum SqlType {
  /** Empty type not yet set. */
  Empty = "Empty",
  /** Unknown database type. */
  Unknown = "Unknown",
  /** Microsoft SQL Server database. */
  MSSqlServer2000 = "MSSqlServer2000",
  /** Postgres database. */
  Postgres = "Postgres",
  /** Google Cloud Spanner database. */
  Spanner = "Spanner",
}
