//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** The currently supported Sql Database types. */
export type SqlType =
  | "Empty"
  | "Unknown"
  | "MSSqlServer2000"
  | "Postgres"
  | "Spanner";
