//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/** Represents the result of an operation performed on a device. */
export type MyAdminResult =
  | "Unknown"
  | "DeviceStatusChanged"
  | "DeviceAddedAndStatusChanged"
  | "ErrorDeviceNotCreated"
  | "ErrorStatusNotChanged"
  | "TestModeResponse";
