name: Test Report
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Tests
          path: "*.xml"
          reporter: jest-junit
